// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: common.define.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace KazusaHSR.Protocol
{

    [global::ProtoBuf.ProtoContract()]
    public partial class PlayerBasicInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"nickname")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Nickname
        {
            get => __pbn__Nickname ?? "";
            set => __pbn__Nickname = value;
        }
        public bool ShouldSerializeNickname() => __pbn__Nickname != null;
        public void ResetNickname() => __pbn__Nickname = null;
        private string __pbn__Nickname;

        [global::ProtoBuf.ProtoMember(2, Name = @"level")]
        public uint Level
        {
            get => __pbn__Level.GetValueOrDefault();
            set => __pbn__Level = value;
        }
        public bool ShouldSerializeLevel() => __pbn__Level != null;
        public void ResetLevel() => __pbn__Level = null;
        private uint? __pbn__Level;

        [global::ProtoBuf.ProtoMember(3, Name = @"exp")]
        public uint Exp
        {
            get => __pbn__Exp.GetValueOrDefault();
            set => __pbn__Exp = value;
        }
        public bool ShouldSerializeExp() => __pbn__Exp != null;
        public void ResetExp() => __pbn__Exp = null;
        private uint? __pbn__Exp;

        [global::ProtoBuf.ProtoMember(4, Name = @"stamina")]
        public uint Stamina
        {
            get => __pbn__Stamina.GetValueOrDefault();
            set => __pbn__Stamina = value;
        }
        public bool ShouldSerializeStamina() => __pbn__Stamina != null;
        public void ResetStamina() => __pbn__Stamina = null;
        private uint? __pbn__Stamina;

        [global::ProtoBuf.ProtoMember(5, Name = @"mcoin")]
        public uint Mcoin
        {
            get => __pbn__Mcoin.GetValueOrDefault();
            set => __pbn__Mcoin = value;
        }
        public bool ShouldSerializeMcoin() => __pbn__Mcoin != null;
        public void ResetMcoin() => __pbn__Mcoin = null;
        private uint? __pbn__Mcoin;

        [global::ProtoBuf.ProtoMember(6, Name = @"hcoin")]
        public uint Hcoin
        {
            get => __pbn__Hcoin.GetValueOrDefault();
            set => __pbn__Hcoin = value;
        }
        public bool ShouldSerializeHcoin() => __pbn__Hcoin != null;
        public void ResetHcoin() => __pbn__Hcoin = null;
        private uint? __pbn__Hcoin;

        [global::ProtoBuf.ProtoMember(7, Name = @"scoin")]
        public uint Scoin
        {
            get => __pbn__Scoin.GetValueOrDefault();
            set => __pbn__Scoin = value;
        }
        public bool ShouldSerializeScoin() => __pbn__Scoin != null;
        public void ResetScoin() => __pbn__Scoin = null;
        private uint? __pbn__Scoin;

        [global::ProtoBuf.ProtoMember(8, Name = @"world_level")]
        public uint WorldLevel
        {
            get => __pbn__WorldLevel.GetValueOrDefault();
            set => __pbn__WorldLevel = value;
        }
        public bool ShouldSerializeWorldLevel() => __pbn__WorldLevel != null;
        public void ResetWorldLevel() => __pbn__WorldLevel = null;
        private uint? __pbn__WorldLevel;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BlackInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"begin_time")]
        public uint BeginTime
        {
            get => __pbn__BeginTime.GetValueOrDefault();
            set => __pbn__BeginTime = value;
        }
        public bool ShouldSerializeBeginTime() => __pbn__BeginTime != null;
        public void ResetBeginTime() => __pbn__BeginTime = null;
        private uint? __pbn__BeginTime;

        [global::ProtoBuf.ProtoMember(2, Name = @"end_time")]
        public uint EndTime
        {
            get => __pbn__EndTime.GetValueOrDefault();
            set => __pbn__EndTime = value;
        }
        public bool ShouldSerializeEndTime() => __pbn__EndTime != null;
        public void ResetEndTime() => __pbn__EndTime = null;
        private uint? __pbn__EndTime;

        [global::ProtoBuf.ProtoMember(3, Name = @"limit_level")]
        public uint LimitLevel
        {
            get => __pbn__LimitLevel.GetValueOrDefault();
            set => __pbn__LimitLevel = value;
        }
        public bool ShouldSerializeLimitLevel() => __pbn__LimitLevel != null;
        public void ResetLimitLevel() => __pbn__LimitLevel = null;
        private uint? __pbn__LimitLevel;

        [global::ProtoBuf.ProtoMember(4, Name = @"ban_type")]
        public uint BanType
        {
            get => __pbn__BanType.GetValueOrDefault();
            set => __pbn__BanType = value;
        }
        public bool ShouldSerializeBanType() => __pbn__BanType != null;
        public void ResetBanType() => __pbn__BanType = null;
        private uint? __pbn__BanType;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class VersionCount : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"version")]
        public uint Version
        {
            get => __pbn__Version.GetValueOrDefault();
            set => __pbn__Version = value;
        }
        public bool ShouldSerializeVersion() => __pbn__Version != null;
        public void ResetVersion() => __pbn__Version = null;
        private uint? __pbn__Version;

        [global::ProtoBuf.ProtoMember(2, Name = @"count")]
        public uint Count
        {
            get => __pbn__Count.GetValueOrDefault();
            set => __pbn__Count = value;
        }
        public bool ShouldSerializeCount() => __pbn__Count != null;
        public void ResetCount() => __pbn__Count = null;
        private uint? __pbn__Count;

    }

    [global::ProtoBuf.ProtoContract()]
    public enum AccountType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"ACCOUNT_MIHOYO_GUEST")]
        AccountMihoyoGuest = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"ACCOUNT_MIHOYO")]
        AccountMihoyo = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"ACCOUNT_XIAOMI")]
        AccountXiaomi = 11,
        [global::ProtoBuf.ProtoEnum(Name = @"ACCOUNT_COOLPAD")]
        AccountCoolpad = 12,
        [global::ProtoBuf.ProtoEnum(Name = @"ACCOUNT_YYB")]
        AccountYyb = 13,
        [global::ProtoBuf.ProtoEnum(Name = @"ACCOUNT_BILI")]
        AccountBili = 14,
        [global::ProtoBuf.ProtoEnum(Name = @"ACCOUNT_HUAWEI")]
        AccountHuawei = 15,
        [global::ProtoBuf.ProtoEnum(Name = @"ACCOUNT_MEIZU")]
        AccountMeizu = 16,
        [global::ProtoBuf.ProtoEnum(Name = @"ACCOUNT_360")]
        Account360 = 17,
        [global::ProtoBuf.ProtoEnum(Name = @"ACCOUNT_OPPO")]
        AccountOppo = 18,
        [global::ProtoBuf.ProtoEnum(Name = @"ACCOUNT_VIVO")]
        AccountVivo = 19,
        [global::ProtoBuf.ProtoEnum(Name = @"ACCOUNT_UC")]
        AccountUc = 20,
        [global::ProtoBuf.ProtoEnum(Name = @"ACCOUNT_WANDOJIA")]
        AccountWandojia = 21,
        [global::ProtoBuf.ProtoEnum(Name = @"ACCOUNT_LENOVO")]
        AccountLenovo = 22,
        [global::ProtoBuf.ProtoEnum(Name = @"ACCOUNT_JINLI")]
        AccountJinli = 23,
        [global::ProtoBuf.ProtoEnum(Name = @"ACCOUNT_BAIDU")]
        AccountBaidu = 25,
        [global::ProtoBuf.ProtoEnum(Name = @"ACCOUNT_DANGLE")]
        AccountDangle = 26,
        [global::ProtoBuf.ProtoEnum(Name = @"ACCOUNT_WEGAME")]
        AccountWegame = 27,
        [global::ProtoBuf.ProtoEnum(Name = @"ACCOUNT_RPG_CUSTOM")]
        AccountRpgCustom = 10000,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum ChannelIdType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"CHANNEL_ID_NONE")]
        ChannelIdNone = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"CHANNEL_ID_MIHOYO")]
        ChannelIdMihoyo = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"CHANNEL_ID_XIAOMI")]
        ChannelIdXiaomi = 11,
        [global::ProtoBuf.ProtoEnum(Name = @"CHANNEL_ID_COOLPAD")]
        ChannelIdCoolpad = 12,
        [global::ProtoBuf.ProtoEnum(Name = @"CHANNEL_ID_YYB")]
        ChannelIdYyb = 13,
        [global::ProtoBuf.ProtoEnum(Name = @"CHANNEL_ID_BILI")]
        ChannelIdBili = 14,
        [global::ProtoBuf.ProtoEnum(Name = @"CHANNEL_ID_HUAWEI")]
        ChannelIdHuawei = 15,
        [global::ProtoBuf.ProtoEnum(Name = @"CHANNEL_ID_MEIZU")]
        ChannelIdMeizu = 16,
        [global::ProtoBuf.ProtoEnum(Name = @"CHANNEL_ID_360")]
        ChannelId360 = 17,
        [global::ProtoBuf.ProtoEnum(Name = @"CHANNEL_ID_OPPO")]
        ChannelIdOppo = 18,
        [global::ProtoBuf.ProtoEnum(Name = @"CHANNEL_ID_VIVO")]
        ChannelIdVivo = 19,
        [global::ProtoBuf.ProtoEnum(Name = @"CHANNEL_ID_UC")]
        ChannelIdUc = 20,
        [global::ProtoBuf.ProtoEnum(Name = @"CHANNEL_ID_WANDOJIA")]
        ChannelIdWandojia = 21,
        [global::ProtoBuf.ProtoEnum(Name = @"CHANNEL_ID_LENOVO")]
        ChannelIdLenovo = 22,
        [global::ProtoBuf.ProtoEnum(Name = @"CHANNEL_ID_JINLI")]
        ChannelIdJinli = 23,
        [global::ProtoBuf.ProtoEnum(Name = @"CHANNEL_ID_BAIDU")]
        ChannelIdBaidu = 25,
        [global::ProtoBuf.ProtoEnum(Name = @"CHANNEL_ID_DANGLE")]
        ChannelIdDangle = 26,
        [global::ProtoBuf.ProtoEnum(Name = @"CHANNEL_ID_WEGAME")]
        ChannelIdWegame = 27,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum AvatarSlotType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"AVATAR_SLOT_1")]
        AvatarSlot1 = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"AVATAR_SLOT_2")]
        AvatarSlot2 = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"AVATAR_SLOT_3")]
        AvatarSlot3 = 2,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum ItemType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"ITEM_TYPE_NONE")]
        ItemTypeNone = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"ITEM_AVATAR_CARD")]
        ItemAvatarCard = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"ITEM_EQUIPMENT")]
        ItemEquipment = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"ITEM_MATERIAL")]
        ItemMaterial = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"ITEM_AVATAR_EXP")]
        ItemAvatarExp = 4,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum VirtualItemType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"VIRTUAL_ITEM_NONE")]
        VirtualItemNone = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"VIRTUAL_ITEM_HCOIN")]
        VirtualItemHcoin = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"VIRTUAL_ITEM_SCOIN")]
        VirtualItemScoin = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"VIRTUAL_ITEM_MCOIN")]
        VirtualItemMcoin = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"VIRTUAL_ITEM_STAMINA")]
        VirtualItemStamina = 11,
        [global::ProtoBuf.ProtoEnum(Name = @"VIRTUAL_ITEM_EXP")]
        VirtualItemExp = 22,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum BlackLimitLevel
    {
        [global::ProtoBuf.ProtoEnum(Name = @"BLACK_LIMIT_LEVEL_ALL")]
        BlackLimitLevelAll = 0,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum AreaType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"AREA_NONE")]
        AreaNone = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"AREA_CN")]
        AreaCn = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"AREA_JP")]
        AreaJp = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"AREA_ASIA")]
        AreaAsia = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"AREA_WEST")]
        AreaWest = 4,
        [global::ProtoBuf.ProtoEnum(Name = @"AREA_KR")]
        AreaKr = 5,
        [global::ProtoBuf.ProtoEnum(Name = @"AREA_OVERSEAS")]
        AreaOverseas = 6,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum EntityType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"ENTITY_NONE")]
        EntityNone = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"ENTITY_AVATAR")]
        EntityAvatar = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"ENTITY_MONSTER")]
        EntityMonster = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"ENTITY_NPC")]
        EntityNpc = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"ENTITY_PROP")]
        EntityProp = 4,
        [global::ProtoBuf.ProtoEnum(Name = @"ENTITY_TRIGGER")]
        EntityTrigger = 5,
        [global::ProtoBuf.ProtoEnum(Name = @"ENTITY_ENV")]
        EntityEnv = 6,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum LanguageType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"LANGUAGE_NONE")]
        LanguageNone = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"LANGUAGE_SC")]
        LanguageSc = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"LANGUAGE_TC")]
        LanguageTc = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"LANGUAGE_EN")]
        LanguageEn = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"LANGUAGE_KR")]
        LanguageKr = 4,
        [global::ProtoBuf.ProtoEnum(Name = @"LANGUAGE_JP")]
        LanguageJp = 5,
        [global::ProtoBuf.ProtoEnum(Name = @"LANGUAGE_FR")]
        LanguageFr = 6,
        [global::ProtoBuf.ProtoEnum(Name = @"LANGUAGE_DE")]
        LanguageDe = 7,
        [global::ProtoBuf.ProtoEnum(Name = @"LANGUAGE_ES")]
        LanguageEs = 8,
        [global::ProtoBuf.ProtoEnum(Name = @"LANGUAGE_PT")]
        LanguagePt = 9,
        [global::ProtoBuf.ProtoEnum(Name = @"LANGUAGE_RU")]
        LanguageRu = 10,
        [global::ProtoBuf.ProtoEnum(Name = @"LANGUAGE_TH")]
        LanguageTh = 11,
        [global::ProtoBuf.ProtoEnum(Name = @"LANGUAGE_VI")]
        LanguageVi = 12,
        [global::ProtoBuf.ProtoEnum(Name = @"LANGUAGE_ID")]
        LanguageId = 13,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum PlatformType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"EDITOR")]
        Editor = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"IOS")]
        Ios = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"ANDROID")]
        Android = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"PC")]
        Pc = 3,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum ReloginType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"NO_KICK")]
        NoKick = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"FORCE_KICK")]
        ForceKick = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"IDLE_KICK")]
        IdleKick = 2,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum AvatarType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"AVATAR_TYPE_NONE")]
        AvatarTypeNone = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"AVATAR_TRIAL_TYPE")]
        AvatarTrialType = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"AVATAR_LIMIT_TYPE")]
        AvatarLimitType = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"AVATAR_FORMAL_TYPE")]
        AvatarFormalType = 3,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
