// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: common.gamecore.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace KazusaHSR.Protocol
{

    [global::ProtoBuf.ProtoContract()]
    public partial class BattleOp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"turn_counter")]
        public uint TurnCounter
        {
            get => __pbn__TurnCounter.GetValueOrDefault();
            set => __pbn__TurnCounter = value;
        }
        public bool ShouldSerializeTurnCounter() => __pbn__TurnCounter != null;
        public void ResetTurnCounter() => __pbn__TurnCounter = null;
        private uint? __pbn__TurnCounter;

        [global::ProtoBuf.ProtoMember(2, Name = @"state")]
        public uint State
        {
            get => __pbn__State.GetValueOrDefault();
            set => __pbn__State = value;
        }
        public bool ShouldSerializeState() => __pbn__State != null;
        public void ResetState() => __pbn__State = null;
        private uint? __pbn__State;

        [global::ProtoBuf.ProtoMember(3, Name = @"action_entity_id")]
        public uint ActionEntityId
        {
            get => __pbn__ActionEntityId.GetValueOrDefault();
            set => __pbn__ActionEntityId = value;
        }
        public bool ShouldSerializeActionEntityId() => __pbn__ActionEntityId != null;
        public void ResetActionEntityId() => __pbn__ActionEntityId = null;
        private uint? __pbn__ActionEntityId;

        [global::ProtoBuf.ProtoMember(4, Name = @"target_entity_id")]
        public uint TargetEntityId
        {
            get => __pbn__TargetEntityId.GetValueOrDefault();
            set => __pbn__TargetEntityId = value;
        }
        public bool ShouldSerializeTargetEntityId() => __pbn__TargetEntityId != null;
        public void ResetTargetEntityId() => __pbn__TargetEntityId = null;
        private uint? __pbn__TargetEntityId;

        [global::ProtoBuf.ProtoMember(5, Name = @"op_type")]
        public uint OpType
        {
            get => __pbn__OpType.GetValueOrDefault();
            set => __pbn__OpType = value;
        }
        public bool ShouldSerializeOpType() => __pbn__OpType != null;
        public void ResetOpType() => __pbn__OpType = null;
        private uint? __pbn__OpType;

        [global::ProtoBuf.ProtoMember(6, Name = @"skill_index")]
        public uint SkillIndex
        {
            get => __pbn__SkillIndex.GetValueOrDefault();
            set => __pbn__SkillIndex = value;
        }
        public bool ShouldSerializeSkillIndex() => __pbn__SkillIndex != null;
        public void ResetSkillIndex() => __pbn__SkillIndex = null;
        private uint? __pbn__SkillIndex;

        [global::ProtoBuf.ProtoMember(7, Name = @"operation_counter")]
        public uint OperationCounter
        {
            get => __pbn__OperationCounter.GetValueOrDefault();
            set => __pbn__OperationCounter = value;
        }
        public bool ShouldSerializeOperationCounter() => __pbn__OperationCounter != null;
        public void ResetOperationCounter() => __pbn__OperationCounter = null;
        private uint? __pbn__OperationCounter;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BattleEquipment : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public uint Id
        {
            get => __pbn__Id.GetValueOrDefault();
            set => __pbn__Id = value;
        }
        public bool ShouldSerializeId() => __pbn__Id != null;
        public void ResetId() => __pbn__Id = null;
        private uint? __pbn__Id;

        [global::ProtoBuf.ProtoMember(2, Name = @"level")]
        public uint Level
        {
            get => __pbn__Level.GetValueOrDefault();
            set => __pbn__Level = value;
        }
        public bool ShouldSerializeLevel() => __pbn__Level != null;
        public void ResetLevel() => __pbn__Level = null;
        private uint? __pbn__Level;

        [global::ProtoBuf.ProtoMember(3, Name = @"promotion")]
        public uint Promotion
        {
            get => __pbn__Promotion.GetValueOrDefault();
            set => __pbn__Promotion = value;
        }
        public bool ShouldSerializePromotion() => __pbn__Promotion != null;
        public void ResetPromotion() => __pbn__Promotion = null;
        private uint? __pbn__Promotion;

        [global::ProtoBuf.ProtoMember(4, Name = @"rank")]
        public uint Rank
        {
            get => __pbn__Rank.GetValueOrDefault();
            set => __pbn__Rank = value;
        }
        public bool ShouldSerializeRank() => __pbn__Rank != null;
        public void ResetRank() => __pbn__Rank = null;
        private uint? __pbn__Rank;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AvatarSkillTree : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"point_id")]
        public uint PointId
        {
            get => __pbn__PointId.GetValueOrDefault();
            set => __pbn__PointId = value;
        }
        public bool ShouldSerializePointId() => __pbn__PointId != null;
        public void ResetPointId() => __pbn__PointId = null;
        private uint? __pbn__PointId;

        [global::ProtoBuf.ProtoMember(2, Name = @"level")]
        public uint Level
        {
            get => __pbn__Level.GetValueOrDefault();
            set => __pbn__Level = value;
        }
        public bool ShouldSerializeLevel() => __pbn__Level != null;
        public void ResetLevel() => __pbn__Level = null;
        private uint? __pbn__Level;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BattleAvatar : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"avatar_type")]
        public AvatarType AvatarType
        {
            get => __pbn__AvatarType.GetValueOrDefault();
            set => __pbn__AvatarType = value;
        }
        public bool ShouldSerializeAvatarType() => __pbn__AvatarType != null;
        public void ResetAvatarType() => __pbn__AvatarType = null;
        private AvatarType? __pbn__AvatarType;

        [global::ProtoBuf.ProtoMember(2, Name = @"id")]
        public uint Id
        {
            get => __pbn__Id.GetValueOrDefault();
            set => __pbn__Id = value;
        }
        public bool ShouldSerializeId() => __pbn__Id != null;
        public void ResetId() => __pbn__Id = null;
        private uint? __pbn__Id;

        [global::ProtoBuf.ProtoMember(3, Name = @"level")]
        public uint Level
        {
            get => __pbn__Level.GetValueOrDefault();
            set => __pbn__Level = value;
        }
        public bool ShouldSerializeLevel() => __pbn__Level != null;
        public void ResetLevel() => __pbn__Level = null;
        private uint? __pbn__Level;

        [global::ProtoBuf.ProtoMember(4, Name = @"rank")]
        public uint Rank
        {
            get => __pbn__Rank.GetValueOrDefault();
            set => __pbn__Rank = value;
        }
        public bool ShouldSerializeRank() => __pbn__Rank != null;
        public void ResetRank() => __pbn__Rank = null;
        private uint? __pbn__Rank;

        [global::ProtoBuf.ProtoMember(5, Name = @"index")]
        public uint Index
        {
            get => __pbn__Index.GetValueOrDefault();
            set => __pbn__Index = value;
        }
        public bool ShouldSerializeIndex() => __pbn__Index != null;
        public void ResetIndex() => __pbn__Index = null;
        private uint? __pbn__Index;

        [global::ProtoBuf.ProtoMember(6, Name = @"skilltree_list")]
        public global::System.Collections.Generic.List<AvatarSkillTree> SkilltreeLists { get; } = new global::System.Collections.Generic.List<AvatarSkillTree>();

        [global::ProtoBuf.ProtoMember(7, Name = @"equipment_list")]
        public global::System.Collections.Generic.List<BattleEquipment> EquipmentLists { get; } = new global::System.Collections.Generic.List<BattleEquipment>();

        [global::ProtoBuf.ProtoMember(8, Name = @"hp")]
        public uint Hp
        {
            get => __pbn__Hp.GetValueOrDefault();
            set => __pbn__Hp = value;
        }
        public bool ShouldSerializeHp() => __pbn__Hp != null;
        public void ResetHp() => __pbn__Hp = null;
        private uint? __pbn__Hp;

        [global::ProtoBuf.ProtoMember(9, Name = @"sp")]
        public uint Sp
        {
            get => __pbn__Sp.GetValueOrDefault();
            set => __pbn__Sp = value;
        }
        public bool ShouldSerializeSp() => __pbn__Sp != null;
        public void ResetSp() => __pbn__Sp = null;
        private uint? __pbn__Sp;

        [global::ProtoBuf.ProtoMember(10, Name = @"promotion")]
        public uint Promotion
        {
            get => __pbn__Promotion.GetValueOrDefault();
            set => __pbn__Promotion = value;
        }
        public bool ShouldSerializePromotion() => __pbn__Promotion != null;
        public void ResetPromotion() => __pbn__Promotion = null;
        private uint? __pbn__Promotion;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BattleMonsterWave : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"monster_id_list", IsPacked = true)]
        public uint[] MonsterIdLists { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BattleBuff : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public uint Id
        {
            get => __pbn__Id.GetValueOrDefault();
            set => __pbn__Id = value;
        }
        public bool ShouldSerializeId() => __pbn__Id != null;
        public void ResetId() => __pbn__Id = null;
        private uint? __pbn__Id;

        [global::ProtoBuf.ProtoMember(2, Name = @"level")]
        public uint Level
        {
            get => __pbn__Level.GetValueOrDefault();
            set => __pbn__Level = value;
        }
        public bool ShouldSerializeLevel() => __pbn__Level != null;
        public void ResetLevel() => __pbn__Level = null;
        private uint? __pbn__Level;

        [global::ProtoBuf.ProtoMember(3, Name = @"owner_index")]
        public uint OwnerIndex
        {
            get => __pbn__OwnerIndex.GetValueOrDefault();
            set => __pbn__OwnerIndex = value;
        }
        public bool ShouldSerializeOwnerIndex() => __pbn__OwnerIndex != null;
        public void ResetOwnerIndex() => __pbn__OwnerIndex = null;
        private uint? __pbn__OwnerIndex;

        [global::ProtoBuf.ProtoMember(4, Name = @"wave_flag")]
        public uint WaveFlag
        {
            get => __pbn__WaveFlag.GetValueOrDefault();
            set => __pbn__WaveFlag = value;
        }
        public bool ShouldSerializeWaveFlag() => __pbn__WaveFlag != null;
        public void ResetWaveFlag() => __pbn__WaveFlag = null;
        private uint? __pbn__WaveFlag;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BattleLineup : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"avatar_list")]
        public global::System.Collections.Generic.List<BattleAvatar> AvatarLists { get; } = new global::System.Collections.Generic.List<BattleAvatar>();

        [global::ProtoBuf.ProtoMember(2, Name = @"monster_wave_list")]
        public global::System.Collections.Generic.List<BattleMonsterWave> MonsterWaveLists { get; } = new global::System.Collections.Generic.List<BattleMonsterWave>();

        [global::ProtoBuf.ProtoMember(3, Name = @"buff_list")]
        public global::System.Collections.Generic.List<BattleBuff> BuffLists { get; } = new global::System.Collections.Generic.List<BattleBuff>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ClientTurnSnapshot : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"turn_counter")]
        public uint TurnCounter
        {
            get => __pbn__TurnCounter.GetValueOrDefault();
            set => __pbn__TurnCounter = value;
        }
        public bool ShouldSerializeTurnCounter() => __pbn__TurnCounter != null;
        public void ResetTurnCounter() => __pbn__TurnCounter = null;
        private uint? __pbn__TurnCounter;

        [global::ProtoBuf.ProtoMember(2, Name = @"random_counter")]
        public uint RandomCounter
        {
            get => __pbn__RandomCounter.GetValueOrDefault();
            set => __pbn__RandomCounter = value;
        }
        public bool ShouldSerializeRandomCounter() => __pbn__RandomCounter != null;
        public void ResetRandomCounter() => __pbn__RandomCounter = null;
        private uint? __pbn__RandomCounter;

        [global::ProtoBuf.ProtoMember(3, Name = @"anim_event_counter")]
        public uint AnimEventCounter
        {
            get => __pbn__AnimEventCounter.GetValueOrDefault();
            set => __pbn__AnimEventCounter = value;
        }
        public bool ShouldSerializeAnimEventCounter() => __pbn__AnimEventCounter != null;
        public void ResetAnimEventCounter() => __pbn__AnimEventCounter = null;
        private uint? __pbn__AnimEventCounter;

        [global::ProtoBuf.ProtoMember(4, Name = @"snapshot_list")]
        public global::System.Collections.Generic.List<CharacterSnapshot> SnapshotLists { get; } = new global::System.Collections.Generic.List<CharacterSnapshot>();

        [global::ProtoBuf.ProtoMember(5, Name = @"anim_event_list")]
        public global::System.Collections.Generic.List<AnimEventSnapshot> AnimEventLists { get; } = new global::System.Collections.Generic.List<AnimEventSnapshot>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GamecoreConfig : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"is_skip_verify")]
        public bool IsSkipVerify
        {
            get => __pbn__IsSkipVerify.GetValueOrDefault();
            set => __pbn__IsSkipVerify = value;
        }
        public bool ShouldSerializeIsSkipVerify() => __pbn__IsSkipVerify != null;
        public void ResetIsSkipVerify() => __pbn__IsSkipVerify = null;
        private bool? __pbn__IsSkipVerify;

        [global::ProtoBuf.ProtoMember(2, Name = @"max_turn_cnt")]
        public uint MaxTurnCnt
        {
            get => __pbn__MaxTurnCnt.GetValueOrDefault();
            set => __pbn__MaxTurnCnt = value;
        }
        public bool ShouldSerializeMaxTurnCnt() => __pbn__MaxTurnCnt != null;
        public void ResetMaxTurnCnt() => __pbn__MaxTurnCnt = null;
        private uint? __pbn__MaxTurnCnt;

        [global::ProtoBuf.ProtoMember(3, Name = @"is_auto_fight")]
        public bool IsAutoFight
        {
            get => __pbn__IsAutoFight.GetValueOrDefault();
            set => __pbn__IsAutoFight = value;
        }
        public bool ShouldSerializeIsAutoFight() => __pbn__IsAutoFight != null;
        public void ResetIsAutoFight() => __pbn__IsAutoFight = null;
        private bool? __pbn__IsAutoFight;

        [global::ProtoBuf.ProtoMember(4, Name = @"csv_path")]
        [global::System.ComponentModel.DefaultValue("")]
        public string CsvPath
        {
            get => __pbn__CsvPath ?? "";
            set => __pbn__CsvPath = value;
        }
        public bool ShouldSerializeCsvPath() => __pbn__CsvPath != null;
        public void ResetCsvPath() => __pbn__CsvPath = null;
        private string __pbn__CsvPath;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BattleBuffMsg : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"buff_id_list", IsPacked = true)]
        public uint[] BuffIdLists { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"buff_index_list", IsPacked = true)]
        public uint[] BuffIndexLists { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"buff_level_list", IsPacked = true)]
        public uint[] BuffLevelLists { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"buff_flag_list", IsPacked = true)]
        public uint[] BuffFlagLists { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BattleReplay : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"version")]
        public uint Version
        {
            get => __pbn__Version.GetValueOrDefault();
            set => __pbn__Version = value;
        }
        public bool ShouldSerializeVersion() => __pbn__Version != null;
        public void ResetVersion() => __pbn__Version = null;
        private uint? __pbn__Version;

        [global::ProtoBuf.ProtoMember(2, Name = @"logic_random_seed")]
        public uint LogicRandomSeed
        {
            get => __pbn__LogicRandomSeed.GetValueOrDefault();
            set => __pbn__LogicRandomSeed = value;
        }
        public bool ShouldSerializeLogicRandomSeed() => __pbn__LogicRandomSeed != null;
        public void ResetLogicRandomSeed() => __pbn__LogicRandomSeed = null;
        private uint? __pbn__LogicRandomSeed;

        [global::ProtoBuf.ProtoMember(3, Name = @"stage_id")]
        public uint StageId
        {
            get => __pbn__StageId.GetValueOrDefault();
            set => __pbn__StageId = value;
        }
        public bool ShouldSerializeStageId() => __pbn__StageId != null;
        public void ResetStageId() => __pbn__StageId = null;
        private uint? __pbn__StageId;

        [global::ProtoBuf.ProtoMember(4, Name = @"lineup")]
        public BattleLineup Lineup { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"op_list")]
        public global::System.Collections.Generic.List<BattleOp> OpLists { get; } = new global::System.Collections.Generic.List<BattleOp>();

        [global::ProtoBuf.ProtoMember(6, Name = @"turn_snapshot_hash")]
        public byte[] TurnSnapshotHash
        {
            get => __pbn__TurnSnapshotHash;
            set => __pbn__TurnSnapshotHash = value;
        }
        public bool ShouldSerializeTurnSnapshotHash() => __pbn__TurnSnapshotHash != null;
        public void ResetTurnSnapshotHash() => __pbn__TurnSnapshotHash = null;
        private byte[] __pbn__TurnSnapshotHash;

        [global::ProtoBuf.ProtoMember(7, Name = @"maze_plane_id")]
        public uint MazePlaneId
        {
            get => __pbn__MazePlaneId.GetValueOrDefault();
            set => __pbn__MazePlaneId = value;
        }
        public bool ShouldSerializeMazePlaneId() => __pbn__MazePlaneId != null;
        public void ResetMazePlaneId() => __pbn__MazePlaneId = null;
        private uint? __pbn__MazePlaneId;

        [global::ProtoBuf.ProtoMember(8, Name = @"extra_ability_list", IsPacked = true)]
        public uint[] ExtraAbilityLists { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"is_ai_consider_ultra_skill")]
        public bool IsAiConsiderUltraSkill
        {
            get => __pbn__IsAiConsiderUltraSkill.GetValueOrDefault();
            set => __pbn__IsAiConsiderUltraSkill = value;
        }
        public bool ShouldSerializeIsAiConsiderUltraSkill() => __pbn__IsAiConsiderUltraSkill != null;
        public void ResetIsAiConsiderUltraSkill() => __pbn__IsAiConsiderUltraSkill = null;
        private bool? __pbn__IsAiConsiderUltraSkill;

        [global::ProtoBuf.ProtoMember(10, Name = @"check_strategy")]
        public BattleCheckStrategyType CheckStrategy
        {
            get => __pbn__CheckStrategy.GetValueOrDefault();
            set => __pbn__CheckStrategy = value;
        }
        public bool ShouldSerializeCheckStrategy() => __pbn__CheckStrategy != null;
        public void ResetCheckStrategy() => __pbn__CheckStrategy = null;
        private BattleCheckStrategyType? __pbn__CheckStrategy;

        [global::ProtoBuf.ProtoMember(21, Name = @"turn_snapshot_list")]
        public global::System.Collections.Generic.List<ClientTurnSnapshot> TurnSnapshotLists { get; } = new global::System.Collections.Generic.List<ClientTurnSnapshot>();

        [global::ProtoBuf.ProtoMember(22, Name = @"local_level_path")]
        [global::System.ComponentModel.DefaultValue("")]
        public string LocalLevelPath
        {
            get => __pbn__LocalLevelPath ?? "";
            set => __pbn__LocalLevelPath = value;
        }
        public bool ShouldSerializeLocalLevelPath() => __pbn__LocalLevelPath != null;
        public void ResetLocalLevelPath() => __pbn__LocalLevelPath = null;
        private string __pbn__LocalLevelPath;

        [global::ProtoBuf.ProtoMember(23, Name = @"debug_extra_info")]
        [global::System.ComponentModel.DefaultValue("")]
        public string DebugExtraInfo
        {
            get => __pbn__DebugExtraInfo ?? "";
            set => __pbn__DebugExtraInfo = value;
        }
        public bool ShouldSerializeDebugExtraInfo() => __pbn__DebugExtraInfo != null;
        public void ResetDebugExtraInfo() => __pbn__DebugExtraInfo = null;
        private string __pbn__DebugExtraInfo;

        [global::ProtoBuf.ProtoMember(24, Name = @"config")]
        public GamecoreConfig Config { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AvatarProperty : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"max_hp")]
        public double MaxHp
        {
            get => __pbn__MaxHp.GetValueOrDefault();
            set => __pbn__MaxHp = value;
        }
        public bool ShouldSerializeMaxHp() => __pbn__MaxHp != null;
        public void ResetMaxHp() => __pbn__MaxHp = null;
        private double? __pbn__MaxHp;

        [global::ProtoBuf.ProtoMember(2, Name = @"attack")]
        public double Attack
        {
            get => __pbn__Attack.GetValueOrDefault();
            set => __pbn__Attack = value;
        }
        public bool ShouldSerializeAttack() => __pbn__Attack != null;
        public void ResetAttack() => __pbn__Attack = null;
        private double? __pbn__Attack;

        [global::ProtoBuf.ProtoMember(3, Name = @"defence")]
        public double Defence
        {
            get => __pbn__Defence.GetValueOrDefault();
            set => __pbn__Defence = value;
        }
        public bool ShouldSerializeDefence() => __pbn__Defence != null;
        public void ResetDefence() => __pbn__Defence = null;
        private double? __pbn__Defence;

        [global::ProtoBuf.ProtoMember(4, Name = @"speed")]
        public double Speed
        {
            get => __pbn__Speed.GetValueOrDefault();
            set => __pbn__Speed = value;
        }
        public bool ShouldSerializeSpeed() => __pbn__Speed != null;
        public void ResetSpeed() => __pbn__Speed = null;
        private double? __pbn__Speed;

        [global::ProtoBuf.ProtoMember(5, Name = @"left_hp")]
        public double LeftHp
        {
            get => __pbn__LeftHp.GetValueOrDefault();
            set => __pbn__LeftHp = value;
        }
        public bool ShouldSerializeLeftHp() => __pbn__LeftHp != null;
        public void ResetLeftHp() => __pbn__LeftHp = null;
        private double? __pbn__LeftHp;

        [global::ProtoBuf.ProtoMember(6, Name = @"left_sp")]
        public double LeftSp
        {
            get => __pbn__LeftSp.GetValueOrDefault();
            set => __pbn__LeftSp = value;
        }
        public bool ShouldSerializeLeftSp() => __pbn__LeftSp != null;
        public void ResetLeftSp() => __pbn__LeftSp = null;
        private double? __pbn__LeftSp;

        [global::ProtoBuf.ProtoMember(7, Name = @"max_sp")]
        public double MaxSp
        {
            get => __pbn__MaxSp.GetValueOrDefault();
            set => __pbn__MaxSp = value;
        }
        public bool ShouldSerializeMaxSp() => __pbn__MaxSp != null;
        public void ResetMaxSp() => __pbn__MaxSp = null;
        private double? __pbn__MaxSp;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class EquipmentProperty : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public uint Id
        {
            get => __pbn__Id.GetValueOrDefault();
            set => __pbn__Id = value;
        }
        public bool ShouldSerializeId() => __pbn__Id != null;
        public void ResetId() => __pbn__Id = null;
        private uint? __pbn__Id;

        [global::ProtoBuf.ProtoMember(2, Name = @"rank")]
        public uint Rank
        {
            get => __pbn__Rank.GetValueOrDefault();
            set => __pbn__Rank = value;
        }
        public bool ShouldSerializeRank() => __pbn__Rank != null;
        public void ResetRank() => __pbn__Rank = null;
        private uint? __pbn__Rank;

        [global::ProtoBuf.ProtoMember(3, Name = @"promotion")]
        public uint Promotion
        {
            get => __pbn__Promotion.GetValueOrDefault();
            set => __pbn__Promotion = value;
        }
        public bool ShouldSerializePromotion() => __pbn__Promotion != null;
        public void ResetPromotion() => __pbn__Promotion = null;
        private uint? __pbn__Promotion;

        [global::ProtoBuf.ProtoMember(4, Name = @"level")]
        public uint Level
        {
            get => __pbn__Level.GetValueOrDefault();
            set => __pbn__Level = value;
        }
        public bool ShouldSerializeLevel() => __pbn__Level != null;
        public void ResetLevel() => __pbn__Level = null;
        private uint? __pbn__Level;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AttackDamageProperty : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"attack_type")]
        [global::System.ComponentModel.DefaultValue("")]
        public string AttackType
        {
            get => __pbn__AttackType ?? "";
            set => __pbn__AttackType = value;
        }
        public bool ShouldSerializeAttackType() => __pbn__AttackType != null;
        public void ResetAttackType() => __pbn__AttackType = null;
        private string __pbn__AttackType;

        [global::ProtoBuf.ProtoMember(2, Name = @"damage")]
        public double Damage
        {
            get => __pbn__Damage.GetValueOrDefault();
            set => __pbn__Damage = value;
        }
        public bool ShouldSerializeDamage() => __pbn__Damage != null;
        public void ResetDamage() => __pbn__Damage = null;
        private double? __pbn__Damage;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SkillUseProperty : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"skill_id")]
        public uint SkillId
        {
            get => __pbn__SkillId.GetValueOrDefault();
            set => __pbn__SkillId = value;
        }
        public bool ShouldSerializeSkillId() => __pbn__SkillId != null;
        public void ResetSkillId() => __pbn__SkillId = null;
        private uint? __pbn__SkillId;

        [global::ProtoBuf.ProtoMember(2, Name = @"skill_type")]
        [global::System.ComponentModel.DefaultValue("")]
        public string SkillType
        {
            get => __pbn__SkillType ?? "";
            set => __pbn__SkillType = value;
        }
        public bool ShouldSerializeSkillType() => __pbn__SkillType != null;
        public void ResetSkillType() => __pbn__SkillType = null;
        private string __pbn__SkillType;

        [global::ProtoBuf.ProtoMember(3, Name = @"skill_level")]
        public uint SkillLevel
        {
            get => __pbn__SkillLevel.GetValueOrDefault();
            set => __pbn__SkillLevel = value;
        }
        public bool ShouldSerializeSkillLevel() => __pbn__SkillLevel != null;
        public void ResetSkillLevel() => __pbn__SkillLevel = null;
        private uint? __pbn__SkillLevel;

        [global::ProtoBuf.ProtoMember(4, Name = @"skill_use_count")]
        public uint SkillUseCount
        {
            get => __pbn__SkillUseCount.GetValueOrDefault();
            set => __pbn__SkillUseCount = value;
        }
        public bool ShouldSerializeSkillUseCount() => __pbn__SkillUseCount != null;
        public void ResetSkillUseCount() => __pbn__SkillUseCount = null;
        private uint? __pbn__SkillUseCount;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SpAddSource : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"source")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Source
        {
            get => __pbn__Source ?? "";
            set => __pbn__Source = value;
        }
        public bool ShouldSerializeSource() => __pbn__Source != null;
        public void ResetSource() => __pbn__Source = null;
        private string __pbn__Source;

        [global::ProtoBuf.ProtoMember(2, Name = @"sp_add")]
        public uint SpAdd
        {
            get => __pbn__SpAdd.GetValueOrDefault();
            set => __pbn__SpAdd = value;
        }
        public bool ShouldSerializeSpAdd() => __pbn__SpAdd != null;
        public void ResetSpAdd() => __pbn__SpAdd = null;
        private uint? __pbn__SpAdd;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AvatarBattleInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"avatar_type")]
        public AvatarType AvatarType
        {
            get => __pbn__AvatarType.GetValueOrDefault();
            set => __pbn__AvatarType = value;
        }
        public bool ShouldSerializeAvatarType() => __pbn__AvatarType != null;
        public void ResetAvatarType() => __pbn__AvatarType = null;
        private AvatarType? __pbn__AvatarType;

        [global::ProtoBuf.ProtoMember(2, Name = @"id")]
        public uint Id
        {
            get => __pbn__Id.GetValueOrDefault();
            set => __pbn__Id = value;
        }
        public bool ShouldSerializeId() => __pbn__Id != null;
        public void ResetId() => __pbn__Id = null;
        private uint? __pbn__Id;

        [global::ProtoBuf.ProtoMember(3, Name = @"avatar_level")]
        public uint AvatarLevel
        {
            get => __pbn__AvatarLevel.GetValueOrDefault();
            set => __pbn__AvatarLevel = value;
        }
        public bool ShouldSerializeAvatarLevel() => __pbn__AvatarLevel != null;
        public void ResetAvatarLevel() => __pbn__AvatarLevel = null;
        private uint? __pbn__AvatarLevel;

        [global::ProtoBuf.ProtoMember(4, Name = @"avatar_rank")]
        public uint AvatarRank
        {
            get => __pbn__AvatarRank.GetValueOrDefault();
            set => __pbn__AvatarRank = value;
        }
        public bool ShouldSerializeAvatarRank() => __pbn__AvatarRank != null;
        public void ResetAvatarRank() => __pbn__AvatarRank = null;
        private uint? __pbn__AvatarRank;

        [global::ProtoBuf.ProtoMember(5, Name = @"avatar_promotion")]
        public uint AvatarPromotion
        {
            get => __pbn__AvatarPromotion.GetValueOrDefault();
            set => __pbn__AvatarPromotion = value;
        }
        public bool ShouldSerializeAvatarPromotion() => __pbn__AvatarPromotion != null;
        public void ResetAvatarPromotion() => __pbn__AvatarPromotion = null;
        private uint? __pbn__AvatarPromotion;

        [global::ProtoBuf.ProtoMember(6, Name = @"avatar_status")]
        public AvatarProperty AvatarStatus { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"avatar_skill")]
        [global::System.ComponentModel.DefaultValue("")]
        public string AvatarSkill
        {
            get => __pbn__AvatarSkill ?? "";
            set => __pbn__AvatarSkill = value;
        }
        public bool ShouldSerializeAvatarSkill() => __pbn__AvatarSkill != null;
        public void ResetAvatarSkill() => __pbn__AvatarSkill = null;
        private string __pbn__AvatarSkill;

        [global::ProtoBuf.ProtoMember(8, Name = @"avatar_equipment")]
        public global::System.Collections.Generic.List<EquipmentProperty> AvatarEquipments { get; } = new global::System.Collections.Generic.List<EquipmentProperty>();

        [global::ProtoBuf.ProtoMember(9, Name = @"total_turns")]
        public uint TotalTurns
        {
            get => __pbn__TotalTurns.GetValueOrDefault();
            set => __pbn__TotalTurns = value;
        }
        public bool ShouldSerializeTotalTurns() => __pbn__TotalTurns != null;
        public void ResetTotalTurns() => __pbn__TotalTurns = null;
        private uint? __pbn__TotalTurns;

        [global::ProtoBuf.ProtoMember(10, Name = @"total_damage")]
        public double TotalDamage
        {
            get => __pbn__TotalDamage.GetValueOrDefault();
            set => __pbn__TotalDamage = value;
        }
        public bool ShouldSerializeTotalDamage() => __pbn__TotalDamage != null;
        public void ResetTotalDamage() => __pbn__TotalDamage = null;
        private double? __pbn__TotalDamage;

        [global::ProtoBuf.ProtoMember(11, Name = @"total_heal")]
        public double TotalHeal
        {
            get => __pbn__TotalHeal.GetValueOrDefault();
            set => __pbn__TotalHeal = value;
        }
        public bool ShouldSerializeTotalHeal() => __pbn__TotalHeal != null;
        public void ResetTotalHeal() => __pbn__TotalHeal = null;
        private double? __pbn__TotalHeal;

        [global::ProtoBuf.ProtoMember(12, Name = @"total_damage_taken")]
        public double TotalDamageTaken
        {
            get => __pbn__TotalDamageTaken.GetValueOrDefault();
            set => __pbn__TotalDamageTaken = value;
        }
        public bool ShouldSerializeTotalDamageTaken() => __pbn__TotalDamageTaken != null;
        public void ResetTotalDamageTaken() => __pbn__TotalDamageTaken = null;
        private double? __pbn__TotalDamageTaken;

        [global::ProtoBuf.ProtoMember(13, Name = @"total_hp_recover")]
        public double TotalHpRecover
        {
            get => __pbn__TotalHpRecover.GetValueOrDefault();
            set => __pbn__TotalHpRecover = value;
        }
        public bool ShouldSerializeTotalHpRecover() => __pbn__TotalHpRecover != null;
        public void ResetTotalHpRecover() => __pbn__TotalHpRecover = null;
        private double? __pbn__TotalHpRecover;

        [global::ProtoBuf.ProtoMember(14, Name = @"total_sp_cost")]
        public double TotalSpCost
        {
            get => __pbn__TotalSpCost.GetValueOrDefault();
            set => __pbn__TotalSpCost = value;
        }
        public bool ShouldSerializeTotalSpCost() => __pbn__TotalSpCost != null;
        public void ResetTotalSpCost() => __pbn__TotalSpCost = null;
        private double? __pbn__TotalSpCost;

        [global::ProtoBuf.ProtoMember(15, Name = @"stage_id")]
        public uint StageId
        {
            get => __pbn__StageId.GetValueOrDefault();
            set => __pbn__StageId = value;
        }
        public bool ShouldSerializeStageId() => __pbn__StageId != null;
        public void ResetStageId() => __pbn__StageId = null;
        private uint? __pbn__StageId;

        [global::ProtoBuf.ProtoMember(16, Name = @"stage_type")]
        public uint StageType
        {
            get => __pbn__StageType.GetValueOrDefault();
            set => __pbn__StageType = value;
        }
        public bool ShouldSerializeStageType() => __pbn__StageType != null;
        public void ResetStageType() => __pbn__StageType = null;
        private uint? __pbn__StageType;

        [global::ProtoBuf.ProtoMember(17, Name = @"total_break_damage")]
        public double TotalBreakDamage
        {
            get => __pbn__TotalBreakDamage.GetValueOrDefault();
            set => __pbn__TotalBreakDamage = value;
        }
        public bool ShouldSerializeTotalBreakDamage() => __pbn__TotalBreakDamage != null;
        public void ResetTotalBreakDamage() => __pbn__TotalBreakDamage = null;
        private double? __pbn__TotalBreakDamage;

        [global::ProtoBuf.ProtoMember(18, Name = @"attack_type_damage")]
        public global::System.Collections.Generic.List<AttackDamageProperty> AttackTypeDamages { get; } = new global::System.Collections.Generic.List<AttackDamageProperty>();

        [global::ProtoBuf.ProtoMember(19, Name = @"attack_type_break_damage")]
        public global::System.Collections.Generic.List<AttackDamageProperty> AttackTypeBreakDamages { get; } = new global::System.Collections.Generic.List<AttackDamageProperty>();

        [global::ProtoBuf.ProtoMember(20, Name = @"attack_type_max_damage")]
        public global::System.Collections.Generic.List<AttackDamageProperty> AttackTypeMaxDamages { get; } = new global::System.Collections.Generic.List<AttackDamageProperty>();

        [global::ProtoBuf.ProtoMember(21, Name = @"skill_times")]
        public global::System.Collections.Generic.List<SkillUseProperty> SkillTimes { get; } = new global::System.Collections.Generic.List<SkillUseProperty>();

        [global::ProtoBuf.ProtoMember(22, Name = @"delay_cumulate")]
        public double DelayCumulate
        {
            get => __pbn__DelayCumulate.GetValueOrDefault();
            set => __pbn__DelayCumulate = value;
        }
        public bool ShouldSerializeDelayCumulate() => __pbn__DelayCumulate != null;
        public void ResetDelayCumulate() => __pbn__DelayCumulate = null;
        private double? __pbn__DelayCumulate;

        [global::ProtoBuf.ProtoMember(23, Name = @"total_sp_add")]
        public uint TotalSpAdd
        {
            get => __pbn__TotalSpAdd.GetValueOrDefault();
            set => __pbn__TotalSpAdd = value;
        }
        public bool ShouldSerializeTotalSpAdd() => __pbn__TotalSpAdd != null;
        public void ResetTotalSpAdd() => __pbn__TotalSpAdd = null;
        private uint? __pbn__TotalSpAdd;

        [global::ProtoBuf.ProtoMember(24, Name = @"sp_add_source")]
        public global::System.Collections.Generic.List<SpAddSource> SpAddSources { get; } = new global::System.Collections.Generic.List<SpAddSource>();

        [global::ProtoBuf.ProtoMember(25, Name = @"total_bp_cost")]
        public uint TotalBpCost
        {
            get => __pbn__TotalBpCost.GetValueOrDefault();
            set => __pbn__TotalBpCost = value;
        }
        public bool ShouldSerializeTotalBpCost() => __pbn__TotalBpCost != null;
        public void ResetTotalBpCost() => __pbn__TotalBpCost = null;
        private uint? __pbn__TotalBpCost;

        [global::ProtoBuf.ProtoMember(26, Name = @"die_times")]
        public uint DieTimes
        {
            get => __pbn__DieTimes.GetValueOrDefault();
            set => __pbn__DieTimes = value;
        }
        public bool ShouldSerializeDieTimes() => __pbn__DieTimes != null;
        public void ResetDieTimes() => __pbn__DieTimes = null;
        private uint? __pbn__DieTimes;

        [global::ProtoBuf.ProtoMember(27, Name = @"revive_times")]
        public uint ReviveTimes
        {
            get => __pbn__ReviveTimes.GetValueOrDefault();
            set => __pbn__ReviveTimes = value;
        }
        public bool ShouldSerializeReviveTimes() => __pbn__ReviveTimes != null;
        public void ResetReviveTimes() => __pbn__ReviveTimes = null;
        private uint? __pbn__ReviveTimes;

        [global::ProtoBuf.ProtoMember(28, Name = @"break_times")]
        public uint BreakTimes
        {
            get => __pbn__BreakTimes.GetValueOrDefault();
            set => __pbn__BreakTimes = value;
        }
        public bool ShouldSerializeBreakTimes() => __pbn__BreakTimes != null;
        public void ResetBreakTimes() => __pbn__BreakTimes = null;
        private uint? __pbn__BreakTimes;

        [global::ProtoBuf.ProtoMember(29, Name = @"extra_turns")]
        public uint ExtraTurns
        {
            get => __pbn__ExtraTurns.GetValueOrDefault();
            set => __pbn__ExtraTurns = value;
        }
        public bool ShouldSerializeExtraTurns() => __pbn__ExtraTurns != null;
        public void ResetExtraTurns() => __pbn__ExtraTurns = null;
        private uint? __pbn__ExtraTurns;

        [global::ProtoBuf.ProtoMember(30, Name = @"total_shield")]
        public double TotalShield
        {
            get => __pbn__TotalShield.GetValueOrDefault();
            set => __pbn__TotalShield = value;
        }
        public bool ShouldSerializeTotalShield() => __pbn__TotalShield != null;
        public void ResetTotalShield() => __pbn__TotalShield = null;
        private double? __pbn__TotalShield;

        [global::ProtoBuf.ProtoMember(31, Name = @"total_shield_taken")]
        public double TotalShieldTaken
        {
            get => __pbn__TotalShieldTaken.GetValueOrDefault();
            set => __pbn__TotalShieldTaken = value;
        }
        public bool ShouldSerializeTotalShieldTaken() => __pbn__TotalShieldTaken != null;
        public void ResetTotalShieldTaken() => __pbn__TotalShieldTaken = null;
        private double? __pbn__TotalShieldTaken;

        [global::ProtoBuf.ProtoMember(32, Name = @"total_shield_damage")]
        public double TotalShieldDamage
        {
            get => __pbn__TotalShieldDamage.GetValueOrDefault();
            set => __pbn__TotalShieldDamage = value;
        }
        public bool ShouldSerializeTotalShieldDamage() => __pbn__TotalShieldDamage != null;
        public void ResetTotalShieldDamage() => __pbn__TotalShieldDamage = null;
        private double? __pbn__TotalShieldDamage;

        [global::ProtoBuf.ProtoMember(33, Name = @"initial_status")]
        public AvatarProperty InitialStatus { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MonsterProperty : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"max_hp")]
        public double MaxHp
        {
            get => __pbn__MaxHp.GetValueOrDefault();
            set => __pbn__MaxHp = value;
        }
        public bool ShouldSerializeMaxHp() => __pbn__MaxHp != null;
        public void ResetMaxHp() => __pbn__MaxHp = null;
        private double? __pbn__MaxHp;

        [global::ProtoBuf.ProtoMember(2, Name = @"attack")]
        public double Attack
        {
            get => __pbn__Attack.GetValueOrDefault();
            set => __pbn__Attack = value;
        }
        public bool ShouldSerializeAttack() => __pbn__Attack != null;
        public void ResetAttack() => __pbn__Attack = null;
        private double? __pbn__Attack;

        [global::ProtoBuf.ProtoMember(3, Name = @"defence")]
        public double Defence
        {
            get => __pbn__Defence.GetValueOrDefault();
            set => __pbn__Defence = value;
        }
        public bool ShouldSerializeDefence() => __pbn__Defence != null;
        public void ResetDefence() => __pbn__Defence = null;
        private double? __pbn__Defence;

        [global::ProtoBuf.ProtoMember(4, Name = @"shield")]
        public double Shield
        {
            get => __pbn__Shield.GetValueOrDefault();
            set => __pbn__Shield = value;
        }
        public bool ShouldSerializeShield() => __pbn__Shield != null;
        public void ResetShield() => __pbn__Shield = null;
        private double? __pbn__Shield;

        [global::ProtoBuf.ProtoMember(5, Name = @"speed")]
        public double Speed
        {
            get => __pbn__Speed.GetValueOrDefault();
            set => __pbn__Speed = value;
        }
        public bool ShouldSerializeSpeed() => __pbn__Speed != null;
        public void ResetSpeed() => __pbn__Speed = null;
        private double? __pbn__Speed;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MonsterBattleInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"entity_id")]
        public uint EntityId
        {
            get => __pbn__EntityId.GetValueOrDefault();
            set => __pbn__EntityId = value;
        }
        public bool ShouldSerializeEntityId() => __pbn__EntityId != null;
        public void ResetEntityId() => __pbn__EntityId = null;
        private uint? __pbn__EntityId;

        [global::ProtoBuf.ProtoMember(2, Name = @"monster_id")]
        public uint MonsterId
        {
            get => __pbn__MonsterId.GetValueOrDefault();
            set => __pbn__MonsterId = value;
        }
        public bool ShouldSerializeMonsterId() => __pbn__MonsterId != null;
        public void ResetMonsterId() => __pbn__MonsterId = null;
        private uint? __pbn__MonsterId;

        [global::ProtoBuf.ProtoMember(3, Name = @"monster_template_id")]
        public uint MonsterTemplateId
        {
            get => __pbn__MonsterTemplateId.GetValueOrDefault();
            set => __pbn__MonsterTemplateId = value;
        }
        public bool ShouldSerializeMonsterTemplateId() => __pbn__MonsterTemplateId != null;
        public void ResetMonsterTemplateId() => __pbn__MonsterTemplateId = null;
        private uint? __pbn__MonsterTemplateId;

        [global::ProtoBuf.ProtoMember(4, Name = @"monster_level")]
        public uint MonsterLevel
        {
            get => __pbn__MonsterLevel.GetValueOrDefault();
            set => __pbn__MonsterLevel = value;
        }
        public bool ShouldSerializeMonsterLevel() => __pbn__MonsterLevel != null;
        public void ResetMonsterLevel() => __pbn__MonsterLevel = null;
        private uint? __pbn__MonsterLevel;

        [global::ProtoBuf.ProtoMember(5, Name = @"monster_status")]
        public MonsterProperty MonsterStatus { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"total_turns")]
        public uint TotalTurns
        {
            get => __pbn__TotalTurns.GetValueOrDefault();
            set => __pbn__TotalTurns = value;
        }
        public bool ShouldSerializeTotalTurns() => __pbn__TotalTurns != null;
        public void ResetTotalTurns() => __pbn__TotalTurns = null;
        private uint? __pbn__TotalTurns;

        [global::ProtoBuf.ProtoMember(7, Name = @"total_damage")]
        public double TotalDamage
        {
            get => __pbn__TotalDamage.GetValueOrDefault();
            set => __pbn__TotalDamage = value;
        }
        public bool ShouldSerializeTotalDamage() => __pbn__TotalDamage != null;
        public void ResetTotalDamage() => __pbn__TotalDamage = null;
        private double? __pbn__TotalDamage;

        [global::ProtoBuf.ProtoMember(8, Name = @"total_heal")]
        public double TotalHeal
        {
            get => __pbn__TotalHeal.GetValueOrDefault();
            set => __pbn__TotalHeal = value;
        }
        public bool ShouldSerializeTotalHeal() => __pbn__TotalHeal != null;
        public void ResetTotalHeal() => __pbn__TotalHeal = null;
        private double? __pbn__TotalHeal;

        [global::ProtoBuf.ProtoMember(9, Name = @"total_damage_taken")]
        public double TotalDamageTaken
        {
            get => __pbn__TotalDamageTaken.GetValueOrDefault();
            set => __pbn__TotalDamageTaken = value;
        }
        public bool ShouldSerializeTotalDamageTaken() => __pbn__TotalDamageTaken != null;
        public void ResetTotalDamageTaken() => __pbn__TotalDamageTaken = null;
        private double? __pbn__TotalDamageTaken;

        [global::ProtoBuf.ProtoMember(10, Name = @"total_stance_damage_taken")]
        public double TotalStanceDamageTaken
        {
            get => __pbn__TotalStanceDamageTaken.GetValueOrDefault();
            set => __pbn__TotalStanceDamageTaken = value;
        }
        public bool ShouldSerializeTotalStanceDamageTaken() => __pbn__TotalStanceDamageTaken != null;
        public void ResetTotalStanceDamageTaken() => __pbn__TotalStanceDamageTaken = null;
        private double? __pbn__TotalStanceDamageTaken;

        [global::ProtoBuf.ProtoMember(11, Name = @"total_hp_recover")]
        public double TotalHpRecover
        {
            get => __pbn__TotalHpRecover.GetValueOrDefault();
            set => __pbn__TotalHpRecover = value;
        }
        public bool ShouldSerializeTotalHpRecover() => __pbn__TotalHpRecover != null;
        public void ResetTotalHpRecover() => __pbn__TotalHpRecover = null;
        private double? __pbn__TotalHpRecover;

        [global::ProtoBuf.ProtoMember(12, Name = @"stage_id")]
        public uint StageId
        {
            get => __pbn__StageId.GetValueOrDefault();
            set => __pbn__StageId = value;
        }
        public bool ShouldSerializeStageId() => __pbn__StageId != null;
        public void ResetStageId() => __pbn__StageId = null;
        private uint? __pbn__StageId;

        [global::ProtoBuf.ProtoMember(13, Name = @"battle_id")]
        public uint BattleId
        {
            get => __pbn__BattleId.GetValueOrDefault();
            set => __pbn__BattleId = value;
        }
        public bool ShouldSerializeBattleId() => __pbn__BattleId != null;
        public void ResetBattleId() => __pbn__BattleId = null;
        private uint? __pbn__BattleId;

        [global::ProtoBuf.ProtoMember(14, Name = @"monster_type")]
        public uint MonsterType
        {
            get => __pbn__MonsterType.GetValueOrDefault();
            set => __pbn__MonsterType = value;
        }
        public bool ShouldSerializeMonsterType() => __pbn__MonsterType != null;
        public void ResetMonsterType() => __pbn__MonsterType = null;
        private uint? __pbn__MonsterType;

        [global::ProtoBuf.ProtoMember(15, Name = @"attack_type_damage")]
        public global::System.Collections.Generic.List<AttackDamageProperty> AttackTypeDamages { get; } = new global::System.Collections.Generic.List<AttackDamageProperty>();

        [global::ProtoBuf.ProtoMember(16, Name = @"skill_times")]
        public global::System.Collections.Generic.List<SkillUseProperty> SkillTimes { get; } = new global::System.Collections.Generic.List<SkillUseProperty>();

        [global::ProtoBuf.ProtoMember(17, Name = @"stage_type")]
        public uint StageType
        {
            get => __pbn__StageType.GetValueOrDefault();
            set => __pbn__StageType = value;
        }
        public bool ShouldSerializeStageType() => __pbn__StageType != null;
        public void ResetStageType() => __pbn__StageType = null;
        private uint? __pbn__StageType;

        [global::ProtoBuf.ProtoMember(18, Name = @"total_break_damage_taken")]
        public double TotalBreakDamageTaken
        {
            get => __pbn__TotalBreakDamageTaken.GetValueOrDefault();
            set => __pbn__TotalBreakDamageTaken = value;
        }
        public bool ShouldSerializeTotalBreakDamageTaken() => __pbn__TotalBreakDamageTaken != null;
        public void ResetTotalBreakDamageTaken() => __pbn__TotalBreakDamageTaken = null;
        private double? __pbn__TotalBreakDamageTaken;

        [global::ProtoBuf.ProtoMember(19, Name = @"delay_cumulate")]
        public double DelayCumulate
        {
            get => __pbn__DelayCumulate.GetValueOrDefault();
            set => __pbn__DelayCumulate = value;
        }
        public bool ShouldSerializeDelayCumulate() => __pbn__DelayCumulate != null;
        public void ResetDelayCumulate() => __pbn__DelayCumulate = null;
        private double? __pbn__DelayCumulate;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BattleStatistics : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"total_battle_turns")]
        public uint TotalBattleTurns
        {
            get => __pbn__TotalBattleTurns.GetValueOrDefault();
            set => __pbn__TotalBattleTurns = value;
        }
        public bool ShouldSerializeTotalBattleTurns() => __pbn__TotalBattleTurns != null;
        public void ResetTotalBattleTurns() => __pbn__TotalBattleTurns = null;
        private uint? __pbn__TotalBattleTurns;

        [global::ProtoBuf.ProtoMember(2, Name = @"total_auto_turns")]
        public uint TotalAutoTurns
        {
            get => __pbn__TotalAutoTurns.GetValueOrDefault();
            set => __pbn__TotalAutoTurns = value;
        }
        public bool ShouldSerializeTotalAutoTurns() => __pbn__TotalAutoTurns != null;
        public void ResetTotalAutoTurns() => __pbn__TotalAutoTurns = null;
        private uint? __pbn__TotalAutoTurns;

        [global::ProtoBuf.ProtoMember(3, Name = @"avatar_id_list", IsPacked = true)]
        public uint[] AvatarIdLists { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"ultra_cnt")]
        public uint UltraCnt
        {
            get => __pbn__UltraCnt.GetValueOrDefault();
            set => __pbn__UltraCnt = value;
        }
        public bool ShouldSerializeUltraCnt() => __pbn__UltraCnt != null;
        public void ResetUltraCnt() => __pbn__UltraCnt = null;
        private uint? __pbn__UltraCnt;

        [global::ProtoBuf.ProtoMember(5, Name = @"total_delay_cumulate")]
        public double TotalDelayCumulate
        {
            get => __pbn__TotalDelayCumulate.GetValueOrDefault();
            set => __pbn__TotalDelayCumulate = value;
        }
        public bool ShouldSerializeTotalDelayCumulate() => __pbn__TotalDelayCumulate != null;
        public void ResetTotalDelayCumulate() => __pbn__TotalDelayCumulate = null;
        private double? __pbn__TotalDelayCumulate;

        [global::ProtoBuf.ProtoMember(6, Name = @"cost_time")]
        public double CostTime
        {
            get => __pbn__CostTime.GetValueOrDefault();
            set => __pbn__CostTime = value;
        }
        public bool ShouldSerializeCostTime() => __pbn__CostTime != null;
        public void ResetCostTime() => __pbn__CostTime = null;
        private double? __pbn__CostTime;

        [global::ProtoBuf.ProtoMember(7, Name = @"avatar_battle_list")]
        public global::System.Collections.Generic.List<AvatarBattleInfo> AvatarBattleLists { get; } = new global::System.Collections.Generic.List<AvatarBattleInfo>();

        [global::ProtoBuf.ProtoMember(8, Name = @"monster_battle_list")]
        public global::System.Collections.Generic.List<MonsterBattleInfo> MonsterBattleLists { get; } = new global::System.Collections.Generic.List<MonsterBattleInfo>();

        [global::ProtoBuf.ProtoMember(9, Name = @"round_cnt")]
        public uint RoundCnt
        {
            get => __pbn__RoundCnt.GetValueOrDefault();
            set => __pbn__RoundCnt = value;
        }
        public bool ShouldSerializeRoundCnt() => __pbn__RoundCnt != null;
        public void ResetRoundCnt() => __pbn__RoundCnt = null;
        private uint? __pbn__RoundCnt;

        [global::ProtoBuf.ProtoMember(10, Name = @"cocoon_dead_wave")]
        public uint CocoonDeadWave
        {
            get => __pbn__CocoonDeadWave.GetValueOrDefault();
            set => __pbn__CocoonDeadWave = value;
        }
        public bool ShouldSerializeCocoonDeadWave() => __pbn__CocoonDeadWave != null;
        public void ResetCocoonDeadWave() => __pbn__CocoonDeadWave = null;
        private uint? __pbn__CocoonDeadWave;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BattleResult : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"retcode")]
        public BattleCheckResultType Retcode
        {
            get => __pbn__Retcode.GetValueOrDefault();
            set => __pbn__Retcode = value;
        }
        public bool ShouldSerializeRetcode() => __pbn__Retcode != null;
        public void ResetRetcode() => __pbn__Retcode = null;
        private BattleCheckResultType? __pbn__Retcode;

        [global::ProtoBuf.ProtoMember(2, Name = @"end_status")]
        public BattleEndStatus EndStatus
        {
            get => __pbn__EndStatus.GetValueOrDefault();
            set => __pbn__EndStatus = value;
        }
        public bool ShouldSerializeEndStatus() => __pbn__EndStatus != null;
        public void ResetEndStatus() => __pbn__EndStatus = null;
        private BattleEndStatus? __pbn__EndStatus;

        [global::ProtoBuf.ProtoMember(3, Name = @"stt")]
        public BattleStatistics Stt { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CharacterSnapshot : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"runtime_id")]
        public uint RuntimeId
        {
            get => __pbn__RuntimeId.GetValueOrDefault();
            set => __pbn__RuntimeId = value;
        }
        public bool ShouldSerializeRuntimeId() => __pbn__RuntimeId != null;
        public void ResetRuntimeId() => __pbn__RuntimeId = null;
        private uint? __pbn__RuntimeId;

        [global::ProtoBuf.ProtoMember(2, Name = @"properties", IsPacked = true)]
        public ulong[] Properties { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AnimEventSnapshot : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"event_name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string EventName
        {
            get => __pbn__EventName ?? "";
            set => __pbn__EventName = value;
        }
        public bool ShouldSerializeEventName() => __pbn__EventName != null;
        public void ResetEventName() => __pbn__EventName = null;
        private string __pbn__EventName;

        [global::ProtoBuf.ProtoMember(2, Name = @"count")]
        public uint Count
        {
            get => __pbn__Count.GetValueOrDefault();
            set => __pbn__Count = value;
        }
        public bool ShouldSerializeCount() => __pbn__Count != null;
        public void ResetCount() => __pbn__Count = null;
        private uint? __pbn__Count;

    }

    [global::ProtoBuf.ProtoContract()]
    public enum BattleCheckStrategyType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"BATTLE_CHECK_STRATEGY_IDENTICAL")]
        BattleCheckStrategyIdentical = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"BATTLE_CHECK_STRATEGY_SERVER")]
        BattleCheckStrategyServer = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"BATTLE_CHECK_STRATEGY_CLIENT")]
        BattleCheckStrategyClient = 2,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum BattleCheckResultType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"BATTLE_CHECK_RESULT_SUCC")]
        BattleCheckResultSucc = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"BATTLE_CHECK_RESULT_FAIL")]
        BattleCheckResultFail = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"BATTLE_CHECK_RESULT_PASS")]
        BattleCheckResultPass = 2,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum BattleEndStatus
    {
        [global::ProtoBuf.ProtoEnum(Name = @"BATTLE_END_NONE")]
        BattleEndNone = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"BATTLE_END_WIN")]
        BattleEndWin = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"BATTLE_END_LOSE")]
        BattleEndLose = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"BATTLE_END_QUIT")]
        BattleEndQuit = 3,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
