// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: cs.avatar.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace KazusaHSR.Protocol
{

    [global::ProtoBuf.ProtoContract()]
    public partial class GetAvatarDataCsReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"is_get_all")]
        public bool IsGetAll
        {
            get => __pbn__IsGetAll.GetValueOrDefault();
            set => __pbn__IsGetAll = value;
        }
        public bool ShouldSerializeIsGetAll() => __pbn__IsGetAll != null;
        public void ResetIsGetAll() => __pbn__IsGetAll = null;
        private bool? __pbn__IsGetAll;

        [global::ProtoBuf.ProtoMember(2, Name = @"avatar_id_list", IsPacked = true)]
        public uint[] AvatarIdLists { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Avatar : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"avatar_id")]
        public uint AvatarId
        {
            get => __pbn__AvatarId.GetValueOrDefault();
            set => __pbn__AvatarId = value;
        }
        public bool ShouldSerializeAvatarId() => __pbn__AvatarId != null;
        public void ResetAvatarId() => __pbn__AvatarId = null;
        private uint? __pbn__AvatarId;

        [global::ProtoBuf.ProtoMember(2, Name = @"exp")]
        public uint Exp
        {
            get => __pbn__Exp.GetValueOrDefault();
            set => __pbn__Exp = value;
        }
        public bool ShouldSerializeExp() => __pbn__Exp != null;
        public void ResetExp() => __pbn__Exp = null;
        private uint? __pbn__Exp;

        [global::ProtoBuf.ProtoMember(3, Name = @"level")]
        public uint Level
        {
            get => __pbn__Level.GetValueOrDefault();
            set => __pbn__Level = value;
        }
        public bool ShouldSerializeLevel() => __pbn__Level != null;
        public void ResetLevel() => __pbn__Level = null;
        private uint? __pbn__Level;

        [global::ProtoBuf.ProtoMember(4, Name = @"promotion")]
        public uint Promotion
        {
            get => __pbn__Promotion.GetValueOrDefault();
            set => __pbn__Promotion = value;
        }
        public bool ShouldSerializePromotion() => __pbn__Promotion != null;
        public void ResetPromotion() => __pbn__Promotion = null;
        private uint? __pbn__Promotion;

        [global::ProtoBuf.ProtoMember(5, Name = @"rank")]
        public uint Rank
        {
            get => __pbn__Rank.GetValueOrDefault();
            set => __pbn__Rank = value;
        }
        public bool ShouldSerializeRank() => __pbn__Rank != null;
        public void ResetRank() => __pbn__Rank = null;
        private uint? __pbn__Rank;

        [global::ProtoBuf.ProtoMember(6, Name = @"skilltree_list")]
        public global::System.Collections.Generic.List<AvatarSkillTree> SkilltreeLists { get; } = new global::System.Collections.Generic.List<AvatarSkillTree>();

        [global::ProtoBuf.ProtoMember(7, Name = @"equipment_unique_id")]
        public uint EquipmentUniqueId
        {
            get => __pbn__EquipmentUniqueId.GetValueOrDefault();
            set => __pbn__EquipmentUniqueId = value;
        }
        public bool ShouldSerializeEquipmentUniqueId() => __pbn__EquipmentUniqueId != null;
        public void ResetEquipmentUniqueId() => __pbn__EquipmentUniqueId = null;
        private uint? __pbn__EquipmentUniqueId;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetAvatarDataScRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"retcode")]
        public uint Retcode
        {
            get => __pbn__Retcode.GetValueOrDefault();
            set => __pbn__Retcode = value;
        }
        public bool ShouldSerializeRetcode() => __pbn__Retcode != null;
        public void ResetRetcode() => __pbn__Retcode = null;
        private uint? __pbn__Retcode;

        [global::ProtoBuf.ProtoMember(2, Name = @"avatar_list")]
        public global::System.Collections.Generic.List<Avatar> AvatarLists { get; } = new global::System.Collections.Generic.List<Avatar>();

        [global::ProtoBuf.ProtoMember(3, Name = @"is_all")]
        public bool IsAll
        {
            get => __pbn__IsAll.GetValueOrDefault();
            set => __pbn__IsAll = value;
        }
        public bool ShouldSerializeIsAll() => __pbn__IsAll != null;
        public void ResetIsAll() => __pbn__IsAll = null;
        private bool? __pbn__IsAll;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AvatarExpUpCsReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"avatar_id")]
        public uint AvatarId
        {
            get => __pbn__AvatarId.GetValueOrDefault();
            set => __pbn__AvatarId = value;
        }
        public bool ShouldSerializeAvatarId() => __pbn__AvatarId != null;
        public void ResetAvatarId() => __pbn__AvatarId = null;
        private uint? __pbn__AvatarId;

        [global::ProtoBuf.ProtoMember(2, Name = @"item_cost")]
        public ItemCostData ItemCost { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AvatarExpUpScRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"retcode")]
        public uint Retcode
        {
            get => __pbn__Retcode.GetValueOrDefault();
            set => __pbn__Retcode = value;
        }
        public bool ShouldSerializeRetcode() => __pbn__Retcode != null;
        public void ResetRetcode() => __pbn__Retcode = null;
        private uint? __pbn__Retcode;

        [global::ProtoBuf.ProtoMember(2, Name = @"return_item_list")]
        public global::System.Collections.Generic.List<PileItem> ReturnItemLists { get; } = new global::System.Collections.Generic.List<PileItem>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UnlockSkilltreeCsReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"point_id")]
        public uint PointId
        {
            get => __pbn__PointId.GetValueOrDefault();
            set => __pbn__PointId = value;
        }
        public bool ShouldSerializePointId() => __pbn__PointId != null;
        public void ResetPointId() => __pbn__PointId = null;
        private uint? __pbn__PointId;

        [global::ProtoBuf.ProtoMember(2, Name = @"level")]
        public uint Level
        {
            get => __pbn__Level.GetValueOrDefault();
            set => __pbn__Level = value;
        }
        public bool ShouldSerializeLevel() => __pbn__Level != null;
        public void ResetLevel() => __pbn__Level = null;
        private uint? __pbn__Level;

        [global::ProtoBuf.ProtoMember(3, Name = @"item_list")]
        public global::System.Collections.Generic.List<ItemCost> ItemLists { get; } = new global::System.Collections.Generic.List<ItemCost>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UnlockSkilltreeScRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"retcode")]
        public uint Retcode
        {
            get => __pbn__Retcode.GetValueOrDefault();
            set => __pbn__Retcode = value;
        }
        public bool ShouldSerializeRetcode() => __pbn__Retcode != null;
        public void ResetRetcode() => __pbn__Retcode = null;
        private uint? __pbn__Retcode;

        [global::ProtoBuf.ProtoMember(2, Name = @"avatar_id")]
        public uint AvatarId
        {
            get => __pbn__AvatarId.GetValueOrDefault();
            set => __pbn__AvatarId = value;
        }
        public bool ShouldSerializeAvatarId() => __pbn__AvatarId != null;
        public void ResetAvatarId() => __pbn__AvatarId = null;
        private uint? __pbn__AvatarId;

        [global::ProtoBuf.ProtoMember(3, Name = @"point_id")]
        public uint PointId
        {
            get => __pbn__PointId.GetValueOrDefault();
            set => __pbn__PointId = value;
        }
        public bool ShouldSerializePointId() => __pbn__PointId != null;
        public void ResetPointId() => __pbn__PointId = null;
        private uint? __pbn__PointId;

        [global::ProtoBuf.ProtoMember(4, Name = @"level")]
        public uint Level
        {
            get => __pbn__Level.GetValueOrDefault();
            set => __pbn__Level = value;
        }
        public bool ShouldSerializeLevel() => __pbn__Level != null;
        public void ResetLevel() => __pbn__Level = null;
        private uint? __pbn__Level;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PromoteAvatarCsReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"avatar_id")]
        public uint AvatarId
        {
            get => __pbn__AvatarId.GetValueOrDefault();
            set => __pbn__AvatarId = value;
        }
        public bool ShouldSerializeAvatarId() => __pbn__AvatarId != null;
        public void ResetAvatarId() => __pbn__AvatarId = null;
        private uint? __pbn__AvatarId;

        [global::ProtoBuf.ProtoMember(2, Name = @"item_list")]
        public global::System.Collections.Generic.List<ItemCost> ItemLists { get; } = new global::System.Collections.Generic.List<ItemCost>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PromoteAvatarScRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"retcode")]
        public uint Retcode
        {
            get => __pbn__Retcode.GetValueOrDefault();
            set => __pbn__Retcode = value;
        }
        public bool ShouldSerializeRetcode() => __pbn__Retcode != null;
        public void ResetRetcode() => __pbn__Retcode = null;
        private uint? __pbn__Retcode;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DressAvatarCsReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"equipment_unique_id")]
        public uint EquipmentUniqueId
        {
            get => __pbn__EquipmentUniqueId.GetValueOrDefault();
            set => __pbn__EquipmentUniqueId = value;
        }
        public bool ShouldSerializeEquipmentUniqueId() => __pbn__EquipmentUniqueId != null;
        public void ResetEquipmentUniqueId() => __pbn__EquipmentUniqueId = null;
        private uint? __pbn__EquipmentUniqueId;

        [global::ProtoBuf.ProtoMember(2, Name = @"avatar_id")]
        public uint AvatarId
        {
            get => __pbn__AvatarId.GetValueOrDefault();
            set => __pbn__AvatarId = value;
        }
        public bool ShouldSerializeAvatarId() => __pbn__AvatarId != null;
        public void ResetAvatarId() => __pbn__AvatarId = null;
        private uint? __pbn__AvatarId;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DressAvatarScRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"retcode")]
        public uint Retcode
        {
            get => __pbn__Retcode.GetValueOrDefault();
            set => __pbn__Retcode = value;
        }
        public bool ShouldSerializeRetcode() => __pbn__Retcode != null;
        public void ResetRetcode() => __pbn__Retcode = null;
        private uint? __pbn__Retcode;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TakeOffEquipmentCsReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"avatar_id")]
        public uint AvatarId
        {
            get => __pbn__AvatarId.GetValueOrDefault();
            set => __pbn__AvatarId = value;
        }
        public bool ShouldSerializeAvatarId() => __pbn__AvatarId != null;
        public void ResetAvatarId() => __pbn__AvatarId = null;
        private uint? __pbn__AvatarId;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TakeOffEquipmentScRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"retcode")]
        public uint Retcode
        {
            get => __pbn__Retcode.GetValueOrDefault();
            set => __pbn__Retcode = value;
        }
        public bool ShouldSerializeRetcode() => __pbn__Retcode != null;
        public void ResetRetcode() => __pbn__Retcode = null;
        private uint? __pbn__Retcode;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AddAvatarScNotify : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"avatar_id")]
        public uint AvatarId
        {
            get => __pbn__AvatarId.GetValueOrDefault();
            set => __pbn__AvatarId = value;
        }
        public bool ShouldSerializeAvatarId() => __pbn__AvatarId != null;
        public void ResetAvatarId() => __pbn__AvatarId = null;
        private uint? __pbn__AvatarId;

        [global::ProtoBuf.ProtoMember(2, Name = @"rank")]
        public uint Rank
        {
            get => __pbn__Rank.GetValueOrDefault();
            set => __pbn__Rank = value;
        }
        public bool ShouldSerializeRank() => __pbn__Rank != null;
        public void ResetRank() => __pbn__Rank = null;
        private uint? __pbn__Rank;

        [global::ProtoBuf.ProtoMember(3, Name = @"reward")]
        public RewardData Reward { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public enum CmdAvatarType
    {
        CmdAvatarTypeNone = 0,
        CmdGetAvatarDataCsReq = 301,
        CmdGetAvatarDataScRsp = 302,
        CmdAvatarExpUpCsReq = 303,
        CmdAvatarExpUpScRsp = 304,
        CmdUnlockSkilltreeCsReq = 305,
        CmdUnlockSkilltreeScRsp = 306,
        CmdPromoteAvatarCsReq = 307,
        CmdPromoteAvatarScRsp = 308,
        CmdDressAvatarCsReq = 309,
        CmdDressAvatarScRsp = 310,
        CmdTakeOffEquipmentCsReq = 311,
        CmdTakeOffEquipmentScRsp = 312,
        CmdAddAvatarScNotify = 313,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
