// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: cs.battle.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace KazusaHSR.Protocol
{

    [global::ProtoBuf.ProtoContract()]
    public partial class PVEBattleResultCsReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"stage_id")]
        public uint StageId
        {
            get => __pbn__StageId.GetValueOrDefault();
            set => __pbn__StageId = value;
        }
        public bool ShouldSerializeStageId() => __pbn__StageId != null;
        public void ResetStageId() => __pbn__StageId = null;
        private uint? __pbn__StageId;

        [global::ProtoBuf.ProtoMember(2, Name = @"op_list")]
        public global::System.Collections.Generic.List<BattleOp> OpLists { get; } = new global::System.Collections.Generic.List<BattleOp>();

        [global::ProtoBuf.ProtoMember(3, Name = @"turn_snapshot_hash")]
        public byte[] TurnSnapshotHash
        {
            get => __pbn__TurnSnapshotHash;
            set => __pbn__TurnSnapshotHash = value;
        }
        public bool ShouldSerializeTurnSnapshotHash() => __pbn__TurnSnapshotHash != null;
        public void ResetTurnSnapshotHash() => __pbn__TurnSnapshotHash = null;
        private byte[] __pbn__TurnSnapshotHash;

        [global::ProtoBuf.ProtoMember(4, Name = @"cost_time")]
        public uint CostTime
        {
            get => __pbn__CostTime.GetValueOrDefault();
            set => __pbn__CostTime = value;
        }
        public bool ShouldSerializeCostTime() => __pbn__CostTime != null;
        public void ResetCostTime() => __pbn__CostTime = null;
        private uint? __pbn__CostTime;

        [global::ProtoBuf.ProtoMember(5, Name = @"debug_extra_info")]
        [global::System.ComponentModel.DefaultValue("")]
        public string DebugExtraInfo
        {
            get => __pbn__DebugExtraInfo ?? "";
            set => __pbn__DebugExtraInfo = value;
        }
        public bool ShouldSerializeDebugExtraInfo() => __pbn__DebugExtraInfo != null;
        public void ResetDebugExtraInfo() => __pbn__DebugExtraInfo = null;
        private string __pbn__DebugExtraInfo;

        [global::ProtoBuf.ProtoMember(6, Name = @"res_version")]
        public uint ResVersion
        {
            get => __pbn__ResVersion.GetValueOrDefault();
            set => __pbn__ResVersion = value;
        }
        public bool ShouldSerializeResVersion() => __pbn__ResVersion != null;
        public void ResetResVersion() => __pbn__ResVersion = null;
        private uint? __pbn__ResVersion;

        [global::ProtoBuf.ProtoMember(7, Name = @"is_ai_consider_ultra_skill")]
        public bool IsAiConsiderUltraSkill
        {
            get => __pbn__IsAiConsiderUltraSkill.GetValueOrDefault();
            set => __pbn__IsAiConsiderUltraSkill = value;
        }
        public bool ShouldSerializeIsAiConsiderUltraSkill() => __pbn__IsAiConsiderUltraSkill != null;
        public void ResetIsAiConsiderUltraSkill() => __pbn__IsAiConsiderUltraSkill = null;
        private bool? __pbn__IsAiConsiderUltraSkill;

        [global::ProtoBuf.ProtoMember(8, Name = @"end_status")]
        public BattleEndStatus EndStatus
        {
            get => __pbn__EndStatus.GetValueOrDefault();
            set => __pbn__EndStatus = value;
        }
        public bool ShouldSerializeEndStatus() => __pbn__EndStatus != null;
        public void ResetEndStatus() => __pbn__EndStatus = null;
        private BattleEndStatus? __pbn__EndStatus;

        [global::ProtoBuf.ProtoMember(9, Name = @"stt")]
        public BattleStatistics Stt { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PVEBattleResultScRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"retcode")]
        public uint Retcode
        {
            get => __pbn__Retcode.GetValueOrDefault();
            set => __pbn__Retcode = value;
        }
        public bool ShouldSerializeRetcode() => __pbn__Retcode != null;
        public void ResetRetcode() => __pbn__Retcode = null;
        private uint? __pbn__Retcode;

        [global::ProtoBuf.ProtoMember(2, Name = @"stage_id")]
        public uint StageId
        {
            get => __pbn__StageId.GetValueOrDefault();
            set => __pbn__StageId = value;
        }
        public bool ShouldSerializeStageId() => __pbn__StageId != null;
        public void ResetStageId() => __pbn__StageId = null;
        private uint? __pbn__StageId;

        [global::ProtoBuf.ProtoMember(3, Name = @"cur_finish_challenge")]
        public uint CurFinishChallenge
        {
            get => __pbn__CurFinishChallenge.GetValueOrDefault();
            set => __pbn__CurFinishChallenge = value;
        }
        public bool ShouldSerializeCurFinishChallenge() => __pbn__CurFinishChallenge != null;
        public void ResetCurFinishChallenge() => __pbn__CurFinishChallenge = null;
        private uint? __pbn__CurFinishChallenge;

        [global::ProtoBuf.ProtoMember(4, Name = @"drop_list")]
        public global::System.Collections.Generic.List<DropItem> DropLists { get; } = new global::System.Collections.Generic.List<DropItem>();

        [global::ProtoBuf.ProtoMember(5, Name = @"avatar_exp_reward")]
        public uint AvatarExpReward
        {
            get => __pbn__AvatarExpReward.GetValueOrDefault();
            set => __pbn__AvatarExpReward = value;
        }
        public bool ShouldSerializeAvatarExpReward() => __pbn__AvatarExpReward != null;
        public void ResetAvatarExpReward() => __pbn__AvatarExpReward = null;
        private uint? __pbn__AvatarExpReward;

        [global::ProtoBuf.ProtoMember(6, Name = @"bin_ver")]
        [global::System.ComponentModel.DefaultValue("")]
        public string BinVer
        {
            get => __pbn__BinVer ?? "";
            set => __pbn__BinVer = value;
        }
        public bool ShouldSerializeBinVer() => __pbn__BinVer != null;
        public void ResetBinVer() => __pbn__BinVer = null;
        private string __pbn__BinVer;

        [global::ProtoBuf.ProtoMember(7, Name = @"res_ver")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ResVer
        {
            get => __pbn__ResVer ?? "";
            set => __pbn__ResVer = value;
        }
        public bool ShouldSerializeResVer() => __pbn__ResVer != null;
        public void ResetResVer() => __pbn__ResVer = null;
        private string __pbn__ResVer;

        [global::ProtoBuf.ProtoMember(8, Name = @"battle_id")]
        public uint BattleId
        {
            get => __pbn__BattleId.GetValueOrDefault();
            set => __pbn__BattleId = value;
        }
        public bool ShouldSerializeBattleId() => __pbn__BattleId != null;
        public void ResetBattleId() => __pbn__BattleId = null;
        private uint? __pbn__BattleId;

        [global::ProtoBuf.ProtoMember(9, Name = @"end_status")]
        public BattleEndStatus EndStatus
        {
            get => __pbn__EndStatus.GetValueOrDefault();
            set => __pbn__EndStatus = value;
        }
        public bool ShouldSerializeEndStatus() => __pbn__EndStatus != null;
        public void ResetEndStatus() => __pbn__EndStatus = null;
        private BattleEndStatus? __pbn__EndStatus;

        [global::ProtoBuf.ProtoMember(10, Name = @"extra_drop_list")]
        public global::System.Collections.Generic.List<DropItem> ExtraDropLists { get; } = new global::System.Collections.Generic.List<DropItem>();

        [global::ProtoBuf.ProtoMember(11, Name = @"check_identical")]
        public bool CheckIdentical
        {
            get => __pbn__CheckIdentical.GetValueOrDefault();
            set => __pbn__CheckIdentical = value;
        }
        public bool ShouldSerializeCheckIdentical() => __pbn__CheckIdentical != null;
        public void ResetCheckIdentical() => __pbn__CheckIdentical = null;
        private bool? __pbn__CheckIdentical;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class QuitBattleCsReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class QuitBattleScRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"retcode")]
        public uint Retcode
        {
            get => __pbn__Retcode.GetValueOrDefault();
            set => __pbn__Retcode = value;
        }
        public bool ShouldSerializeRetcode() => __pbn__Retcode != null;
        public void ResetRetcode() => __pbn__Retcode = null;
        private uint? __pbn__Retcode;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetCurBattleInfoCsReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetCurBattleInfoScRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"retcode")]
        public uint Retcode
        {
            get => __pbn__Retcode.GetValueOrDefault();
            set => __pbn__Retcode = value;
        }
        public bool ShouldSerializeRetcode() => __pbn__Retcode != null;
        public void ResetRetcode() => __pbn__Retcode = null;
        private uint? __pbn__Retcode;

        [global::ProtoBuf.ProtoMember(2, Name = @"stage_id")]
        public uint StageId
        {
            get => __pbn__StageId.GetValueOrDefault();
            set => __pbn__StageId = value;
        }
        public bool ShouldSerializeStageId() => __pbn__StageId != null;
        public void ResetStageId() => __pbn__StageId = null;
        private uint? __pbn__StageId;

        [global::ProtoBuf.ProtoMember(3, Name = @"logic_random_seed")]
        public uint LogicRandomSeed
        {
            get => __pbn__LogicRandomSeed.GetValueOrDefault();
            set => __pbn__LogicRandomSeed = value;
        }
        public bool ShouldSerializeLogicRandomSeed() => __pbn__LogicRandomSeed != null;
        public void ResetLogicRandomSeed() => __pbn__LogicRandomSeed = null;
        private uint? __pbn__LogicRandomSeed;

        [global::ProtoBuf.ProtoMember(4, Name = @"avatar_list")]
        public global::System.Collections.Generic.List<BattleAvatar> AvatarLists { get; } = new global::System.Collections.Generic.List<BattleAvatar>();

        [global::ProtoBuf.ProtoMember(5, Name = @"battle_info")]
        public SceneBattleInfo BattleInfo { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SyncClientResVersionCsReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"res_version")]
        public uint ResVersion
        {
            get => __pbn__ResVersion.GetValueOrDefault();
            set => __pbn__ResVersion = value;
        }
        public bool ShouldSerializeResVersion() => __pbn__ResVersion != null;
        public void ResetResVersion() => __pbn__ResVersion = null;
        private uint? __pbn__ResVersion;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SyncClientResVersionScRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"retcode")]
        public uint Retcode
        {
            get => __pbn__Retcode.GetValueOrDefault();
            set => __pbn__Retcode = value;
        }
        public bool ShouldSerializeRetcode() => __pbn__Retcode != null;
        public void ResetRetcode() => __pbn__Retcode = null;
        private uint? __pbn__Retcode;

        [global::ProtoBuf.ProtoMember(2, Name = @"res_version")]
        public uint ResVersion
        {
            get => __pbn__ResVersion.GetValueOrDefault();
            set => __pbn__ResVersion = value;
        }
        public bool ShouldSerializeResVersion() => __pbn__ResVersion != null;
        public void ResetResVersion() => __pbn__ResVersion = null;
        private uint? __pbn__ResVersion;

    }

    [global::ProtoBuf.ProtoContract()]
    public enum CmdBattleType
    {
        CmdBattleTypeNone = 0,
        CmdPVEBattleResultCsReq = 101,
        CmdPVEBattleResultScRsp = 102,
        CmdQuitBattleCsReq = 103,
        CmdQuitBattleScRsp = 104,
        CmdGetCurBattleInfoCsReq = 105,
        CmdGetCurBattleInfoScRsp = 106,
        CmdSyncClientResVersionCsReq = 107,
        CmdSyncClientResVersionScRsp = 108,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
