// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: cs.challenge.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace KazusaHSR.Protocol
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Challenge : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"challenge_id")]
        public uint ChallengeId
        {
            get => __pbn__ChallengeId.GetValueOrDefault();
            set => __pbn__ChallengeId = value;
        }
        public bool ShouldSerializeChallengeId() => __pbn__ChallengeId != null;
        public void ResetChallengeId() => __pbn__ChallengeId = null;
        private uint? __pbn__ChallengeId;

        [global::ProtoBuf.ProtoMember(2, Name = @"stars")]
        public uint Stars
        {
            get => __pbn__Stars.GetValueOrDefault();
            set => __pbn__Stars = value;
        }
        public bool ShouldSerializeStars() => __pbn__Stars != null;
        public void ResetStars() => __pbn__Stars = null;
        private uint? __pbn__Stars;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetChallengeCsReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetChallengeScRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"retcode")]
        public uint Retcode
        {
            get => __pbn__Retcode.GetValueOrDefault();
            set => __pbn__Retcode = value;
        }
        public bool ShouldSerializeRetcode() => __pbn__Retcode != null;
        public void ResetRetcode() => __pbn__Retcode = null;
        private uint? __pbn__Retcode;

        [global::ProtoBuf.ProtoMember(2, Name = @"challenge_list")]
        public global::System.Collections.Generic.List<Challenge> ChallengeLists { get; } = new global::System.Collections.Generic.List<Challenge>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class StartChallengeCsReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"challenge_id")]
        public uint ChallengeId
        {
            get => __pbn__ChallengeId.GetValueOrDefault();
            set => __pbn__ChallengeId = value;
        }
        public bool ShouldSerializeChallengeId() => __pbn__ChallengeId != null;
        public void ResetChallengeId() => __pbn__ChallengeId = null;
        private uint? __pbn__ChallengeId;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class StartChallengeScRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"retcode")]
        public uint Retcode
        {
            get => __pbn__Retcode.GetValueOrDefault();
            set => __pbn__Retcode = value;
        }
        public bool ShouldSerializeRetcode() => __pbn__Retcode != null;
        public void ResetRetcode() => __pbn__Retcode = null;
        private uint? __pbn__Retcode;

        [global::ProtoBuf.ProtoMember(2, Name = @"maze")]
        public Maze Maze { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LeaveChallengeCsReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LeaveChallengeScRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"retcode")]
        public uint Retcode
        {
            get => __pbn__Retcode.GetValueOrDefault();
            set => __pbn__Retcode = value;
        }
        public bool ShouldSerializeRetcode() => __pbn__Retcode != null;
        public void ResetRetcode() => __pbn__Retcode = null;
        private uint? __pbn__Retcode;

        [global::ProtoBuf.ProtoMember(2, Name = @"maze")]
        public Maze Maze { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ChallengeSettleNotify : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"challenge_id")]
        public uint ChallengeId
        {
            get => __pbn__ChallengeId.GetValueOrDefault();
            set => __pbn__ChallengeId = value;
        }
        public bool ShouldSerializeChallengeId() => __pbn__ChallengeId != null;
        public void ResetChallengeId() => __pbn__ChallengeId = null;
        private uint? __pbn__ChallengeId;

        [global::ProtoBuf.ProtoMember(2, Name = @"is_win")]
        public bool IsWin
        {
            get => __pbn__IsWin.GetValueOrDefault();
            set => __pbn__IsWin = value;
        }
        public bool ShouldSerializeIsWin() => __pbn__IsWin != null;
        public void ResetIsWin() => __pbn__IsWin = null;
        private bool? __pbn__IsWin;

        [global::ProtoBuf.ProtoMember(3, Name = @"reward")]
        public RewardData Reward { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"stars")]
        public uint Stars
        {
            get => __pbn__Stars.GetValueOrDefault();
            set => __pbn__Stars = value;
        }
        public bool ShouldSerializeStars() => __pbn__Stars != null;
        public void ResetStars() => __pbn__Stars = null;
        private uint? __pbn__Stars;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class FinishChallengeCsReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"challenge_id")]
        public uint ChallengeId
        {
            get => __pbn__ChallengeId.GetValueOrDefault();
            set => __pbn__ChallengeId = value;
        }
        public bool ShouldSerializeChallengeId() => __pbn__ChallengeId != null;
        public void ResetChallengeId() => __pbn__ChallengeId = null;
        private uint? __pbn__ChallengeId;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class FinishChallengeScRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"retcode")]
        public uint Retcode
        {
            get => __pbn__Retcode.GetValueOrDefault();
            set => __pbn__Retcode = value;
        }
        public bool ShouldSerializeRetcode() => __pbn__Retcode != null;
        public void ResetRetcode() => __pbn__Retcode = null;
        private uint? __pbn__Retcode;

    }

    [global::ProtoBuf.ProtoContract()]
    public enum CmdChallengeType
    {
        CmdChallengeTypeNone = 0,
        CmdGetChallengeCsReq = 1701,
        CmdGetChallengeScRsp = 1702,
        CmdStartChallengeCsReq = 1703,
        CmdStartChallengeScRsp = 1704,
        CmdLeaveChallengeCsReq = 1705,
        CmdLeaveChallengeScRsp = 1706,
        CmdChallengeSettleNotify = 1707,
        CmdFinishChallengeCsReq = 1708,
        CmdFinishChallengeScRsp = 1709,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
