// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: cs.common.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace KazusaHSR.Protocol
{

    [global::ProtoBuf.ProtoContract()]
    public partial class PileItem : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"item_id")]
        public uint ItemId
        {
            get => __pbn__ItemId.GetValueOrDefault();
            set => __pbn__ItemId = value;
        }
        public bool ShouldSerializeItemId() => __pbn__ItemId != null;
        public void ResetItemId() => __pbn__ItemId = null;
        private uint? __pbn__ItemId;

        [global::ProtoBuf.ProtoMember(2, Name = @"item_num")]
        public uint ItemNum
        {
            get => __pbn__ItemNum.GetValueOrDefault();
            set => __pbn__ItemNum = value;
        }
        public bool ShouldSerializeItemNum() => __pbn__ItemNum != null;
        public void ResetItemNum() => __pbn__ItemNum = null;
        private uint? __pbn__ItemNum;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ItemCost : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"pile_item")]
        public PileItem PileItem
        {
            get => __pbn__Item.Is(1) ? ((PileItem)__pbn__Item.Object) : default;
            set => __pbn__Item = new global::ProtoBuf.DiscriminatedUnion32Object(1, value);
        }
        public bool ShouldSerializePileItem() => __pbn__Item.Is(1);
        public void ResetPileItem() => global::ProtoBuf.DiscriminatedUnion32Object.Reset(ref __pbn__Item, 1);

        private global::ProtoBuf.DiscriminatedUnion32Object __pbn__Item;

        [global::ProtoBuf.ProtoMember(2, Name = @"unique_id")]
        public uint UniqueId
        {
            get => __pbn__Item.Is(2) ? __pbn__Item.UInt32 : default;
            set => __pbn__Item = new global::ProtoBuf.DiscriminatedUnion32Object(2, value);
        }
        public bool ShouldSerializeUniqueId() => __pbn__Item.Is(2);
        public void ResetUniqueId() => global::ProtoBuf.DiscriminatedUnion32Object.Reset(ref __pbn__Item, 2);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ItemCostData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"item_list")]
        public global::System.Collections.Generic.List<ItemCost> ItemLists { get; } = new global::System.Collections.Generic.List<ItemCost>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DropItem : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"item_id")]
        public uint ItemId
        {
            get => __pbn__ItemId.GetValueOrDefault();
            set => __pbn__ItemId = value;
        }
        public bool ShouldSerializeItemId() => __pbn__ItemId != null;
        public void ResetItemId() => __pbn__ItemId = null;
        private uint? __pbn__ItemId;

        [global::ProtoBuf.ProtoMember(2, Name = @"level")]
        public uint Level
        {
            get => __pbn__Level.GetValueOrDefault();
            set => __pbn__Level = value;
        }
        public bool ShouldSerializeLevel() => __pbn__Level != null;
        public void ResetLevel() => __pbn__Level = null;
        private uint? __pbn__Level;

        [global::ProtoBuf.ProtoMember(3, Name = @"rank")]
        public uint Rank
        {
            get => __pbn__Rank.GetValueOrDefault();
            set => __pbn__Rank = value;
        }
        public bool ShouldSerializeRank() => __pbn__Rank != null;
        public void ResetRank() => __pbn__Rank = null;
        private uint? __pbn__Rank;

        [global::ProtoBuf.ProtoMember(4, Name = @"num")]
        public uint Num
        {
            get => __pbn__Num.GetValueOrDefault();
            set => __pbn__Num = value;
        }
        public bool ShouldSerializeNum() => __pbn__Num != null;
        public void ResetNum() => __pbn__Num = null;
        private uint? __pbn__Num;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DropData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"item_list")]
        public global::System.Collections.Generic.List<DropItem> ItemLists { get; } = new global::System.Collections.Generic.List<DropItem>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RewardItem : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"item_id")]
        public uint ItemId
        {
            get => __pbn__ItemId.GetValueOrDefault();
            set => __pbn__ItemId = value;
        }
        public bool ShouldSerializeItemId() => __pbn__ItemId != null;
        public void ResetItemId() => __pbn__ItemId = null;
        private uint? __pbn__ItemId;

        [global::ProtoBuf.ProtoMember(2, Name = @"level")]
        public uint Level
        {
            get => __pbn__Level.GetValueOrDefault();
            set => __pbn__Level = value;
        }
        public bool ShouldSerializeLevel() => __pbn__Level != null;
        public void ResetLevel() => __pbn__Level = null;
        private uint? __pbn__Level;

        [global::ProtoBuf.ProtoMember(3, Name = @"rank")]
        public uint Rank
        {
            get => __pbn__Rank.GetValueOrDefault();
            set => __pbn__Rank = value;
        }
        public bool ShouldSerializeRank() => __pbn__Rank != null;
        public void ResetRank() => __pbn__Rank = null;
        private uint? __pbn__Rank;

        [global::ProtoBuf.ProtoMember(4, Name = @"num")]
        public uint Num
        {
            get => __pbn__Num.GetValueOrDefault();
            set => __pbn__Num = value;
        }
        public bool ShouldSerializeNum() => __pbn__Num != null;
        public void ResetNum() => __pbn__Num = null;
        private uint? __pbn__Num;

        [global::ProtoBuf.ProtoMember(5, Name = @"promotion")]
        public uint Promotion
        {
            get => __pbn__Promotion.GetValueOrDefault();
            set => __pbn__Promotion = value;
        }
        public bool ShouldSerializePromotion() => __pbn__Promotion != null;
        public void ResetPromotion() => __pbn__Promotion = null;
        private uint? __pbn__Promotion;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RewardData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"item_list")]
        public global::System.Collections.Generic.List<RewardItem> ItemLists { get; } = new global::System.Collections.Generic.List<RewardItem>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SceneMonsterWave : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"monster_id_list", IsPacked = true)]
        public uint[] MonsterIdLists { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"drop_list")]
        public global::System.Collections.Generic.List<DropData> DropLists { get; } = new global::System.Collections.Generic.List<DropData>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SceneBattleInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"logic_random_seed")]
        public uint LogicRandomSeed
        {
            get => __pbn__LogicRandomSeed.GetValueOrDefault();
            set => __pbn__LogicRandomSeed = value;
        }
        public bool ShouldSerializeLogicRandomSeed() => __pbn__LogicRandomSeed != null;
        public void ResetLogicRandomSeed() => __pbn__LogicRandomSeed = null;
        private uint? __pbn__LogicRandomSeed;

        [global::ProtoBuf.ProtoMember(2, Name = @"stage_id")]
        public uint StageId
        {
            get => __pbn__StageId.GetValueOrDefault();
            set => __pbn__StageId = value;
        }
        public bool ShouldSerializeStageId() => __pbn__StageId != null;
        public void ResetStageId() => __pbn__StageId = null;
        private uint? __pbn__StageId;

        [global::ProtoBuf.ProtoMember(3, Name = @"monster_wave_list")]
        public global::System.Collections.Generic.List<SceneMonsterWave> MonsterWaveLists { get; } = new global::System.Collections.Generic.List<SceneMonsterWave>();

        [global::ProtoBuf.ProtoMember(4, Name = @"battle_avatar_list")]
        public global::System.Collections.Generic.List<BattleAvatar> BattleAvatarLists { get; } = new global::System.Collections.Generic.List<BattleAvatar>();

        [global::ProtoBuf.ProtoMember(5, Name = @"buff_list")]
        public global::System.Collections.Generic.List<BattleBuff> BuffLists { get; } = new global::System.Collections.Generic.List<BattleBuff>();

    }

    [global::ProtoBuf.ProtoContract()]
    public enum MissionStatus
    {
        [global::ProtoBuf.ProtoEnum(Name = @"MISSION_NONE")]
        MissionNone = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"MISSION_DOING")]
        MissionDoing = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"MISSION_FINISH")]
        MissionFinish = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"MISSION_PREPARED")]
        MissionPrepared = 3,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
