// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: cs.item.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace KazusaHSR.Protocol
{

    [global::ProtoBuf.ProtoContract()]
    public partial class GetBagCsReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Equipment : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"unique_id")]
        public uint UniqueId
        {
            get => __pbn__UniqueId.GetValueOrDefault();
            set => __pbn__UniqueId = value;
        }
        public bool ShouldSerializeUniqueId() => __pbn__UniqueId != null;
        public void ResetUniqueId() => __pbn__UniqueId = null;
        private uint? __pbn__UniqueId;

        [global::ProtoBuf.ProtoMember(2, Name = @"tid")]
        public uint Tid
        {
            get => __pbn__Tid.GetValueOrDefault();
            set => __pbn__Tid = value;
        }
        public bool ShouldSerializeTid() => __pbn__Tid != null;
        public void ResetTid() => __pbn__Tid = null;
        private uint? __pbn__Tid;

        [global::ProtoBuf.ProtoMember(3, Name = @"level")]
        public uint Level
        {
            get => __pbn__Level.GetValueOrDefault();
            set => __pbn__Level = value;
        }
        public bool ShouldSerializeLevel() => __pbn__Level != null;
        public void ResetLevel() => __pbn__Level = null;
        private uint? __pbn__Level;

        [global::ProtoBuf.ProtoMember(4, Name = @"exp")]
        public uint Exp
        {
            get => __pbn__Exp.GetValueOrDefault();
            set => __pbn__Exp = value;
        }
        public bool ShouldSerializeExp() => __pbn__Exp != null;
        public void ResetExp() => __pbn__Exp = null;
        private uint? __pbn__Exp;

        [global::ProtoBuf.ProtoMember(5, Name = @"rank")]
        public uint Rank
        {
            get => __pbn__Rank.GetValueOrDefault();
            set => __pbn__Rank = value;
        }
        public bool ShouldSerializeRank() => __pbn__Rank != null;
        public void ResetRank() => __pbn__Rank = null;
        private uint? __pbn__Rank;

        [global::ProtoBuf.ProtoMember(6, Name = @"belong_avatar_id")]
        public uint BelongAvatarId
        {
            get => __pbn__BelongAvatarId.GetValueOrDefault();
            set => __pbn__BelongAvatarId = value;
        }
        public bool ShouldSerializeBelongAvatarId() => __pbn__BelongAvatarId != null;
        public void ResetBelongAvatarId() => __pbn__BelongAvatarId = null;
        private uint? __pbn__BelongAvatarId;

        [global::ProtoBuf.ProtoMember(7, Name = @"is_protected")]
        public bool IsProtected
        {
            get => __pbn__IsProtected.GetValueOrDefault();
            set => __pbn__IsProtected = value;
        }
        public bool ShouldSerializeIsProtected() => __pbn__IsProtected != null;
        public void ResetIsProtected() => __pbn__IsProtected = null;
        private bool? __pbn__IsProtected;

        [global::ProtoBuf.ProtoMember(8, Name = @"promotion")]
        public uint Promotion
        {
            get => __pbn__Promotion.GetValueOrDefault();
            set => __pbn__Promotion = value;
        }
        public bool ShouldSerializePromotion() => __pbn__Promotion != null;
        public void ResetPromotion() => __pbn__Promotion = null;
        private uint? __pbn__Promotion;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Material : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"tid")]
        public uint Tid
        {
            get => __pbn__Tid.GetValueOrDefault();
            set => __pbn__Tid = value;
        }
        public bool ShouldSerializeTid() => __pbn__Tid != null;
        public void ResetTid() => __pbn__Tid = null;
        private uint? __pbn__Tid;

        [global::ProtoBuf.ProtoMember(2, Name = @"num")]
        public uint Num
        {
            get => __pbn__Num.GetValueOrDefault();
            set => __pbn__Num = value;
        }
        public bool ShouldSerializeNum() => __pbn__Num != null;
        public void ResetNum() => __pbn__Num = null;
        private uint? __pbn__Num;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetBagScRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"retcode")]
        public uint Retcode
        {
            get => __pbn__Retcode.GetValueOrDefault();
            set => __pbn__Retcode = value;
        }
        public bool ShouldSerializeRetcode() => __pbn__Retcode != null;
        public void ResetRetcode() => __pbn__Retcode = null;
        private uint? __pbn__Retcode;

        [global::ProtoBuf.ProtoMember(2, Name = @"equipment_list")]
        public global::System.Collections.Generic.List<Equipment> EquipmentLists { get; } = new global::System.Collections.Generic.List<Equipment>();

        [global::ProtoBuf.ProtoMember(3, Name = @"material_list")]
        public global::System.Collections.Generic.List<Material> MaterialLists { get; } = new global::System.Collections.Generic.List<Material>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PromoteEquipmentCsReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"equipment_unique_id")]
        public uint EquipmentUniqueId
        {
            get => __pbn__EquipmentUniqueId.GetValueOrDefault();
            set => __pbn__EquipmentUniqueId = value;
        }
        public bool ShouldSerializeEquipmentUniqueId() => __pbn__EquipmentUniqueId != null;
        public void ResetEquipmentUniqueId() => __pbn__EquipmentUniqueId = null;
        private uint? __pbn__EquipmentUniqueId;

        [global::ProtoBuf.ProtoMember(2, Name = @"cost_data")]
        public ItemCostData CostData { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PromoteEquipmentScRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"retcode")]
        public uint Retcode
        {
            get => __pbn__Retcode.GetValueOrDefault();
            set => __pbn__Retcode = value;
        }
        public bool ShouldSerializeRetcode() => __pbn__Retcode != null;
        public void ResetRetcode() => __pbn__Retcode = null;
        private uint? __pbn__Retcode;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LockEquipmentCsReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"equipment_unique_id")]
        public uint EquipmentUniqueId
        {
            get => __pbn__EquipmentUniqueId.GetValueOrDefault();
            set => __pbn__EquipmentUniqueId = value;
        }
        public bool ShouldSerializeEquipmentUniqueId() => __pbn__EquipmentUniqueId != null;
        public void ResetEquipmentUniqueId() => __pbn__EquipmentUniqueId = null;
        private uint? __pbn__EquipmentUniqueId;

        [global::ProtoBuf.ProtoMember(2, Name = @"is_lock")]
        public bool IsLock
        {
            get => __pbn__IsLock.GetValueOrDefault();
            set => __pbn__IsLock = value;
        }
        public bool ShouldSerializeIsLock() => __pbn__IsLock != null;
        public void ResetIsLock() => __pbn__IsLock = null;
        private bool? __pbn__IsLock;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LockEquipmentScRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"retcode")]
        public uint Retcode
        {
            get => __pbn__Retcode.GetValueOrDefault();
            set => __pbn__Retcode = value;
        }
        public bool ShouldSerializeRetcode() => __pbn__Retcode != null;
        public void ResetRetcode() => __pbn__Retcode = null;
        private uint? __pbn__Retcode;

        [global::ProtoBuf.ProtoMember(2, Name = @"equipment_unique_id")]
        public uint EquipmentUniqueId
        {
            get => __pbn__EquipmentUniqueId.GetValueOrDefault();
            set => __pbn__EquipmentUniqueId = value;
        }
        public bool ShouldSerializeEquipmentUniqueId() => __pbn__EquipmentUniqueId != null;
        public void ResetEquipmentUniqueId() => __pbn__EquipmentUniqueId = null;
        private uint? __pbn__EquipmentUniqueId;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UseItemCsReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"use_item_id")]
        public uint UseItemId
        {
            get => __pbn__UseItemId.GetValueOrDefault();
            set => __pbn__UseItemId = value;
        }
        public bool ShouldSerializeUseItemId() => __pbn__UseItemId != null;
        public void ResetUseItemId() => __pbn__UseItemId = null;
        private uint? __pbn__UseItemId;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UseItemScRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"retcode")]
        public uint Retcode
        {
            get => __pbn__Retcode.GetValueOrDefault();
            set => __pbn__Retcode = value;
        }
        public bool ShouldSerializeRetcode() => __pbn__Retcode != null;
        public void ResetRetcode() => __pbn__Retcode = null;
        private uint? __pbn__Retcode;

        [global::ProtoBuf.ProtoMember(2, Name = @"use_item_id")]
        public uint UseItemId
        {
            get => __pbn__UseItemId.GetValueOrDefault();
            set => __pbn__UseItemId = value;
        }
        public bool ShouldSerializeUseItemId() => __pbn__UseItemId != null;
        public void ResetUseItemId() => __pbn__UseItemId = null;
        private uint? __pbn__UseItemId;

        [global::ProtoBuf.ProtoMember(3, Name = @"reward_data")]
        public RewardData RewardData { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RankUpEquipmentCsReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"equipment_unique_id")]
        public uint EquipmentUniqueId
        {
            get => __pbn__EquipmentUniqueId.GetValueOrDefault();
            set => __pbn__EquipmentUniqueId = value;
        }
        public bool ShouldSerializeEquipmentUniqueId() => __pbn__EquipmentUniqueId != null;
        public void ResetEquipmentUniqueId() => __pbn__EquipmentUniqueId = null;
        private uint? __pbn__EquipmentUniqueId;

        [global::ProtoBuf.ProtoMember(2, Name = @"equipment_id_list", IsPacked = true)]
        public uint[] EquipmentIdLists { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RankUpEquipmentScRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"retcode")]
        public uint Retcode
        {
            get => __pbn__Retcode.GetValueOrDefault();
            set => __pbn__Retcode = value;
        }
        public bool ShouldSerializeRetcode() => __pbn__Retcode != null;
        public void ResetRetcode() => __pbn__Retcode = null;
        private uint? __pbn__Retcode;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ExpUpEquipmentCsReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"equipment_unique_id")]
        public uint EquipmentUniqueId
        {
            get => __pbn__EquipmentUniqueId.GetValueOrDefault();
            set => __pbn__EquipmentUniqueId = value;
        }
        public bool ShouldSerializeEquipmentUniqueId() => __pbn__EquipmentUniqueId != null;
        public void ResetEquipmentUniqueId() => __pbn__EquipmentUniqueId = null;
        private uint? __pbn__EquipmentUniqueId;

        [global::ProtoBuf.ProtoMember(2, Name = @"cost_data")]
        public ItemCostData CostData { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ExpUpEquipmentScRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"retcode")]
        public uint Retcode
        {
            get => __pbn__Retcode.GetValueOrDefault();
            set => __pbn__Retcode = value;
        }
        public bool ShouldSerializeRetcode() => __pbn__Retcode != null;
        public void ResetRetcode() => __pbn__Retcode = null;
        private uint? __pbn__Retcode;

        [global::ProtoBuf.ProtoMember(2, Name = @"return_item_list")]
        public global::System.Collections.Generic.List<PileItem> ReturnItemLists { get; } = new global::System.Collections.Generic.List<PileItem>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UseItemFoodCsReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"use_item_id")]
        public uint UseItemId
        {
            get => __pbn__UseItemId.GetValueOrDefault();
            set => __pbn__UseItemId = value;
        }
        public bool ShouldSerializeUseItemId() => __pbn__UseItemId != null;
        public void ResetUseItemId() => __pbn__UseItemId = null;
        private uint? __pbn__UseItemId;

        [global::ProtoBuf.ProtoMember(2, Name = @"use_item_count")]
        public uint UseItemCount
        {
            get => __pbn__UseItemCount.GetValueOrDefault();
            set => __pbn__UseItemCount = value;
        }
        public bool ShouldSerializeUseItemCount() => __pbn__UseItemCount != null;
        public void ResetUseItemCount() => __pbn__UseItemCount = null;
        private uint? __pbn__UseItemCount;

        [global::ProtoBuf.ProtoMember(3, Name = @"use_avatar_id")]
        public uint UseAvatarId
        {
            get => __pbn__UseAvatarId.GetValueOrDefault();
            set => __pbn__UseAvatarId = value;
        }
        public bool ShouldSerializeUseAvatarId() => __pbn__UseAvatarId != null;
        public void ResetUseAvatarId() => __pbn__UseAvatarId = null;
        private uint? __pbn__UseAvatarId;

        [global::ProtoBuf.ProtoMember(4, Name = @"use_avatar_type")]
        public AvatarType UseAvatarType
        {
            get => __pbn__UseAvatarType.GetValueOrDefault();
            set => __pbn__UseAvatarType = value;
        }
        public bool ShouldSerializeUseAvatarType() => __pbn__UseAvatarType != null;
        public void ResetUseAvatarType() => __pbn__UseAvatarType = null;
        private AvatarType? __pbn__UseAvatarType;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UseItemFoodScRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"retcode")]
        public uint Retcode
        {
            get => __pbn__Retcode.GetValueOrDefault();
            set => __pbn__Retcode = value;
        }
        public bool ShouldSerializeRetcode() => __pbn__Retcode != null;
        public void ResetRetcode() => __pbn__Retcode = null;
        private uint? __pbn__Retcode;

        [global::ProtoBuf.ProtoMember(2, Name = @"use_item_id")]
        public uint UseItemId
        {
            get => __pbn__UseItemId.GetValueOrDefault();
            set => __pbn__UseItemId = value;
        }
        public bool ShouldSerializeUseItemId() => __pbn__UseItemId != null;
        public void ResetUseItemId() => __pbn__UseItemId = null;
        private uint? __pbn__UseItemId;

        [global::ProtoBuf.ProtoMember(3, Name = @"use_item_count")]
        public uint UseItemCount
        {
            get => __pbn__UseItemCount.GetValueOrDefault();
            set => __pbn__UseItemCount = value;
        }
        public bool ShouldSerializeUseItemCount() => __pbn__UseItemCount != null;
        public void ResetUseItemCount() => __pbn__UseItemCount = null;
        private uint? __pbn__UseItemCount;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ComposeItemCsReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"compose_id")]
        public uint ComposeId
        {
            get => __pbn__ComposeId.GetValueOrDefault();
            set => __pbn__ComposeId = value;
        }
        public bool ShouldSerializeComposeId() => __pbn__ComposeId != null;
        public void ResetComposeId() => __pbn__ComposeId = null;
        private uint? __pbn__ComposeId;

        [global::ProtoBuf.ProtoMember(2, Name = @"count")]
        public uint Count
        {
            get => __pbn__Count.GetValueOrDefault();
            set => __pbn__Count = value;
        }
        public bool ShouldSerializeCount() => __pbn__Count != null;
        public void ResetCount() => __pbn__Count = null;
        private uint? __pbn__Count;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ComposeItemScRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"retcode")]
        public uint Retcode
        {
            get => __pbn__Retcode.GetValueOrDefault();
            set => __pbn__Retcode = value;
        }
        public bool ShouldSerializeRetcode() => __pbn__Retcode != null;
        public void ResetRetcode() => __pbn__Retcode = null;
        private uint? __pbn__Retcode;

        [global::ProtoBuf.ProtoMember(2, Name = @"compose_id")]
        public uint ComposeId
        {
            get => __pbn__ComposeId.GetValueOrDefault();
            set => __pbn__ComposeId = value;
        }
        public bool ShouldSerializeComposeId() => __pbn__ComposeId != null;
        public void ResetComposeId() => __pbn__ComposeId = null;
        private uint? __pbn__ComposeId;

        [global::ProtoBuf.ProtoMember(3, Name = @"count")]
        public uint Count
        {
            get => __pbn__Count.GetValueOrDefault();
            set => __pbn__Count = value;
        }
        public bool ShouldSerializeCount() => __pbn__Count != null;
        public void ResetCount() => __pbn__Count = null;
        private uint? __pbn__Count;

    }

    [global::ProtoBuf.ProtoContract()]
    public enum CmdItemType
    {
        CmdItemTypeNone = 0,
        CmdGetBagCsReq = 501,
        CmdGetBagScRsp = 502,
        CmdPromoteEquipmentCsReq = 503,
        CmdPromoteEquipmentScRsp = 504,
        CmdLockEquipmentCsReq = 505,
        CmdLockEquipmentScRsp = 506,
        CmdUseItemCsReq = 507,
        CmdUseItemScRsp = 508,
        CmdRankUpEquipmentCsReq = 509,
        CmdRankUpEquipmentScRsp = 510,
        CmdExpUpEquipmentCsReq = 511,
        CmdExpUpEquipmentScRsp = 512,
        CmdUseItemFoodCsReq = 513,
        CmdUseItemFoodScRsp = 514,
        CmdComposeItemCsReq = 515,
        CmdComposeItemScRsp = 516,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
