// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: cs.lineup.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace KazusaHSR.Protocol
{

    [global::ProtoBuf.ProtoContract()]
    public partial class GetStageLineupCsReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class StageLineup : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"stage_type")]
        public uint StageType
        {
            get => __pbn__StageType.GetValueOrDefault();
            set => __pbn__StageType = value;
        }
        public bool ShouldSerializeStageType() => __pbn__StageType != null;
        public void ResetStageType() => __pbn__StageType = null;
        private uint? __pbn__StageType;

        [global::ProtoBuf.ProtoMember(2, Name = @"lineup_index")]
        public uint LineupIndex
        {
            get => __pbn__LineupIndex.GetValueOrDefault();
            set => __pbn__LineupIndex = value;
        }
        public bool ShouldSerializeLineupIndex() => __pbn__LineupIndex != null;
        public void ResetLineupIndex() => __pbn__LineupIndex = null;
        private uint? __pbn__LineupIndex;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetStageLineupScRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"retcode")]
        public uint Retcode
        {
            get => __pbn__Retcode.GetValueOrDefault();
            set => __pbn__Retcode = value;
        }
        public bool ShouldSerializeRetcode() => __pbn__Retcode != null;
        public void ResetRetcode() => __pbn__Retcode = null;
        private uint? __pbn__Retcode;

        [global::ProtoBuf.ProtoMember(2, Name = @"stage_lineup_list")]
        public global::System.Collections.Generic.List<StageLineup> StageLineupLists { get; } = new global::System.Collections.Generic.List<StageLineup>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LineupAvatar : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"slot")]
        public uint Slot
        {
            get => __pbn__Slot.GetValueOrDefault();
            set => __pbn__Slot = value;
        }
        public bool ShouldSerializeSlot() => __pbn__Slot != null;
        public void ResetSlot() => __pbn__Slot = null;
        private uint? __pbn__Slot;

        [global::ProtoBuf.ProtoMember(2, Name = @"avatar_type")]
        public AvatarType AvatarType
        {
            get => __pbn__AvatarType.GetValueOrDefault();
            set => __pbn__AvatarType = value;
        }
        public bool ShouldSerializeAvatarType() => __pbn__AvatarType != null;
        public void ResetAvatarType() => __pbn__AvatarType = null;
        private AvatarType? __pbn__AvatarType;

        [global::ProtoBuf.ProtoMember(3, Name = @"id")]
        public uint Id
        {
            get => __pbn__Id.GetValueOrDefault();
            set => __pbn__Id = value;
        }
        public bool ShouldSerializeId() => __pbn__Id != null;
        public void ResetId() => __pbn__Id = null;
        private uint? __pbn__Id;

        [global::ProtoBuf.ProtoMember(4, Name = @"skill_cast_cnt")]
        public uint SkillCastCnt
        {
            get => __pbn__SkillCastCnt.GetValueOrDefault();
            set => __pbn__SkillCastCnt = value;
        }
        public bool ShouldSerializeSkillCastCnt() => __pbn__SkillCastCnt != null;
        public void ResetSkillCastCnt() => __pbn__SkillCastCnt = null;
        private uint? __pbn__SkillCastCnt;

        [global::ProtoBuf.ProtoMember(5, Name = @"hp")]
        public uint Hp
        {
            get => __pbn__Hp.GetValueOrDefault();
            set => __pbn__Hp = value;
        }
        public bool ShouldSerializeHp() => __pbn__Hp != null;
        public void ResetHp() => __pbn__Hp = null;
        private uint? __pbn__Hp;

        [global::ProtoBuf.ProtoMember(6, Name = @"sp")]
        public uint Sp
        {
            get => __pbn__Sp.GetValueOrDefault();
            set => __pbn__Sp = value;
        }
        public bool ShouldSerializeSp() => __pbn__Sp != null;
        public void ResetSp() => __pbn__Sp = null;
        private uint? __pbn__Sp;

        [global::ProtoBuf.ProtoMember(7, Name = @"satiety")]
        public uint Satiety
        {
            get => __pbn__Satiety.GetValueOrDefault();
            set => __pbn__Satiety = value;
        }
        public bool ShouldSerializeSatiety() => __pbn__Satiety != null;
        public void ResetSatiety() => __pbn__Satiety = null;
        private uint? __pbn__Satiety;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LineupInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"avatar_list")]
        public global::System.Collections.Generic.List<LineupAvatar> AvatarLists { get; } = new global::System.Collections.Generic.List<LineupAvatar>();

        [global::ProtoBuf.ProtoMember(2, Name = @"is_virtual")]
        public bool IsVirtual
        {
            get => __pbn__IsVirtual.GetValueOrDefault();
            set => __pbn__IsVirtual = value;
        }
        public bool ShouldSerializeIsVirtual() => __pbn__IsVirtual != null;
        public void ResetIsVirtual() => __pbn__IsVirtual = null;
        private bool? __pbn__IsVirtual;

        [global::ProtoBuf.ProtoMember(3, Name = @"plane_id")]
        public uint PlaneId
        {
            get => __pbn__PlaneId.GetValueOrDefault();
            set => __pbn__PlaneId = value;
        }
        public bool ShouldSerializePlaneId() => __pbn__PlaneId != null;
        public void ResetPlaneId() => __pbn__PlaneId = null;
        private uint? __pbn__PlaneId;

        [global::ProtoBuf.ProtoMember(4, Name = @"mp")]
        public uint Mp
        {
            get => __pbn__Mp.GetValueOrDefault();
            set => __pbn__Mp = value;
        }
        public bool ShouldSerializeMp() => __pbn__Mp != null;
        public void ResetMp() => __pbn__Mp = null;
        private uint? __pbn__Mp;

        [global::ProtoBuf.ProtoMember(5, Name = @"leader_slot")]
        public uint LeaderSlot
        {
            get => __pbn__LeaderSlot.GetValueOrDefault();
            set => __pbn__LeaderSlot = value;
        }
        public bool ShouldSerializeLeaderSlot() => __pbn__LeaderSlot != null;
        public void ResetLeaderSlot() => __pbn__LeaderSlot = null;
        private uint? __pbn__LeaderSlot;

        [global::ProtoBuf.ProtoMember(6, Name = @"index")]
        public uint Index
        {
            get => __pbn__Index.GetValueOrDefault();
            set => __pbn__Index = value;
        }
        public bool ShouldSerializeIndex() => __pbn__Index != null;
        public void ResetIndex() => __pbn__Index = null;
        private uint? __pbn__Index;

        [global::ProtoBuf.ProtoMember(7, Name = @"extra_lineup_type")]
        public ExtraLineupType ExtraLineupType
        {
            get => __pbn__ExtraLineupType.GetValueOrDefault();
            set => __pbn__ExtraLineupType = value;
        }
        public bool ShouldSerializeExtraLineupType() => __pbn__ExtraLineupType != null;
        public void ResetExtraLineupType() => __pbn__ExtraLineupType = null;
        private ExtraLineupType? __pbn__ExtraLineupType;

        [global::ProtoBuf.ProtoMember(8, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name
        {
            get => __pbn__Name ?? "";
            set => __pbn__Name = value;
        }
        public bool ShouldSerializeName() => __pbn__Name != null;
        public void ResetName() => __pbn__Name = null;
        private string __pbn__Name;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetCurLineupDataCsReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetCurLineupDataScRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"retcode")]
        public uint Retcode
        {
            get => __pbn__Retcode.GetValueOrDefault();
            set => __pbn__Retcode = value;
        }
        public bool ShouldSerializeRetcode() => __pbn__Retcode != null;
        public void ResetRetcode() => __pbn__Retcode = null;
        private uint? __pbn__Retcode;

        [global::ProtoBuf.ProtoMember(2, Name = @"lineup")]
        public LineupInfo Lineup { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class JoinLineupCsReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"avatar_id")]
        public uint AvatarId
        {
            get => __pbn__AvatarId.GetValueOrDefault();
            set => __pbn__AvatarId = value;
        }
        public bool ShouldSerializeAvatarId() => __pbn__AvatarId != null;
        public void ResetAvatarId() => __pbn__AvatarId = null;
        private uint? __pbn__AvatarId;

        [global::ProtoBuf.ProtoMember(2, Name = @"is_virtual")]
        public bool IsVirtual
        {
            get => __pbn__IsVirtual.GetValueOrDefault();
            set => __pbn__IsVirtual = value;
        }
        public bool ShouldSerializeIsVirtual() => __pbn__IsVirtual != null;
        public void ResetIsVirtual() => __pbn__IsVirtual = null;
        private bool? __pbn__IsVirtual;

        [global::ProtoBuf.ProtoMember(3, Name = @"plane_id")]
        public uint PlaneId
        {
            get => __pbn__PlaneId.GetValueOrDefault();
            set => __pbn__PlaneId = value;
        }
        public bool ShouldSerializePlaneId() => __pbn__PlaneId != null;
        public void ResetPlaneId() => __pbn__PlaneId = null;
        private uint? __pbn__PlaneId;

        [global::ProtoBuf.ProtoMember(4, Name = @"slot")]
        public uint Slot
        {
            get => __pbn__Slot.GetValueOrDefault();
            set => __pbn__Slot = value;
        }
        public bool ShouldSerializeSlot() => __pbn__Slot != null;
        public void ResetSlot() => __pbn__Slot = null;
        private uint? __pbn__Slot;

        [global::ProtoBuf.ProtoMember(5, Name = @"index")]
        public uint Index
        {
            get => __pbn__Index.GetValueOrDefault();
            set => __pbn__Index = value;
        }
        public bool ShouldSerializeIndex() => __pbn__Index != null;
        public void ResetIndex() => __pbn__Index = null;
        private uint? __pbn__Index;

        [global::ProtoBuf.ProtoMember(6, Name = @"extra_lineup_type")]
        public ExtraLineupType ExtraLineupType
        {
            get => __pbn__ExtraLineupType.GetValueOrDefault();
            set => __pbn__ExtraLineupType = value;
        }
        public bool ShouldSerializeExtraLineupType() => __pbn__ExtraLineupType != null;
        public void ResetExtraLineupType() => __pbn__ExtraLineupType = null;
        private ExtraLineupType? __pbn__ExtraLineupType;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class JoinLineupScRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"retcode")]
        public uint Retcode
        {
            get => __pbn__Retcode.GetValueOrDefault();
            set => __pbn__Retcode = value;
        }
        public bool ShouldSerializeRetcode() => __pbn__Retcode != null;
        public void ResetRetcode() => __pbn__Retcode = null;
        private uint? __pbn__Retcode;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class QuitLineupCsReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"avatar_id")]
        public uint AvatarId
        {
            get => __pbn__AvatarId.GetValueOrDefault();
            set => __pbn__AvatarId = value;
        }
        public bool ShouldSerializeAvatarId() => __pbn__AvatarId != null;
        public void ResetAvatarId() => __pbn__AvatarId = null;
        private uint? __pbn__AvatarId;

        [global::ProtoBuf.ProtoMember(2, Name = @"is_virtual")]
        public bool IsVirtual
        {
            get => __pbn__IsVirtual.GetValueOrDefault();
            set => __pbn__IsVirtual = value;
        }
        public bool ShouldSerializeIsVirtual() => __pbn__IsVirtual != null;
        public void ResetIsVirtual() => __pbn__IsVirtual = null;
        private bool? __pbn__IsVirtual;

        [global::ProtoBuf.ProtoMember(3, Name = @"plane_id")]
        public uint PlaneId
        {
            get => __pbn__PlaneId.GetValueOrDefault();
            set => __pbn__PlaneId = value;
        }
        public bool ShouldSerializePlaneId() => __pbn__PlaneId != null;
        public void ResetPlaneId() => __pbn__PlaneId = null;
        private uint? __pbn__PlaneId;

        [global::ProtoBuf.ProtoMember(4, Name = @"index")]
        public uint Index
        {
            get => __pbn__Index.GetValueOrDefault();
            set => __pbn__Index = value;
        }
        public bool ShouldSerializeIndex() => __pbn__Index != null;
        public void ResetIndex() => __pbn__Index = null;
        private uint? __pbn__Index;

        [global::ProtoBuf.ProtoMember(5, Name = @"extra_lineup_type")]
        public ExtraLineupType ExtraLineupType
        {
            get => __pbn__ExtraLineupType.GetValueOrDefault();
            set => __pbn__ExtraLineupType = value;
        }
        public bool ShouldSerializeExtraLineupType() => __pbn__ExtraLineupType != null;
        public void ResetExtraLineupType() => __pbn__ExtraLineupType = null;
        private ExtraLineupType? __pbn__ExtraLineupType;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class QuitLineupScRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"retcode")]
        public uint Retcode
        {
            get => __pbn__Retcode.GetValueOrDefault();
            set => __pbn__Retcode = value;
        }
        public bool ShouldSerializeRetcode() => __pbn__Retcode != null;
        public void ResetRetcode() => __pbn__Retcode = null;
        private uint? __pbn__Retcode;

        [global::ProtoBuf.ProtoMember(2, Name = @"avatar_id")]
        public uint AvatarId
        {
            get => __pbn__AvatarId.GetValueOrDefault();
            set => __pbn__AvatarId = value;
        }
        public bool ShouldSerializeAvatarId() => __pbn__AvatarId != null;
        public void ResetAvatarId() => __pbn__AvatarId = null;
        private uint? __pbn__AvatarId;

        [global::ProtoBuf.ProtoMember(3, Name = @"is_mainline")]
        public bool IsMainline
        {
            get => __pbn__IsMainline.GetValueOrDefault();
            set => __pbn__IsMainline = value;
        }
        public bool ShouldSerializeIsMainline() => __pbn__IsMainline != null;
        public void ResetIsMainline() => __pbn__IsMainline = null;
        private bool? __pbn__IsMainline;

        [global::ProtoBuf.ProtoMember(4, Name = @"plane_id")]
        public uint PlaneId
        {
            get => __pbn__PlaneId.GetValueOrDefault();
            set => __pbn__PlaneId = value;
        }
        public bool ShouldSerializePlaneId() => __pbn__PlaneId != null;
        public void ResetPlaneId() => __pbn__PlaneId = null;
        private uint? __pbn__PlaneId;

        [global::ProtoBuf.ProtoMember(5, Name = @"is_virtual")]
        public bool IsVirtual
        {
            get => __pbn__IsVirtual.GetValueOrDefault();
            set => __pbn__IsVirtual = value;
        }
        public bool ShouldSerializeIsVirtual() => __pbn__IsVirtual != null;
        public void ResetIsVirtual() => __pbn__IsVirtual = null;
        private bool? __pbn__IsVirtual;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SwapLineupCsReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"is_virtual")]
        public bool IsVirtual
        {
            get => __pbn__IsVirtual.GetValueOrDefault();
            set => __pbn__IsVirtual = value;
        }
        public bool ShouldSerializeIsVirtual() => __pbn__IsVirtual != null;
        public void ResetIsVirtual() => __pbn__IsVirtual = null;
        private bool? __pbn__IsVirtual;

        [global::ProtoBuf.ProtoMember(2, Name = @"plane_id")]
        public uint PlaneId
        {
            get => __pbn__PlaneId.GetValueOrDefault();
            set => __pbn__PlaneId = value;
        }
        public bool ShouldSerializePlaneId() => __pbn__PlaneId != null;
        public void ResetPlaneId() => __pbn__PlaneId = null;
        private uint? __pbn__PlaneId;

        [global::ProtoBuf.ProtoMember(3, Name = @"src_slot")]
        public uint SrcSlot
        {
            get => __pbn__SrcSlot.GetValueOrDefault();
            set => __pbn__SrcSlot = value;
        }
        public bool ShouldSerializeSrcSlot() => __pbn__SrcSlot != null;
        public void ResetSrcSlot() => __pbn__SrcSlot = null;
        private uint? __pbn__SrcSlot;

        [global::ProtoBuf.ProtoMember(4, Name = @"dst_slot")]
        public uint DstSlot
        {
            get => __pbn__DstSlot.GetValueOrDefault();
            set => __pbn__DstSlot = value;
        }
        public bool ShouldSerializeDstSlot() => __pbn__DstSlot != null;
        public void ResetDstSlot() => __pbn__DstSlot = null;
        private uint? __pbn__DstSlot;

        [global::ProtoBuf.ProtoMember(5, Name = @"index")]
        public uint Index
        {
            get => __pbn__Index.GetValueOrDefault();
            set => __pbn__Index = value;
        }
        public bool ShouldSerializeIndex() => __pbn__Index != null;
        public void ResetIndex() => __pbn__Index = null;
        private uint? __pbn__Index;

        [global::ProtoBuf.ProtoMember(6, Name = @"extra_lineup_type")]
        public ExtraLineupType ExtraLineupType
        {
            get => __pbn__ExtraLineupType.GetValueOrDefault();
            set => __pbn__ExtraLineupType = value;
        }
        public bool ShouldSerializeExtraLineupType() => __pbn__ExtraLineupType != null;
        public void ResetExtraLineupType() => __pbn__ExtraLineupType = null;
        private ExtraLineupType? __pbn__ExtraLineupType;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SwapLineupScRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"retcode")]
        public uint Retcode
        {
            get => __pbn__Retcode.GetValueOrDefault();
            set => __pbn__Retcode = value;
        }
        public bool ShouldSerializeRetcode() => __pbn__Retcode != null;
        public void ResetRetcode() => __pbn__Retcode = null;
        private uint? __pbn__Retcode;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SyncLineupNotify : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"lineup")]
        public LineupInfo Lineup { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetLineupAvatarDataCsReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LineupAvatarData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"avatar_type")]
        public AvatarType AvatarType
        {
            get => __pbn__AvatarType.GetValueOrDefault();
            set => __pbn__AvatarType = value;
        }
        public bool ShouldSerializeAvatarType() => __pbn__AvatarType != null;
        public void ResetAvatarType() => __pbn__AvatarType = null;
        private AvatarType? __pbn__AvatarType;

        [global::ProtoBuf.ProtoMember(2, Name = @"id")]
        public uint Id
        {
            get => __pbn__Id.GetValueOrDefault();
            set => __pbn__Id = value;
        }
        public bool ShouldSerializeId() => __pbn__Id != null;
        public void ResetId() => __pbn__Id = null;
        private uint? __pbn__Id;

        [global::ProtoBuf.ProtoMember(3, Name = @"hp")]
        public uint Hp
        {
            get => __pbn__Hp.GetValueOrDefault();
            set => __pbn__Hp = value;
        }
        public bool ShouldSerializeHp() => __pbn__Hp != null;
        public void ResetHp() => __pbn__Hp = null;
        private uint? __pbn__Hp;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetLineupAvatarDataScRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"retcode")]
        public uint Retcode
        {
            get => __pbn__Retcode.GetValueOrDefault();
            set => __pbn__Retcode = value;
        }
        public bool ShouldSerializeRetcode() => __pbn__Retcode != null;
        public void ResetRetcode() => __pbn__Retcode = null;
        private uint? __pbn__Retcode;

        [global::ProtoBuf.ProtoMember(2, Name = @"avatar_data_list")]
        public global::System.Collections.Generic.List<LineupAvatarData> AvatarDataLists { get; } = new global::System.Collections.Generic.List<LineupAvatarData>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ChangeLineupLeaderCsReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"slot")]
        public uint Slot
        {
            get => __pbn__Slot.GetValueOrDefault();
            set => __pbn__Slot = value;
        }
        public bool ShouldSerializeSlot() => __pbn__Slot != null;
        public void ResetSlot() => __pbn__Slot = null;
        private uint? __pbn__Slot;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ChangeLineupLeaderScRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"retcode")]
        public uint Retcode
        {
            get => __pbn__Retcode.GetValueOrDefault();
            set => __pbn__Retcode = value;
        }
        public bool ShouldSerializeRetcode() => __pbn__Retcode != null;
        public void ResetRetcode() => __pbn__Retcode = null;
        private uint? __pbn__Retcode;

        [global::ProtoBuf.ProtoMember(2, Name = @"slot")]
        public uint Slot
        {
            get => __pbn__Slot.GetValueOrDefault();
            set => __pbn__Slot = value;
        }
        public bool ShouldSerializeSlot() => __pbn__Slot != null;
        public void ResetSlot() => __pbn__Slot = null;
        private uint? __pbn__Slot;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SwitchLineupIndexCsReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"index")]
        public uint Index
        {
            get => __pbn__Index.GetValueOrDefault();
            set => __pbn__Index = value;
        }
        public bool ShouldSerializeIndex() => __pbn__Index != null;
        public void ResetIndex() => __pbn__Index = null;
        private uint? __pbn__Index;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SwitchLineupIndexScRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"retcode")]
        public uint Retcode
        {
            get => __pbn__Retcode.GetValueOrDefault();
            set => __pbn__Retcode = value;
        }
        public bool ShouldSerializeRetcode() => __pbn__Retcode != null;
        public void ResetRetcode() => __pbn__Retcode = null;
        private uint? __pbn__Retcode;

        [global::ProtoBuf.ProtoMember(2, Name = @"index")]
        public uint Index
        {
            get => __pbn__Index.GetValueOrDefault();
            set => __pbn__Index = value;
        }
        public bool ShouldSerializeIndex() => __pbn__Index != null;
        public void ResetIndex() => __pbn__Index = null;
        private uint? __pbn__Index;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SetLineupNameCsReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name
        {
            get => __pbn__Name ?? "";
            set => __pbn__Name = value;
        }
        public bool ShouldSerializeName() => __pbn__Name != null;
        public void ResetName() => __pbn__Name = null;
        private string __pbn__Name;

        [global::ProtoBuf.ProtoMember(2, Name = @"index")]
        public uint Index
        {
            get => __pbn__Index.GetValueOrDefault();
            set => __pbn__Index = value;
        }
        public bool ShouldSerializeIndex() => __pbn__Index != null;
        public void ResetIndex() => __pbn__Index = null;
        private uint? __pbn__Index;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SetLineupNameScRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"retcode")]
        public uint Retcode
        {
            get => __pbn__Retcode.GetValueOrDefault();
            set => __pbn__Retcode = value;
        }
        public bool ShouldSerializeRetcode() => __pbn__Retcode != null;
        public void ResetRetcode() => __pbn__Retcode = null;
        private uint? __pbn__Retcode;

        [global::ProtoBuf.ProtoMember(2, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name
        {
            get => __pbn__Name ?? "";
            set => __pbn__Name = value;
        }
        public bool ShouldSerializeName() => __pbn__Name != null;
        public void ResetName() => __pbn__Name = null;
        private string __pbn__Name;

        [global::ProtoBuf.ProtoMember(3, Name = @"index")]
        public uint Index
        {
            get => __pbn__Index.GetValueOrDefault();
            set => __pbn__Index = value;
        }
        public bool ShouldSerializeIndex() => __pbn__Index != null;
        public void ResetIndex() => __pbn__Index = null;
        private uint? __pbn__Index;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetAllLineupDataCsReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetAllLineupDataScRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"retcode")]
        public uint Retcode
        {
            get => __pbn__Retcode.GetValueOrDefault();
            set => __pbn__Retcode = value;
        }
        public bool ShouldSerializeRetcode() => __pbn__Retcode != null;
        public void ResetRetcode() => __pbn__Retcode = null;
        private uint? __pbn__Retcode;

        [global::ProtoBuf.ProtoMember(2, Name = @"cur_index")]
        public uint CurIndex
        {
            get => __pbn__CurIndex.GetValueOrDefault();
            set => __pbn__CurIndex = value;
        }
        public bool ShouldSerializeCurIndex() => __pbn__CurIndex != null;
        public void ResetCurIndex() => __pbn__CurIndex = null;
        private uint? __pbn__CurIndex;

        [global::ProtoBuf.ProtoMember(3, Name = @"lineup_list")]
        public global::System.Collections.Generic.List<LineupInfo> LineupLists { get; } = new global::System.Collections.Generic.List<LineupInfo>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class VirtualLineupDestroyNotify : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"plane_id")]
        public uint PlaneId
        {
            get => __pbn__PlaneId.GetValueOrDefault();
            set => __pbn__PlaneId = value;
        }
        public bool ShouldSerializePlaneId() => __pbn__PlaneId != null;
        public void ResetPlaneId() => __pbn__PlaneId = null;
        private uint? __pbn__PlaneId;

    }

    [global::ProtoBuf.ProtoContract()]
    public enum CmdLineupType
    {
        CmdLineupTypeNone = 0,
        CmdGetStageLineupCsReq = 701,
        CmdGetStageLineupScRsp = 702,
        CmdGetCurLineupDataCsReq = 703,
        CmdGetCurLineupDataScRsp = 704,
        CmdJoinLineupCsReq = 705,
        CmdJoinLineupScRsp = 706,
        CmdQuitLineupCsReq = 707,
        CmdQuitLineupScRsp = 708,
        CmdSwapLineupCsReq = 709,
        CmdSwapLineupScRsp = 710,
        CmdSyncLineupNotify = 711,
        CmdGetLineupAvatarDataCsReq = 712,
        CmdGetLineupAvatarDataScRsp = 713,
        CmdChangeLineupLeaderCsReq = 714,
        CmdChangeLineupLeaderScRsp = 715,
        CmdSwitchLineupIndexCsReq = 716,
        CmdSwitchLineupIndexScRsp = 717,
        CmdSetLineupNameCsReq = 718,
        CmdSetLineupNameScRsp = 719,
        CmdGetAllLineupDataCsReq = 720,
        CmdGetAllLineupDataScRsp = 721,
        CmdVirtualLineupDestroyNotify = 722,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum ExtraLineupType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"LINEUP_NONE")]
        LineupNone = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"LINEUP_CHALLENGE")]
        LineupChallenge = 1,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
