// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: cs.mail.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace KazusaHSR.Protocol
{

    [global::ProtoBuf.ProtoContract()]
    public partial class GetMailCsReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"start")]
        public uint Start
        {
            get => __pbn__Start.GetValueOrDefault();
            set => __pbn__Start = value;
        }
        public bool ShouldSerializeStart() => __pbn__Start != null;
        public void ResetStart() => __pbn__Start = null;
        private uint? __pbn__Start;

        [global::ProtoBuf.ProtoMember(2, Name = @"stop")]
        public uint Stop
        {
            get => __pbn__Stop.GetValueOrDefault();
            set => __pbn__Stop = value;
        }
        public bool ShouldSerializeStop() => __pbn__Stop != null;
        public void ResetStop() => __pbn__Stop = null;
        private uint? __pbn__Stop;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MailItem : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"item_id")]
        public uint ItemId
        {
            get => __pbn__ItemId.GetValueOrDefault();
            set => __pbn__ItemId = value;
        }
        public bool ShouldSerializeItemId() => __pbn__ItemId != null;
        public void ResetItemId() => __pbn__ItemId = null;
        private uint? __pbn__ItemId;

        [global::ProtoBuf.ProtoMember(2, Name = @"level")]
        public uint Level
        {
            get => __pbn__Level.GetValueOrDefault();
            set => __pbn__Level = value;
        }
        public bool ShouldSerializeLevel() => __pbn__Level != null;
        public void ResetLevel() => __pbn__Level = null;
        private uint? __pbn__Level;

        [global::ProtoBuf.ProtoMember(3, Name = @"num")]
        public uint Num
        {
            get => __pbn__Num.GetValueOrDefault();
            set => __pbn__Num = value;
        }
        public bool ShouldSerializeNum() => __pbn__Num != null;
        public void ResetNum() => __pbn__Num = null;
        private uint? __pbn__Num;

        [global::ProtoBuf.ProtoMember(4, Name = @"rank")]
        public uint Rank
        {
            get => __pbn__Rank.GetValueOrDefault();
            set => __pbn__Rank = value;
        }
        public bool ShouldSerializeRank() => __pbn__Rank != null;
        public void ResetRank() => __pbn__Rank = null;
        private uint? __pbn__Rank;

        [global::ProtoBuf.ProtoMember(5, Name = @"promotion")]
        public uint Promotion
        {
            get => __pbn__Promotion.GetValueOrDefault();
            set => __pbn__Promotion = value;
        }
        public bool ShouldSerializePromotion() => __pbn__Promotion != null;
        public void ResetPromotion() => __pbn__Promotion = null;
        private uint? __pbn__Promotion;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MailAttachment : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"item_list")]
        public global::System.Collections.Generic.List<MailItem> ItemLists { get; } = new global::System.Collections.Generic.List<MailItem>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ClientMail : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public uint Id
        {
            get => __pbn__Id.GetValueOrDefault();
            set => __pbn__Id = value;
        }
        public bool ShouldSerializeId() => __pbn__Id != null;
        public void ResetId() => __pbn__Id = null;
        private uint? __pbn__Id;

        [global::ProtoBuf.ProtoMember(2, Name = @"template_id")]
        public uint TemplateId
        {
            get => __pbn__TemplateId.GetValueOrDefault();
            set => __pbn__TemplateId = value;
        }
        public bool ShouldSerializeTemplateId() => __pbn__TemplateId != null;
        public void ResetTemplateId() => __pbn__TemplateId = null;
        private uint? __pbn__TemplateId;

        [global::ProtoBuf.ProtoMember(3, Name = @"title")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Title
        {
            get => __pbn__Title ?? "";
            set => __pbn__Title = value;
        }
        public bool ShouldSerializeTitle() => __pbn__Title != null;
        public void ResetTitle() => __pbn__Title = null;
        private string __pbn__Title;

        [global::ProtoBuf.ProtoMember(4, Name = @"content")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Content
        {
            get => __pbn__Content ?? "";
            set => __pbn__Content = value;
        }
        public bool ShouldSerializeContent() => __pbn__Content != null;
        public void ResetContent() => __pbn__Content = null;
        private string __pbn__Content;

        [global::ProtoBuf.ProtoMember(5, Name = @"sender")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Sender
        {
            get => __pbn__Sender ?? "";
            set => __pbn__Sender = value;
        }
        public bool ShouldSerializeSender() => __pbn__Sender != null;
        public void ResetSender() => __pbn__Sender = null;
        private string __pbn__Sender;

        [global::ProtoBuf.ProtoMember(6, Name = @"time")]
        public uint Time
        {
            get => __pbn__Time.GetValueOrDefault();
            set => __pbn__Time = value;
        }
        public bool ShouldSerializeTime() => __pbn__Time != null;
        public void ResetTime() => __pbn__Time = null;
        private uint? __pbn__Time;

        [global::ProtoBuf.ProtoMember(7, Name = @"attachment")]
        public MailAttachment Attachment { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"is_read")]
        public bool IsRead
        {
            get => __pbn__IsRead.GetValueOrDefault();
            set => __pbn__IsRead = value;
        }
        public bool ShouldSerializeIsRead() => __pbn__IsRead != null;
        public void ResetIsRead() => __pbn__IsRead = null;
        private bool? __pbn__IsRead;

        [global::ProtoBuf.ProtoMember(9, Name = @"expire_time")]
        public uint ExpireTime
        {
            get => __pbn__ExpireTime.GetValueOrDefault();
            set => __pbn__ExpireTime = value;
        }
        public bool ShouldSerializeExpireTime() => __pbn__ExpireTime != null;
        public void ResetExpireTime() => __pbn__ExpireTime = null;
        private uint? __pbn__ExpireTime;

        [global::ProtoBuf.ProtoMember(10, Name = @"para_list")]
        public global::System.Collections.Generic.List<string> ParaLists { get; } = new global::System.Collections.Generic.List<string>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetMailScRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"retcode")]
        public uint Retcode
        {
            get => __pbn__Retcode.GetValueOrDefault();
            set => __pbn__Retcode = value;
        }
        public bool ShouldSerializeRetcode() => __pbn__Retcode != null;
        public void ResetRetcode() => __pbn__Retcode = null;
        private uint? __pbn__Retcode;

        [global::ProtoBuf.ProtoMember(2, Name = @"mail_list")]
        public global::System.Collections.Generic.List<ClientMail> MailLists { get; } = new global::System.Collections.Generic.List<ClientMail>();

        [global::ProtoBuf.ProtoMember(3, Name = @"is_end")]
        public bool IsEnd
        {
            get => __pbn__IsEnd.GetValueOrDefault();
            set => __pbn__IsEnd = value;
        }
        public bool ShouldSerializeIsEnd() => __pbn__IsEnd != null;
        public void ResetIsEnd() => __pbn__IsEnd = null;
        private bool? __pbn__IsEnd;

        [global::ProtoBuf.ProtoMember(4, Name = @"total_num")]
        public uint TotalNum
        {
            get => __pbn__TotalNum.GetValueOrDefault();
            set => __pbn__TotalNum = value;
        }
        public bool ShouldSerializeTotalNum() => __pbn__TotalNum != null;
        public void ResetTotalNum() => __pbn__TotalNum = null;
        private uint? __pbn__TotalNum;

        [global::ProtoBuf.ProtoMember(5, Name = @"start")]
        public uint Start
        {
            get => __pbn__Start.GetValueOrDefault();
            set => __pbn__Start = value;
        }
        public bool ShouldSerializeStart() => __pbn__Start != null;
        public void ResetStart() => __pbn__Start = null;
        private uint? __pbn__Start;

        [global::ProtoBuf.ProtoMember(6, Name = @"notice_mail_list")]
        public global::System.Collections.Generic.List<ClientMail> NoticeMailLists { get; } = new global::System.Collections.Generic.List<ClientMail>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MarkReadMailCsReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public uint Id
        {
            get => __pbn__Id.GetValueOrDefault();
            set => __pbn__Id = value;
        }
        public bool ShouldSerializeId() => __pbn__Id != null;
        public void ResetId() => __pbn__Id = null;
        private uint? __pbn__Id;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MarkReadMailScRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"retcode")]
        public uint Retcode
        {
            get => __pbn__Retcode.GetValueOrDefault();
            set => __pbn__Retcode = value;
        }
        public bool ShouldSerializeRetcode() => __pbn__Retcode != null;
        public void ResetRetcode() => __pbn__Retcode = null;
        private uint? __pbn__Retcode;

        [global::ProtoBuf.ProtoMember(2, Name = @"id")]
        public uint Id
        {
            get => __pbn__Id.GetValueOrDefault();
            set => __pbn__Id = value;
        }
        public bool ShouldSerializeId() => __pbn__Id != null;
        public void ResetId() => __pbn__Id = null;
        private uint? __pbn__Id;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DelMailCsReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id_list", IsPacked = true)]
        public uint[] IdLists { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DelMailScRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"retcode")]
        public uint Retcode
        {
            get => __pbn__Retcode.GetValueOrDefault();
            set => __pbn__Retcode = value;
        }
        public bool ShouldSerializeRetcode() => __pbn__Retcode != null;
        public void ResetRetcode() => __pbn__Retcode = null;
        private uint? __pbn__Retcode;

        [global::ProtoBuf.ProtoMember(2, Name = @"id_list", IsPacked = true)]
        public uint[] IdLists { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TakeMailAttachmentCsReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"mail_id_list", IsPacked = true)]
        public uint[] MailIdLists { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ClientMailAttachmentItem : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"mail_id")]
        public uint MailId
        {
            get => __pbn__MailId.GetValueOrDefault();
            set => __pbn__MailId = value;
        }
        public bool ShouldSerializeMailId() => __pbn__MailId != null;
        public void ResetMailId() => __pbn__MailId = null;
        private uint? __pbn__MailId;

        [global::ProtoBuf.ProtoMember(2, Name = @"item_id")]
        public uint ItemId
        {
            get => __pbn__ItemId.GetValueOrDefault();
            set => __pbn__ItemId = value;
        }
        public bool ShouldSerializeItemId() => __pbn__ItemId != null;
        public void ResetItemId() => __pbn__ItemId = null;
        private uint? __pbn__ItemId;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TakeMailAttachmentScRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"retcode")]
        public uint Retcode
        {
            get => __pbn__Retcode.GetValueOrDefault();
            set => __pbn__Retcode = value;
        }
        public bool ShouldSerializeRetcode() => __pbn__Retcode != null;
        public void ResetRetcode() => __pbn__Retcode = null;
        private uint? __pbn__Retcode;

        [global::ProtoBuf.ProtoMember(2, Name = @"succ_mail_id_list", IsPacked = true)]
        public uint[] SuccMailIdLists { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"attachment")]
        public MailAttachment Attachment { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"fail_mail_list")]
        public global::System.Collections.Generic.List<ClientMailAttachmentItem> FailMailLists { get; } = new global::System.Collections.Generic.List<ClientMailAttachmentItem>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class NewMailScNotify : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"mail_id_list", IsPacked = true)]
        public uint[] MailIdLists { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public enum CmdMailType
    {
        CmdMailTypeNone = 0,
        CmdGetMailCsReq = 801,
        CmdGetMailScRsp = 802,
        CmdMarkReadMailCsReq = 803,
        CmdMarkReadMailScRsp = 804,
        CmdDelMailCsReq = 805,
        CmdDelMailScRsp = 806,
        CmdTakeMailAttachmentCsReq = 807,
        CmdTakeMailAttachmentScRsp = 808,
        CmdNewMailScNotify = 809,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
