// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: cs.maze.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace KazusaHSR.Protocol
{

    [global::ProtoBuf.ProtoContract()]
    public partial class MazeFloor : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"floor_id")]
        public uint FloorId
        {
            get => __pbn__FloorId.GetValueOrDefault();
            set => __pbn__FloorId = value;
        }
        public bool ShouldSerializeFloorId() => __pbn__FloorId != null;
        public void ResetFloorId() => __pbn__FloorId = null;
        private uint? __pbn__FloorId;

        [global::ProtoBuf.ProtoMember(2, Name = @"scene")]
        public SceneInfo Scene { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Maze : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public uint Id
        {
            get => __pbn__Id.GetValueOrDefault();
            set => __pbn__Id = value;
        }
        public bool ShouldSerializeId() => __pbn__Id != null;
        public void ResetId() => __pbn__Id = null;
        private uint? __pbn__Id;

        [global::ProtoBuf.ProtoMember(2, Name = @"floor")]
        public MazeFloor Floor { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"map_entry_id")]
        public uint MapEntryId
        {
            get => __pbn__MapEntryId.GetValueOrDefault();
            set => __pbn__MapEntryId = value;
        }
        public bool ShouldSerializeMapEntryId() => __pbn__MapEntryId != null;
        public void ResetMapEntryId() => __pbn__MapEntryId = null;
        private uint? __pbn__MapEntryId;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MazeAvatar : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"avatar_id")]
        public uint AvatarId
        {
            get => __pbn__AvatarId.GetValueOrDefault();
            set => __pbn__AvatarId = value;
        }
        public bool ShouldSerializeAvatarId() => __pbn__AvatarId != null;
        public void ResetAvatarId() => __pbn__AvatarId = null;
        private uint? __pbn__AvatarId;

        [global::ProtoBuf.ProtoMember(2, Name = @"left_hp")]
        public uint LeftHp
        {
            get => __pbn__LeftHp.GetValueOrDefault();
            set => __pbn__LeftHp = value;
        }
        public bool ShouldSerializeLeftHp() => __pbn__LeftHp != null;
        public void ResetLeftHp() => __pbn__LeftHp = null;
        private uint? __pbn__LeftHp;

        [global::ProtoBuf.ProtoMember(3, Name = @"sp")]
        public uint Sp
        {
            get => __pbn__Sp.GetValueOrDefault();
            set => __pbn__Sp = value;
        }
        public bool ShouldSerializeSp() => __pbn__Sp != null;
        public void ResetSp() => __pbn__Sp = null;
        private uint? __pbn__Sp;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MazeMission : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"sub_mission_id")]
        public uint SubMissionId
        {
            get => __pbn__SubMissionId.GetValueOrDefault();
            set => __pbn__SubMissionId = value;
        }
        public bool ShouldSerializeSubMissionId() => __pbn__SubMissionId != null;
        public void ResetSubMissionId() => __pbn__SubMissionId = null;
        private uint? __pbn__SubMissionId;

        [global::ProtoBuf.ProtoMember(2, Name = @"status")]
        public MissionStatus Status
        {
            get => __pbn__Status.GetValueOrDefault();
            set => __pbn__Status = value;
        }
        public bool ShouldSerializeStatus() => __pbn__Status != null;
        public void ResetStatus() => __pbn__Status = null;
        private MissionStatus? __pbn__Status;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetMazeCsReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetMazeScRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"retcode")]
        public uint Retcode
        {
            get => __pbn__Retcode.GetValueOrDefault();
            set => __pbn__Retcode = value;
        }
        public bool ShouldSerializeRetcode() => __pbn__Retcode != null;
        public void ResetRetcode() => __pbn__Retcode = null;
        private uint? __pbn__Retcode;

        [global::ProtoBuf.ProtoMember(2, Name = @"maze_list")]
        public global::System.Collections.Generic.List<Maze> MazeLists { get; } = new global::System.Collections.Generic.List<Maze>();

        [global::ProtoBuf.ProtoMember(3, Name = @"cur_series_id")]
        public uint CurSeriesId
        {
            get => __pbn__CurSeriesId.GetValueOrDefault();
            set => __pbn__CurSeriesId = value;
        }
        public bool ShouldSerializeCurSeriesId() => __pbn__CurSeriesId != null;
        public void ResetCurSeriesId() => __pbn__CurSeriesId = null;
        private uint? __pbn__CurSeriesId;

        [global::ProtoBuf.ProtoMember(4, Name = @"finished_plane_list", IsPacked = true)]
        public uint[] FinishedPlaneLists { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"wait_plane_list", IsPacked = true)]
        public uint[] WaitPlaneLists { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"taken_reward_list", IsPacked = true)]
        public uint[] TakenRewardLists { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"avatar_list")]
        public global::System.Collections.Generic.List<MazeAvatar> AvatarLists { get; } = new global::System.Collections.Generic.List<MazeAvatar>();

        [global::ProtoBuf.ProtoMember(8, Name = @"chosen_ability_list", IsPacked = true)]
        public uint[] ChosenAbilityLists { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"candidate_ability_list", IsPacked = true)]
        public uint[] CandidateAbilityLists { get; set; }

        [global::ProtoBuf.ProtoMember(10, Name = @"maze_mission_list")]
        public global::System.Collections.Generic.List<MazeMission> MazeMissionLists { get; } = new global::System.Collections.Generic.List<MazeMission>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ChooseMazeSeriesCsReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"series_id")]
        public uint SeriesId
        {
            get => __pbn__SeriesId.GetValueOrDefault();
            set => __pbn__SeriesId = value;
        }
        public bool ShouldSerializeSeriesId() => __pbn__SeriesId != null;
        public void ResetSeriesId() => __pbn__SeriesId = null;
        private uint? __pbn__SeriesId;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ChooseMazeSeriesScRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"retcode")]
        public uint Retcode
        {
            get => __pbn__Retcode.GetValueOrDefault();
            set => __pbn__Retcode = value;
        }
        public bool ShouldSerializeRetcode() => __pbn__Retcode != null;
        public void ResetRetcode() => __pbn__Retcode = null;
        private uint? __pbn__Retcode;

        [global::ProtoBuf.ProtoMember(2, Name = @"series_id")]
        public uint SeriesId
        {
            get => __pbn__SeriesId.GetValueOrDefault();
            set => __pbn__SeriesId = value;
        }
        public bool ShouldSerializeSeriesId() => __pbn__SeriesId != null;
        public void ResetSeriesId() => __pbn__SeriesId = null;
        private uint? __pbn__SeriesId;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ChooseMazeAbilityCsReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"ability_id")]
        public uint AbilityId
        {
            get => __pbn__AbilityId.GetValueOrDefault();
            set => __pbn__AbilityId = value;
        }
        public bool ShouldSerializeAbilityId() => __pbn__AbilityId != null;
        public void ResetAbilityId() => __pbn__AbilityId = null;
        private uint? __pbn__AbilityId;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ChooseMazeAbilityScRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"retcode")]
        public uint Retcode
        {
            get => __pbn__Retcode.GetValueOrDefault();
            set => __pbn__Retcode = value;
        }
        public bool ShouldSerializeRetcode() => __pbn__Retcode != null;
        public void ResetRetcode() => __pbn__Retcode = null;
        private uint? __pbn__Retcode;

        [global::ProtoBuf.ProtoMember(2, Name = @"ability_list", IsPacked = true)]
        public uint[] AbilityLists { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class EnterMazeCsReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"plane_id")]
        public uint PlaneId
        {
            get => __pbn__PlaneId.GetValueOrDefault();
            set => __pbn__PlaneId = value;
        }
        public bool ShouldSerializePlaneId() => __pbn__PlaneId != null;
        public void ResetPlaneId() => __pbn__PlaneId = null;
        private uint? __pbn__PlaneId;

        [global::ProtoBuf.ProtoMember(2, Name = @"floor_id")]
        public uint FloorId
        {
            get => __pbn__FloorId.GetValueOrDefault();
            set => __pbn__FloorId = value;
        }
        public bool ShouldSerializeFloorId() => __pbn__FloorId != null;
        public void ResetFloorId() => __pbn__FloorId = null;
        private uint? __pbn__FloorId;

        [global::ProtoBuf.ProtoMember(3, Name = @"entry_id")]
        public uint EntryId
        {
            get => __pbn__EntryId.GetValueOrDefault();
            set => __pbn__EntryId = value;
        }
        public bool ShouldSerializeEntryId() => __pbn__EntryId != null;
        public void ResetEntryId() => __pbn__EntryId = null;
        private uint? __pbn__EntryId;

        [global::ProtoBuf.ProtoMember(4, Name = @"group_id")]
        public uint GroupId
        {
            get => __pbn__GroupId.GetValueOrDefault();
            set => __pbn__GroupId = value;
        }
        public bool ShouldSerializeGroupId() => __pbn__GroupId != null;
        public void ResetGroupId() => __pbn__GroupId = null;
        private uint? __pbn__GroupId;

        [global::ProtoBuf.ProtoMember(5, Name = @"config_id")]
        public uint ConfigId
        {
            get => __pbn__ConfigId.GetValueOrDefault();
            set => __pbn__ConfigId = value;
        }
        public bool ShouldSerializeConfigId() => __pbn__ConfigId != null;
        public void ResetConfigId() => __pbn__ConfigId = null;
        private uint? __pbn__ConfigId;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class EnterMazeScRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"retcode")]
        public uint Retcode
        {
            get => __pbn__Retcode.GetValueOrDefault();
            set => __pbn__Retcode = value;
        }
        public bool ShouldSerializeRetcode() => __pbn__Retcode != null;
        public void ResetRetcode() => __pbn__Retcode = null;
        private uint? __pbn__Retcode;

        [global::ProtoBuf.ProtoMember(2, Name = @"maze")]
        public Maze Maze { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MazeBuffScNotify : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"buff_id")]
        public uint BuffId
        {
            get => __pbn__BuffId.GetValueOrDefault();
            set => __pbn__BuffId = value;
        }
        public bool ShouldSerializeBuffId() => __pbn__BuffId != null;
        public void ResetBuffId() => __pbn__BuffId = null;
        private uint? __pbn__BuffId;

        [global::ProtoBuf.ProtoMember(2, Name = @"op")]
        public MazeBuffOp Op
        {
            get => __pbn__Op.GetValueOrDefault();
            set => __pbn__Op = value;
        }
        public bool ShouldSerializeOp() => __pbn__Op != null;
        public void ResetOp() => __pbn__Op = null;
        private MazeBuffOp? __pbn__Op;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CastMazeSkillCsReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"skill_id")]
        public uint SkillId
        {
            get => __pbn__SkillId.GetValueOrDefault();
            set => __pbn__SkillId = value;
        }
        public bool ShouldSerializeSkillId() => __pbn__SkillId != null;
        public void ResetSkillId() => __pbn__SkillId = null;
        private uint? __pbn__SkillId;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CastMazeSkillScRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"retcode")]
        public uint Retcode
        {
            get => __pbn__Retcode.GetValueOrDefault();
            set => __pbn__Retcode = value;
        }
        public bool ShouldSerializeRetcode() => __pbn__Retcode != null;
        public void ResetRetcode() => __pbn__Retcode = null;
        private uint? __pbn__Retcode;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MazePlaneEventScNotify : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"reward")]
        public RewardData Reward { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"drop_list")]
        public global::System.Collections.Generic.List<DropItem> DropLists { get; } = new global::System.Collections.Generic.List<DropItem>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class EnterMazeByServerScNotify : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"maze")]
        public Maze Maze { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MazePropState : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"group_id")]
        public uint GroupId
        {
            get => __pbn__GroupId.GetValueOrDefault();
            set => __pbn__GroupId = value;
        }
        public bool ShouldSerializeGroupId() => __pbn__GroupId != null;
        public void ResetGroupId() => __pbn__GroupId = null;
        private uint? __pbn__GroupId;

        [global::ProtoBuf.ProtoMember(2, Name = @"config_id")]
        public uint ConfigId
        {
            get => __pbn__ConfigId.GetValueOrDefault();
            set => __pbn__ConfigId = value;
        }
        public bool ShouldSerializeConfigId() => __pbn__ConfigId != null;
        public void ResetConfigId() => __pbn__ConfigId = null;
        private uint? __pbn__ConfigId;

        [global::ProtoBuf.ProtoMember(3, Name = @"state")]
        public uint State
        {
            get => __pbn__State.GetValueOrDefault();
            set => __pbn__State = value;
        }
        public bool ShouldSerializeState() => __pbn__State != null;
        public void ResetState() => __pbn__State = null;
        private uint? __pbn__State;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MazeGroup : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"group_id")]
        public uint GroupId
        {
            get => __pbn__GroupId.GetValueOrDefault();
            set => __pbn__GroupId = value;
        }
        public bool ShouldSerializeGroupId() => __pbn__GroupId != null;
        public void ResetGroupId() => __pbn__GroupId = null;
        private uint? __pbn__GroupId;

        [global::ProtoBuf.ProtoMember(2, Name = @"modify_time")]
        public uint ModifyTime
        {
            get => __pbn__ModifyTime.GetValueOrDefault();
            set => __pbn__ModifyTime = value;
        }
        public bool ShouldSerializeModifyTime() => __pbn__ModifyTime != null;
        public void ResetModifyTime() => __pbn__ModifyTime = null;
        private uint? __pbn__ModifyTime;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetMazeMapInfoCsReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"entry_id")]
        public uint EntryId
        {
            get => __pbn__EntryId.GetValueOrDefault();
            set => __pbn__EntryId = value;
        }
        public bool ShouldSerializeEntryId() => __pbn__EntryId != null;
        public void ResetEntryId() => __pbn__EntryId = null;
        private uint? __pbn__EntryId;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetMazeMapInfoScRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"retcode")]
        public uint Retcode
        {
            get => __pbn__Retcode.GetValueOrDefault();
            set => __pbn__Retcode = value;
        }
        public bool ShouldSerializeRetcode() => __pbn__Retcode != null;
        public void ResetRetcode() => __pbn__Retcode = null;
        private uint? __pbn__Retcode;

        [global::ProtoBuf.ProtoMember(2, Name = @"entry_id")]
        public uint EntryId
        {
            get => __pbn__EntryId.GetValueOrDefault();
            set => __pbn__EntryId = value;
        }
        public bool ShouldSerializeEntryId() => __pbn__EntryId != null;
        public void ResetEntryId() => __pbn__EntryId = null;
        private uint? __pbn__EntryId;

        [global::ProtoBuf.ProtoMember(3, Name = @"lighten_section_list", IsPacked = true)]
        public uint[] LightenSectionLists { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"maze_prop_list")]
        public global::System.Collections.Generic.List<MazePropState> MazePropLists { get; } = new global::System.Collections.Generic.List<MazePropState>();

        [global::ProtoBuf.ProtoMember(5, Name = @"maze_group_list")]
        public global::System.Collections.Generic.List<MazeGroup> MazeGroupLists { get; } = new global::System.Collections.Generic.List<MazeGroup>();

    }

    [global::ProtoBuf.ProtoContract()]
    public enum CmdMazeType
    {
        CmdMazeTypeNode = 0,
        CmdGetMazeCsReq = 1001,
        CmdGetMazeScRsp = 1002,
        CmdChooseMazeSeriesCsReq = 1003,
        CmdChooseMazeSeriesScRsp = 1004,
        CmdChooseMazeAbilityCsReq = 1005,
        CmdChooseMazeAbilityScRsp = 1006,
        CmdEnterMazeCsReq = 1007,
        CmdEnterMazeScRsp = 1008,
        CmdMazeBuffScNotify = 1011,
        CmdCastMazeSkillCsReq = 1012,
        CmdCastMazeSkillScRsp = 1013,
        CmdMazePlaneEventScNotify = 1014,
        CmdEnterMazeByServerScNotify = 1015,
        CmdGetMazeMapInfoCsReq = 1016,
        CmdGetMazeMapInfoScRsp = 1017,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum MazeBuffOp
    {
        [global::ProtoBuf.ProtoEnum(Name = @"MAZE_BUFF_OP_NONE")]
        MazeBuffOpNone = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"MAZE_BUFF_OP_ADD")]
        MazeBuffOpAdd = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"MAZE_BUFF_OP_DEL")]
        MazeBuffOpDel = 2,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
