// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: cs.mission.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace KazusaHSR.Protocol
{

    [global::ProtoBuf.ProtoContract()]
    public partial class GetMissionDataCsReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Mission : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public uint Id
        {
            get => __pbn__Id.GetValueOrDefault();
            set => __pbn__Id = value;
        }
        public bool ShouldSerializeId() => __pbn__Id != null;
        public void ResetId() => __pbn__Id = null;
        private uint? __pbn__Id;

        [global::ProtoBuf.ProtoMember(2, Name = @"status")]
        public MissionStatus Status
        {
            get => __pbn__Status.GetValueOrDefault();
            set => __pbn__Status = value;
        }
        public bool ShouldSerializeStatus() => __pbn__Status != null;
        public void ResetStatus() => __pbn__Status = null;
        private MissionStatus? __pbn__Status;

        [global::ProtoBuf.ProtoMember(3, Name = @"progress")]
        public uint Progress
        {
            get => __pbn__Progress.GetValueOrDefault();
            set => __pbn__Progress = value;
        }
        public bool ShouldSerializeProgress() => __pbn__Progress != null;
        public void ResetProgress() => __pbn__Progress = null;
        private uint? __pbn__Progress;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetMissionDataScRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"retcode")]
        public uint Retcode
        {
            get => __pbn__Retcode.GetValueOrDefault();
            set => __pbn__Retcode = value;
        }
        public bool ShouldSerializeRetcode() => __pbn__Retcode != null;
        public void ResetRetcode() => __pbn__Retcode = null;
        private uint? __pbn__Retcode;

        [global::ProtoBuf.ProtoMember(2, Name = @"mission_list")]
        public global::System.Collections.Generic.List<Mission> MissionLists { get; } = new global::System.Collections.Generic.List<Mission>();

        [global::ProtoBuf.ProtoMember(3, Name = @"finished_main_mission_id_list", IsPacked = true)]
        public uint[] FinishedMainMissionIdLists { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class FinishTalkMissionCsReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"talk_str")]
        [global::System.ComponentModel.DefaultValue("")]
        public string TalkStr
        {
            get => __pbn__TalkStr ?? "";
            set => __pbn__TalkStr = value;
        }
        public bool ShouldSerializeTalkStr() => __pbn__TalkStr != null;
        public void ResetTalkStr() => __pbn__TalkStr = null;
        private string __pbn__TalkStr;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class FinishTalkMissionScRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"retcode")]
        public uint Retcode
        {
            get => __pbn__Retcode.GetValueOrDefault();
            set => __pbn__Retcode = value;
        }
        public bool ShouldSerializeRetcode() => __pbn__Retcode != null;
        public void ResetRetcode() => __pbn__Retcode = null;
        private uint? __pbn__Retcode;

        [global::ProtoBuf.ProtoMember(2, Name = @"talk_str")]
        [global::System.ComponentModel.DefaultValue("")]
        public string TalkStr
        {
            get => __pbn__TalkStr ?? "";
            set => __pbn__TalkStr = value;
        }
        public bool ShouldSerializeTalkStr() => __pbn__TalkStr != null;
        public void ResetTalkStr() => __pbn__TalkStr = null;
        private string __pbn__TalkStr;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MissionRewardScNotify : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"main_mission_id")]
        public uint MainMissionId
        {
            get => __pbn__MainMissionId.GetValueOrDefault();
            set => __pbn__MainMissionId = value;
        }
        public bool ShouldSerializeMainMissionId() => __pbn__MainMissionId != null;
        public void ResetMainMissionId() => __pbn__MainMissionId = null;
        private uint? __pbn__MainMissionId;

        [global::ProtoBuf.ProtoMember(2, Name = @"reward")]
        public RewardData Reward { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SyncTaskCsReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"key")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Key
        {
            get => __pbn__Key ?? "";
            set => __pbn__Key = value;
        }
        public bool ShouldSerializeKey() => __pbn__Key != null;
        public void ResetKey() => __pbn__Key = null;
        private string __pbn__Key;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SyncTaskScRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"retcode")]
        public uint Retcode
        {
            get => __pbn__Retcode.GetValueOrDefault();
            set => __pbn__Retcode = value;
        }
        public bool ShouldSerializeRetcode() => __pbn__Retcode != null;
        public void ResetRetcode() => __pbn__Retcode = null;
        private uint? __pbn__Retcode;

        [global::ProtoBuf.ProtoMember(2, Name = @"key")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Key
        {
            get => __pbn__Key ?? "";
            set => __pbn__Key = value;
        }
        public bool ShouldSerializeKey() => __pbn__Key != null;
        public void ResetKey() => __pbn__Key = null;
        private string __pbn__Key;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DailyTask : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"main_mission_id")]
        public uint MainMissionId
        {
            get => __pbn__MainMissionId.GetValueOrDefault();
            set => __pbn__MainMissionId = value;
        }
        public bool ShouldSerializeMainMissionId() => __pbn__MainMissionId != null;
        public void ResetMainMissionId() => __pbn__MainMissionId = null;
        private uint? __pbn__MainMissionId;

        [global::ProtoBuf.ProtoMember(2, Name = @"is_finished")]
        public bool IsFinished
        {
            get => __pbn__IsFinished.GetValueOrDefault();
            set => __pbn__IsFinished = value;
        }
        public bool ShouldSerializeIsFinished() => __pbn__IsFinished != null;
        public void ResetIsFinished() => __pbn__IsFinished = null;
        private bool? __pbn__IsFinished;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DailyTaskDataScNotify : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"is_taken_extra_reward")]
        public bool IsTakenExtraReward
        {
            get => __pbn__IsTakenExtraReward.GetValueOrDefault();
            set => __pbn__IsTakenExtraReward = value;
        }
        public bool ShouldSerializeIsTakenExtraReward() => __pbn__IsTakenExtraReward != null;
        public void ResetIsTakenExtraReward() => __pbn__IsTakenExtraReward = null;
        private bool? __pbn__IsTakenExtraReward;

        [global::ProtoBuf.ProtoMember(2, Name = @"finished_num")]
        public uint FinishedNum
        {
            get => __pbn__FinishedNum.GetValueOrDefault();
            set => __pbn__FinishedNum = value;
        }
        public bool ShouldSerializeFinishedNum() => __pbn__FinishedNum != null;
        public void ResetFinishedNum() => __pbn__FinishedNum = null;
        private uint? __pbn__FinishedNum;

        [global::ProtoBuf.ProtoMember(3, Name = @"daily_task_list")]
        public global::System.Collections.Generic.List<DailyTask> DailyTaskLists { get; } = new global::System.Collections.Generic.List<DailyTask>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TakeDailyTaskExtraRewardCsReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TakeDailyTaskExtraRewardScRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"retcode")]
        public uint Retcode
        {
            get => __pbn__Retcode.GetValueOrDefault();
            set => __pbn__Retcode = value;
        }
        public bool ShouldSerializeRetcode() => __pbn__Retcode != null;
        public void ResetRetcode() => __pbn__Retcode = null;
        private uint? __pbn__Retcode;

        [global::ProtoBuf.ProtoMember(2, Name = @"reward")]
        public RewardData Reward { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DailyTaskRewardScNotify : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"count")]
        public uint Count
        {
            get => __pbn__Count.GetValueOrDefault();
            set => __pbn__Count = value;
        }
        public bool ShouldSerializeCount() => __pbn__Count != null;
        public void ResetCount() => __pbn__Count = null;
        private uint? __pbn__Count;

        [global::ProtoBuf.ProtoMember(2, Name = @"reward")]
        public RewardData Reward { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MissionGroupWarnScNotify : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"group_id_list", IsPacked = true)]
        public uint[] GroupIdLists { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class FinishCosumeItemMissionCsReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"sub_mission_id")]
        public uint SubMissionId
        {
            get => __pbn__SubMissionId.GetValueOrDefault();
            set => __pbn__SubMissionId = value;
        }
        public bool ShouldSerializeSubMissionId() => __pbn__SubMissionId != null;
        public void ResetSubMissionId() => __pbn__SubMissionId = null;
        private uint? __pbn__SubMissionId;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class FinishCosumeItemMissionScRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"retcode")]
        public uint Retcode
        {
            get => __pbn__Retcode.GetValueOrDefault();
            set => __pbn__Retcode = value;
        }
        public bool ShouldSerializeRetcode() => __pbn__Retcode != null;
        public void ResetRetcode() => __pbn__Retcode = null;
        private uint? __pbn__Retcode;

        [global::ProtoBuf.ProtoMember(2, Name = @"sub_mission_id")]
        public uint SubMissionId
        {
            get => __pbn__SubMissionId.GetValueOrDefault();
            set => __pbn__SubMissionId = value;
        }
        public bool ShouldSerializeSubMissionId() => __pbn__SubMissionId != null;
        public void ResetSubMissionId() => __pbn__SubMissionId = null;
        private uint? __pbn__SubMissionId;

    }

    [global::ProtoBuf.ProtoContract()]
    public enum CmdMissionType
    {
        CmdMissionTypeNone = 0,
        CmdGetMissionDataCsReq = 1201,
        CmdGetMissionDataScRsp = 1202,
        CmdFinishTalkMissionCsReq = 1203,
        CmdFinishTalkMissionScRsp = 1204,
        CmdMissionRewardScNotify = 1205,
        CmdSyncTaskCsReq = 1206,
        CmdSyncTaskScRsp = 1207,
        CmdDailyTaskDataScNotify = 1208,
        CmdTakeDailyTaskExtraRewardCsReq = 1209,
        CmdTakeDailyTaskExtraRewardScRsp = 1210,
        CmdDailyTaskRewardScNotify = 1211,
        CmdMissionGroupWarnScNotify = 1212,
        CmdFinishCosumeItemMissionCsReq = 1213,
        CmdFinishCosumeItemMissionScRsp = 1214,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
