// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: cs.player.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace KazusaHSR.Protocol
{

    [global::ProtoBuf.ProtoContract()]
    public partial class PlayerLoginCsReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"platform")]
        public PlatformType Platform
        {
            get => __pbn__Platform.GetValueOrDefault();
            set => __pbn__Platform = value;
        }
        public bool ShouldSerializePlatform() => __pbn__Platform != null;
        public void ResetPlatform() => __pbn__Platform = null;
        private PlatformType? __pbn__Platform;

        [global::ProtoBuf.ProtoMember(2, Name = @"cps")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Cps
        {
            get => __pbn__Cps ?? "";
            set => __pbn__Cps = value;
        }
        public bool ShouldSerializeCps() => __pbn__Cps != null;
        public void ResetCps() => __pbn__Cps = null;
        private string __pbn__Cps;

        [global::ProtoBuf.ProtoMember(3, Name = @"device_uuid")]
        [global::System.ComponentModel.DefaultValue("")]
        public string DeviceUuid
        {
            get => __pbn__DeviceUuid ?? "";
            set => __pbn__DeviceUuid = value;
        }
        public bool ShouldSerializeDeviceUuid() => __pbn__DeviceUuid != null;
        public void ResetDeviceUuid() => __pbn__DeviceUuid = null;
        private string __pbn__DeviceUuid;

        [global::ProtoBuf.ProtoMember(4, Name = @"device_info")]
        [global::System.ComponentModel.DefaultValue("")]
        public string DeviceInfo
        {
            get => __pbn__DeviceInfo ?? "";
            set => __pbn__DeviceInfo = value;
        }
        public bool ShouldSerializeDeviceInfo() => __pbn__DeviceInfo != null;
        public void ResetDeviceInfo() => __pbn__DeviceInfo = null;
        private string __pbn__DeviceInfo;

        [global::ProtoBuf.ProtoMember(5, Name = @"system_info")]
        [global::System.ComponentModel.DefaultValue("")]
        public string SystemInfo
        {
            get => __pbn__SystemInfo ?? "";
            set => __pbn__SystemInfo = value;
        }
        public bool ShouldSerializeSystemInfo() => __pbn__SystemInfo != null;
        public void ResetSystemInfo() => __pbn__SystemInfo = null;
        private string __pbn__SystemInfo;

        [global::ProtoBuf.ProtoMember(6, Name = @"client_version")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ClientVersion
        {
            get => __pbn__ClientVersion ?? "";
            set => __pbn__ClientVersion = value;
        }
        public bool ShouldSerializeClientVersion() => __pbn__ClientVersion != null;
        public void ResetClientVersion() => __pbn__ClientVersion = null;
        private string __pbn__ClientVersion;

        [global::ProtoBuf.ProtoMember(7, Name = @"language")]
        public LanguageType Language
        {
            get => __pbn__Language.GetValueOrDefault();
            set => __pbn__Language = value;
        }
        public bool ShouldSerializeLanguage() => __pbn__Language != null;
        public void ResetLanguage() => __pbn__Language = null;
        private LanguageType? __pbn__Language;

        [global::ProtoBuf.ProtoMember(8, Name = @"last_server_packet_id")]
        public uint LastServerPacketId
        {
            get => __pbn__LastServerPacketId.GetValueOrDefault();
            set => __pbn__LastServerPacketId = value;
        }
        public bool ShouldSerializeLastServerPacketId() => __pbn__LastServerPacketId != null;
        public void ResetLastServerPacketId() => __pbn__LastServerPacketId = null;
        private uint? __pbn__LastServerPacketId;

        [global::ProtoBuf.ProtoMember(9, Name = @"check_sum_1")]
        [global::System.ComponentModel.DefaultValue("")]
        public string CheckSum1
        {
            get => __pbn__CheckSum1 ?? "";
            set => __pbn__CheckSum1 = value;
        }
        public bool ShouldSerializeCheckSum1() => __pbn__CheckSum1 != null;
        public void ResetCheckSum1() => __pbn__CheckSum1 = null;
        private string __pbn__CheckSum1;

        [global::ProtoBuf.ProtoMember(10, Name = @"check_sum_2")]
        [global::System.ComponentModel.DefaultValue("")]
        public string CheckSum2
        {
            get => __pbn__CheckSum2 ?? "";
            set => __pbn__CheckSum2 = value;
        }
        public bool ShouldSerializeCheckSum2() => __pbn__CheckSum2 != null;
        public void ResetCheckSum2() => __pbn__CheckSum2 = null;
        private string __pbn__CheckSum2;

        [global::ProtoBuf.ProtoMember(11, Name = @"signature")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Signature
        {
            get => __pbn__Signature ?? "";
            set => __pbn__Signature = value;
        }
        public bool ShouldSerializeSignature() => __pbn__Signature != null;
        public void ResetSignature() => __pbn__Signature = null;
        private string __pbn__Signature;

        [global::ProtoBuf.ProtoMember(12, Name = @"resolution")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Resolution
        {
            get => __pbn__Resolution ?? "";
            set => __pbn__Resolution = value;
        }
        public bool ShouldSerializeResolution() => __pbn__Resolution != null;
        public void ResetResolution() => __pbn__Resolution = null;
        private string __pbn__Resolution;

        [global::ProtoBuf.ProtoMember(13, Name = @"login_random")]
        public ulong LoginRandom
        {
            get => __pbn__LoginRandom.GetValueOrDefault();
            set => __pbn__LoginRandom = value;
        }
        public bool ShouldSerializeLoginRandom() => __pbn__LoginRandom != null;
        public void ResetLoginRandom() => __pbn__LoginRandom = null;
        private ulong? __pbn__LoginRandom;

        [global::ProtoBuf.ProtoMember(14, Name = @"system_language")]
        [global::System.ComponentModel.DefaultValue("")]
        public string SystemLanguage
        {
            get => __pbn__SystemLanguage ?? "";
            set => __pbn__SystemLanguage = value;
        }
        public bool ShouldSerializeSystemLanguage() => __pbn__SystemLanguage != null;
        public void ResetSystemLanguage() => __pbn__SystemLanguage = null;
        private string __pbn__SystemLanguage;

        [global::ProtoBuf.ProtoMember(15, Name = @"res_version")]
        public uint ResVersion
        {
            get => __pbn__ResVersion.GetValueOrDefault();
            set => __pbn__ResVersion = value;
        }
        public bool ShouldSerializeResVersion() => __pbn__ResVersion != null;
        public void ResetResVersion() => __pbn__ResVersion = null;
        private uint? __pbn__ResVersion;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PlayerLoginScRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"retcode")]
        public uint Retcode
        {
            get => __pbn__Retcode.GetValueOrDefault();
            set => __pbn__Retcode = value;
        }
        public bool ShouldSerializeRetcode() => __pbn__Retcode != null;
        public void ResetRetcode() => __pbn__Retcode = null;
        private uint? __pbn__Retcode;

        [global::ProtoBuf.ProtoMember(2, Name = @"is_new_player")]
        public bool IsNewPlayer
        {
            get => __pbn__IsNewPlayer.GetValueOrDefault();
            set => __pbn__IsNewPlayer = value;
        }
        public bool ShouldSerializeIsNewPlayer() => __pbn__IsNewPlayer != null;
        public void ResetIsNewPlayer() => __pbn__IsNewPlayer = null;
        private bool? __pbn__IsNewPlayer;

        [global::ProtoBuf.ProtoMember(3, Name = @"basic_info")]
        public PlayerBasicInfo BasicInfo { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"server_timestamp_ms")]
        public ulong ServerTimestampMs
        {
            get => __pbn__ServerTimestampMs.GetValueOrDefault();
            set => __pbn__ServerTimestampMs = value;
        }
        public bool ShouldSerializeServerTimestampMs() => __pbn__ServerTimestampMs != null;
        public void ResetServerTimestampMs() => __pbn__ServerTimestampMs = null;
        private ulong? __pbn__ServerTimestampMs;

        [global::ProtoBuf.ProtoMember(5, Name = @"stamina")]
        public uint Stamina
        {
            get => __pbn__Stamina.GetValueOrDefault();
            set => __pbn__Stamina = value;
        }
        public bool ShouldSerializeStamina() => __pbn__Stamina != null;
        public void ResetStamina() => __pbn__Stamina = null;
        private uint? __pbn__Stamina;

        [global::ProtoBuf.ProtoMember(6, Name = @"is_relay")]
        public bool IsRelay
        {
            get => __pbn__IsRelay.GetValueOrDefault();
            set => __pbn__IsRelay = value;
        }
        public bool ShouldSerializeIsRelay() => __pbn__IsRelay != null;
        public void ResetIsRelay() => __pbn__IsRelay = null;
        private bool? __pbn__IsRelay;

        [global::ProtoBuf.ProtoMember(7, Name = @"login_random")]
        public ulong LoginRandom
        {
            get => __pbn__LoginRandom.GetValueOrDefault();
            set => __pbn__LoginRandom = value;
        }
        public bool ShouldSerializeLoginRandom() => __pbn__LoginRandom != null;
        public void ResetLoginRandom() => __pbn__LoginRandom = null;
        private ulong? __pbn__LoginRandom;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PlayerLogoutCsReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PlayerGetTokenCsReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"channel_id")]
        public uint ChannelId
        {
            get => __pbn__ChannelId.GetValueOrDefault();
            set => __pbn__ChannelId = value;
        }
        public bool ShouldSerializeChannelId() => __pbn__ChannelId != null;
        public void ResetChannelId() => __pbn__ChannelId = null;
        private uint? __pbn__ChannelId;

        [global::ProtoBuf.ProtoMember(2, Name = @"account_uid")]
        [global::System.ComponentModel.DefaultValue("")]
        public string AccountUid
        {
            get => __pbn__AccountUid ?? "";
            set => __pbn__AccountUid = value;
        }
        public bool ShouldSerializeAccountUid() => __pbn__AccountUid != null;
        public void ResetAccountUid() => __pbn__AccountUid = null;
        private string __pbn__AccountUid;

        [global::ProtoBuf.ProtoMember(3, Name = @"token")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Token
        {
            get => __pbn__Token ?? "";
            set => __pbn__Token = value;
        }
        public bool ShouldSerializeToken() => __pbn__Token != null;
        public void ResetToken() => __pbn__Token = null;
        private string __pbn__Token;

        [global::ProtoBuf.ProtoMember(4, Name = @"uid")]
        public uint Uid
        {
            get => __pbn__Uid.GetValueOrDefault();
            set => __pbn__Uid = value;
        }
        public bool ShouldSerializeUid() => __pbn__Uid != null;
        public void ResetUid() => __pbn__Uid = null;
        private uint? __pbn__Uid;

        [global::ProtoBuf.ProtoMember(5, Name = @"device")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Device
        {
            get => __pbn__Device ?? "";
            set => __pbn__Device = value;
        }
        public bool ShouldSerializeDevice() => __pbn__Device != null;
        public void ResetDevice() => __pbn__Device = null;
        private string __pbn__Device;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PlayerGetTokenScRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"retcode")]
        public uint Retcode
        {
            get => __pbn__Retcode.GetValueOrDefault();
            set => __pbn__Retcode = value;
        }
        public bool ShouldSerializeRetcode() => __pbn__Retcode != null;
        public void ResetRetcode() => __pbn__Retcode = null;
        private uint? __pbn__Retcode;

        [global::ProtoBuf.ProtoMember(2, Name = @"uid")]
        public uint Uid
        {
            get => __pbn__Uid.GetValueOrDefault();
            set => __pbn__Uid = value;
        }
        public bool ShouldSerializeUid() => __pbn__Uid != null;
        public void ResetUid() => __pbn__Uid = null;
        private uint? __pbn__Uid;

        [global::ProtoBuf.ProtoMember(3, Name = @"black_info")]
        public BlackInfo BlackInfo { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"msg")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Msg
        {
            get => __pbn__Msg ?? "";
            set => __pbn__Msg = value;
        }
        public bool ShouldSerializeMsg() => __pbn__Msg != null;
        public void ResetMsg() => __pbn__Msg = null;
        private string __pbn__Msg;

        [global::ProtoBuf.ProtoMember(5, Name = @"secret_key_seed")]
        public ulong SecretKeySeed
        {
            get => __pbn__SecretKeySeed.GetValueOrDefault();
            set => __pbn__SecretKeySeed = value;
        }
        public bool ShouldSerializeSecretKeySeed() => __pbn__SecretKeySeed != null;
        public void ResetSecretKeySeed() => __pbn__SecretKeySeed = null;
        private ulong? __pbn__SecretKeySeed;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PlayerKeepAliveNotify : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GmTalkScNotify : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"msg")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Msg
        {
            get => __pbn__Msg ?? "";
            set => __pbn__Msg = value;
        }
        public bool ShouldSerializeMsg() => __pbn__Msg != null;
        public void ResetMsg() => __pbn__Msg = null;
        private string __pbn__Msg;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PlayerKickOutScNotify : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public KickType kick_type
        {
            get => __pbn__kick_type.GetValueOrDefault();
            set => __pbn__kick_type = value;
        }
        public bool ShouldSerializekick_type() => __pbn__kick_type != null;
        public void Resetkick_type() => __pbn__kick_type = null;
        private KickType? __pbn__kick_type;

        [global::ProtoBuf.ProtoMember(2, Name = @"black_info")]
        public BlackInfo BlackInfo { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum KickType
        {
            [global::ProtoBuf.ProtoEnum(Name = @"KICK_SQUEEZED")]
            KickSqueezed = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"KICK_BLACK")]
            KickBlack = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"KICK_CHANGE_PWD")]
            KickChangePwd = 2,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GmTalkCsReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"msg")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Msg
        {
            get => __pbn__Msg ?? "";
            set => __pbn__Msg = value;
        }
        public bool ShouldSerializeMsg() => __pbn__Msg != null;
        public void ResetMsg() => __pbn__Msg = null;
        private string __pbn__Msg;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GmTalkScRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"retcode")]
        public uint Retcode
        {
            get => __pbn__Retcode.GetValueOrDefault();
            set => __pbn__Retcode = value;
        }
        public bool ShouldSerializeRetcode() => __pbn__Retcode != null;
        public void ResetRetcode() => __pbn__Retcode = null;
        private uint? __pbn__Retcode;

        [global::ProtoBuf.ProtoMember(2, Name = @"retmsg")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Retmsg
        {
            get => __pbn__Retmsg ?? "";
            set => __pbn__Retmsg = value;
        }
        public bool ShouldSerializeRetmsg() => __pbn__Retmsg != null;
        public void ResetRetmsg() => __pbn__Retmsg = null;
        private string __pbn__Retmsg;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetStaminaExchangeCsReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetStaminaExchangeScRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"retcode")]
        public uint Retcode
        {
            get => __pbn__Retcode.GetValueOrDefault();
            set => __pbn__Retcode = value;
        }
        public bool ShouldSerializeRetcode() => __pbn__Retcode != null;
        public void ResetRetcode() => __pbn__Retcode = null;
        private uint? __pbn__Retcode;

        [global::ProtoBuf.ProtoMember(2, Name = @"next_recover_time")]
        public uint NextRecoverTime
        {
            get => __pbn__NextRecoverTime.GetValueOrDefault();
            set => __pbn__NextRecoverTime = value;
        }
        public bool ShouldSerializeNextRecoverTime() => __pbn__NextRecoverTime != null;
        public void ResetNextRecoverTime() => __pbn__NextRecoverTime = null;
        private uint? __pbn__NextRecoverTime;

        [global::ProtoBuf.ProtoMember(3, Name = @"exchange_times")]
        public uint ExchangeTimes
        {
            get => __pbn__ExchangeTimes.GetValueOrDefault();
            set => __pbn__ExchangeTimes = value;
        }
        public bool ShouldSerializeExchangeTimes() => __pbn__ExchangeTimes != null;
        public void ResetExchangeTimes() => __pbn__ExchangeTimes = null;
        private uint? __pbn__ExchangeTimes;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ExchangeStaminaCsReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ExchangeStaminaScRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"retcode")]
        public uint Retcode
        {
            get => __pbn__Retcode.GetValueOrDefault();
            set => __pbn__Retcode = value;
        }
        public bool ShouldSerializeRetcode() => __pbn__Retcode != null;
        public void ResetRetcode() => __pbn__Retcode = null;
        private uint? __pbn__Retcode;

        [global::ProtoBuf.ProtoMember(2, Name = @"stamina_add")]
        public uint StaminaAdd
        {
            get => __pbn__StaminaAdd.GetValueOrDefault();
            set => __pbn__StaminaAdd = value;
        }
        public bool ShouldSerializeStaminaAdd() => __pbn__StaminaAdd != null;
        public void ResetStaminaAdd() => __pbn__StaminaAdd = null;
        private uint? __pbn__StaminaAdd;

        [global::ProtoBuf.ProtoMember(3, Name = @"item_cost_list")]
        public global::System.Collections.Generic.List<ItemCost> ItemCostLists { get; } = new global::System.Collections.Generic.List<ItemCost>();

        [global::ProtoBuf.ProtoMember(4, Name = @"last_recover_time")]
        public uint LastRecoverTime
        {
            get => __pbn__LastRecoverTime.GetValueOrDefault();
            set => __pbn__LastRecoverTime = value;
        }
        public bool ShouldSerializeLastRecoverTime() => __pbn__LastRecoverTime != null;
        public void ResetLastRecoverTime() => __pbn__LastRecoverTime = null;
        private uint? __pbn__LastRecoverTime;

        [global::ProtoBuf.ProtoMember(5, Name = @"exchange_times")]
        public uint ExchangeTimes
        {
            get => __pbn__ExchangeTimes.GetValueOrDefault();
            set => __pbn__ExchangeTimes = value;
        }
        public bool ShouldSerializeExchangeTimes() => __pbn__ExchangeTimes != null;
        public void ResetExchangeTimes() => __pbn__ExchangeTimes = null;
        private uint? __pbn__ExchangeTimes;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetAuthkeyCsReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"auth_appid")]
        [global::System.ComponentModel.DefaultValue("")]
        public string AuthAppid
        {
            get => __pbn__AuthAppid ?? "";
            set => __pbn__AuthAppid = value;
        }
        public bool ShouldSerializeAuthAppid() => __pbn__AuthAppid != null;
        public void ResetAuthAppid() => __pbn__AuthAppid = null;
        private string __pbn__AuthAppid;

        [global::ProtoBuf.ProtoMember(2, Name = @"sign_type")]
        public uint SignType
        {
            get => __pbn__SignType.GetValueOrDefault();
            set => __pbn__SignType = value;
        }
        public bool ShouldSerializeSignType() => __pbn__SignType != null;
        public void ResetSignType() => __pbn__SignType = null;
        private uint? __pbn__SignType;

        [global::ProtoBuf.ProtoMember(3, Name = @"authkey_ver")]
        public uint AuthkeyVer
        {
            get => __pbn__AuthkeyVer.GetValueOrDefault();
            set => __pbn__AuthkeyVer = value;
        }
        public bool ShouldSerializeAuthkeyVer() => __pbn__AuthkeyVer != null;
        public void ResetAuthkeyVer() => __pbn__AuthkeyVer = null;
        private uint? __pbn__AuthkeyVer;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetAuthkeyScRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"retcode")]
        public uint Retcode
        {
            get => __pbn__Retcode.GetValueOrDefault();
            set => __pbn__Retcode = value;
        }
        public bool ShouldSerializeRetcode() => __pbn__Retcode != null;
        public void ResetRetcode() => __pbn__Retcode = null;
        private uint? __pbn__Retcode;

        [global::ProtoBuf.ProtoMember(2, Name = @"authkey")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Authkey
        {
            get => __pbn__Authkey ?? "";
            set => __pbn__Authkey = value;
        }
        public bool ShouldSerializeAuthkey() => __pbn__Authkey != null;
        public void ResetAuthkey() => __pbn__Authkey = null;
        private string __pbn__Authkey;

        [global::ProtoBuf.ProtoMember(3, Name = @"auth_appid")]
        [global::System.ComponentModel.DefaultValue("")]
        public string AuthAppid
        {
            get => __pbn__AuthAppid ?? "";
            set => __pbn__AuthAppid = value;
        }
        public bool ShouldSerializeAuthAppid() => __pbn__AuthAppid != null;
        public void ResetAuthAppid() => __pbn__AuthAppid = null;
        private string __pbn__AuthAppid;

        [global::ProtoBuf.ProtoMember(4, Name = @"sign_type")]
        public uint SignType
        {
            get => __pbn__SignType.GetValueOrDefault();
            set => __pbn__SignType = value;
        }
        public bool ShouldSerializeSignType() => __pbn__SignType != null;
        public void ResetSignType() => __pbn__SignType = null;
        private uint? __pbn__SignType;

        [global::ProtoBuf.ProtoMember(5, Name = @"authkey_ver")]
        public uint AuthkeyVer
        {
            get => __pbn__AuthkeyVer.GetValueOrDefault();
            set => __pbn__AuthkeyVer = value;
        }
        public bool ShouldSerializeAuthkeyVer() => __pbn__AuthkeyVer != null;
        public void ResetAuthkeyVer() => __pbn__AuthkeyVer = null;
        private uint? __pbn__AuthkeyVer;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RegionStopScNotify : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"stop_begin_time")]
        public uint StopBeginTime
        {
            get => __pbn__StopBeginTime.GetValueOrDefault();
            set => __pbn__StopBeginTime = value;
        }
        public bool ShouldSerializeStopBeginTime() => __pbn__StopBeginTime != null;
        public void ResetStopBeginTime() => __pbn__StopBeginTime = null;
        private uint? __pbn__StopBeginTime;

        [global::ProtoBuf.ProtoMember(2, Name = @"stop_end_time")]
        public uint StopEndTime
        {
            get => __pbn__StopEndTime.GetValueOrDefault();
            set => __pbn__StopEndTime = value;
        }
        public bool ShouldSerializeStopEndTime() => __pbn__StopEndTime != null;
        public void ResetStopEndTime() => __pbn__StopEndTime = null;
        private uint? __pbn__StopEndTime;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AntiAddictScNotify : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"msg_type")]
        public uint MsgType
        {
            get => __pbn__MsgType.GetValueOrDefault();
            set => __pbn__MsgType = value;
        }
        public bool ShouldSerializeMsgType() => __pbn__MsgType != null;
        public void ResetMsgType() => __pbn__MsgType = null;
        private uint? __pbn__MsgType;

        [global::ProtoBuf.ProtoMember(2, Name = @"msg")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Msg
        {
            get => __pbn__Msg ?? "";
            set => __pbn__Msg = value;
        }
        public bool ShouldSerializeMsg() => __pbn__Msg != null;
        public void ResetMsg() => __pbn__Msg = null;
        private string __pbn__Msg;

        [global::ProtoBuf.ProtoMember(3, Name = @"level")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Level
        {
            get => __pbn__Level ?? "";
            set => __pbn__Level = value;
        }
        public bool ShouldSerializeLevel() => __pbn__Level != null;
        public void ResetLevel() => __pbn__Level = null;
        private string __pbn__Level;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SetNicknameCsReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"nickname")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Nickname
        {
            get => __pbn__Nickname ?? "";
            set => __pbn__Nickname = value;
        }
        public bool ShouldSerializeNickname() => __pbn__Nickname != null;
        public void ResetNickname() => __pbn__Nickname = null;
        private string __pbn__Nickname;

        [global::ProtoBuf.ProtoMember(2, Name = @"is_modify")]
        public bool IsModify
        {
            get => __pbn__IsModify.GetValueOrDefault();
            set => __pbn__IsModify = value;
        }
        public bool ShouldSerializeIsModify() => __pbn__IsModify != null;
        public void ResetIsModify() => __pbn__IsModify = null;
        private bool? __pbn__IsModify;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SetNicknameScRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"retcode")]
        public uint Retcode
        {
            get => __pbn__Retcode.GetValueOrDefault();
            set => __pbn__Retcode = value;
        }
        public bool ShouldSerializeRetcode() => __pbn__Retcode != null;
        public void ResetRetcode() => __pbn__Retcode = null;
        private uint? __pbn__Retcode;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetLevelRewardTakenListCsReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetLevelRewardTakenListScRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"retcode")]
        public uint Retcode
        {
            get => __pbn__Retcode.GetValueOrDefault();
            set => __pbn__Retcode = value;
        }
        public bool ShouldSerializeRetcode() => __pbn__Retcode != null;
        public void ResetRetcode() => __pbn__Retcode = null;
        private uint? __pbn__Retcode;

        [global::ProtoBuf.ProtoMember(2, Name = @"taken_level_list", IsPacked = true)]
        public uint[] TakenLevelLists { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetLevelRewardCsReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"level")]
        public uint Level
        {
            get => __pbn__Level.GetValueOrDefault();
            set => __pbn__Level = value;
        }
        public bool ShouldSerializeLevel() => __pbn__Level != null;
        public void ResetLevel() => __pbn__Level = null;
        private uint? __pbn__Level;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetLevelRewardScRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"retcode")]
        public uint Retcode
        {
            get => __pbn__Retcode.GetValueOrDefault();
            set => __pbn__Retcode = value;
        }
        public bool ShouldSerializeRetcode() => __pbn__Retcode != null;
        public void ResetRetcode() => __pbn__Retcode = null;
        private uint? __pbn__Retcode;

        [global::ProtoBuf.ProtoMember(2, Name = @"reward")]
        public RewardData Reward { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SyncTimeCsReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"client_time_ms")]
        public ulong ClientTimeMs
        {
            get => __pbn__ClientTimeMs.GetValueOrDefault();
            set => __pbn__ClientTimeMs = value;
        }
        public bool ShouldSerializeClientTimeMs() => __pbn__ClientTimeMs != null;
        public void ResetClientTimeMs() => __pbn__ClientTimeMs = null;
        private ulong? __pbn__ClientTimeMs;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SyncTimeScRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"retcode")]
        public uint Retcode
        {
            get => __pbn__Retcode.GetValueOrDefault();
            set => __pbn__Retcode = value;
        }
        public bool ShouldSerializeRetcode() => __pbn__Retcode != null;
        public void ResetRetcode() => __pbn__Retcode = null;
        private uint? __pbn__Retcode;

        [global::ProtoBuf.ProtoMember(2, Name = @"client_time_ms")]
        public ulong ClientTimeMs
        {
            get => __pbn__ClientTimeMs.GetValueOrDefault();
            set => __pbn__ClientTimeMs = value;
        }
        public bool ShouldSerializeClientTimeMs() => __pbn__ClientTimeMs != null;
        public void ResetClientTimeMs() => __pbn__ClientTimeMs = null;
        private ulong? __pbn__ClientTimeMs;

        [global::ProtoBuf.ProtoMember(3, Name = @"server_time_ms")]
        public ulong ServerTimeMs
        {
            get => __pbn__ServerTimeMs.GetValueOrDefault();
            set => __pbn__ServerTimeMs = value;
        }
        public bool ShouldSerializeServerTimeMs() => __pbn__ServerTimeMs != null;
        public void ResetServerTimeMs() => __pbn__ServerTimeMs = null;
        private ulong? __pbn__ServerTimeMs;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SetLanguageCsReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"language")]
        public LanguageType Language
        {
            get => __pbn__Language.GetValueOrDefault();
            set => __pbn__Language = value;
        }
        public bool ShouldSerializeLanguage() => __pbn__Language != null;
        public void ResetLanguage() => __pbn__Language = null;
        private LanguageType? __pbn__Language;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SetLanguageScRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"retcode")]
        public uint Retcode
        {
            get => __pbn__Retcode.GetValueOrDefault();
            set => __pbn__Retcode = value;
        }
        public bool ShouldSerializeRetcode() => __pbn__Retcode != null;
        public void ResetRetcode() => __pbn__Retcode = null;
        private uint? __pbn__Retcode;

        [global::ProtoBuf.ProtoMember(2, Name = @"language")]
        public LanguageType Language
        {
            get => __pbn__Language.GetValueOrDefault();
            set => __pbn__Language = value;
        }
        public bool ShouldSerializeLanguage() => __pbn__Language != null;
        public void ResetLanguage() => __pbn__Language = null;
        private LanguageType? __pbn__Language;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AnnounceData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"config_id")]
        public uint ConfigId
        {
            get => __pbn__ConfigId.GetValueOrDefault();
            set => __pbn__ConfigId = value;
        }
        public bool ShouldSerializeConfigId() => __pbn__ConfigId != null;
        public void ResetConfigId() => __pbn__ConfigId = null;
        private uint? __pbn__ConfigId;

        [global::ProtoBuf.ProtoMember(2, Name = @"begin_time")]
        public uint BeginTime
        {
            get => __pbn__BeginTime.GetValueOrDefault();
            set => __pbn__BeginTime = value;
        }
        public bool ShouldSerializeBeginTime() => __pbn__BeginTime != null;
        public void ResetBeginTime() => __pbn__BeginTime = null;
        private uint? __pbn__BeginTime;

        [global::ProtoBuf.ProtoMember(3, Name = @"end_time")]
        public uint EndTime
        {
            get => __pbn__EndTime.GetValueOrDefault();
            set => __pbn__EndTime = value;
        }
        public bool ShouldSerializeEndTime() => __pbn__EndTime != null;
        public void ResetEndTime() => __pbn__EndTime = null;
        private uint? __pbn__EndTime;

        [global::ProtoBuf.ProtoMember(4, Name = @"center_system_text")]
        [global::System.ComponentModel.DefaultValue("")]
        public string CenterSystemText
        {
            get => __pbn__CenterSystemText ?? "";
            set => __pbn__CenterSystemText = value;
        }
        public bool ShouldSerializeCenterSystemText() => __pbn__CenterSystemText != null;
        public void ResetCenterSystemText() => __pbn__CenterSystemText = null;
        private string __pbn__CenterSystemText;

        [global::ProtoBuf.ProtoMember(5, Name = @"count_down_text")]
        [global::System.ComponentModel.DefaultValue("")]
        public string CountDownText
        {
            get => __pbn__CountDownText ?? "";
            set => __pbn__CountDownText = value;
        }
        public bool ShouldSerializeCountDownText() => __pbn__CountDownText != null;
        public void ResetCountDownText() => __pbn__CountDownText = null;
        private string __pbn__CountDownText;

        [global::ProtoBuf.ProtoMember(6, Name = @"dungeon_confirm_text")]
        [global::System.ComponentModel.DefaultValue("")]
        public string DungeonConfirmText
        {
            get => __pbn__DungeonConfirmText ?? "";
            set => __pbn__DungeonConfirmText = value;
        }
        public bool ShouldSerializeDungeonConfirmText() => __pbn__DungeonConfirmText != null;
        public void ResetDungeonConfirmText() => __pbn__DungeonConfirmText = null;
        private string __pbn__DungeonConfirmText;

        [global::ProtoBuf.ProtoMember(7, Name = @"center_system_frequency")]
        public uint CenterSystemFrequency
        {
            get => __pbn__CenterSystemFrequency.GetValueOrDefault();
            set => __pbn__CenterSystemFrequency = value;
        }
        public bool ShouldSerializeCenterSystemFrequency() => __pbn__CenterSystemFrequency != null;
        public void ResetCenterSystemFrequency() => __pbn__CenterSystemFrequency = null;
        private uint? __pbn__CenterSystemFrequency;

        [global::ProtoBuf.ProtoMember(8, Name = @"count_down_frequency")]
        public uint CountDownFrequency
        {
            get => __pbn__CountDownFrequency.GetValueOrDefault();
            set => __pbn__CountDownFrequency = value;
        }
        public bool ShouldSerializeCountDownFrequency() => __pbn__CountDownFrequency != null;
        public void ResetCountDownFrequency() => __pbn__CountDownFrequency = null;
        private uint? __pbn__CountDownFrequency;

        [global::ProtoBuf.ProtoMember(9, Name = @"is_center_system_last_5_every_minutes")]
        public bool IsCenterSystemLast5EveryMinutes
        {
            get => __pbn__IsCenterSystemLast5EveryMinutes.GetValueOrDefault();
            set => __pbn__IsCenterSystemLast5EveryMinutes = value;
        }
        public bool ShouldSerializeIsCenterSystemLast5EveryMinutes() => __pbn__IsCenterSystemLast5EveryMinutes != null;
        public void ResetIsCenterSystemLast5EveryMinutes() => __pbn__IsCenterSystemLast5EveryMinutes = null;
        private bool? __pbn__IsCenterSystemLast5EveryMinutes;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ServerAnnounceNotify : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"announce_data_list")]
        public global::System.Collections.Generic.List<AnnounceData> AnnounceDataLists { get; } = new global::System.Collections.Generic.List<AnnounceData>();

    }

    [global::ProtoBuf.ProtoContract()]
    public enum CmdPlayerType
    {
        CmdPlayerTypeNone = 0,
        CmdPlayerLoginCsReq = 1,
        CmdPlayerLoginScRsp = 2,
        CmdPlayerLogoutCsReq = 3,
        CmdPlayerLogoutScRsp = 4,
        CmdPlayerGetTokenCsReq = 5,
        CmdPlayerGetTokenScRsp = 6,
        CmdPlayerKeepAliveNotify = 7,
        CmdGmTalkScNotify = 8,
        CmdPlayerKickOutScNotify = 9,
        CmdGmTalkCsReq = 10,
        CmdGmTalkScRsp = 11,
        CmdGetStaminaExchangeCsReq = 12,
        CmdGetStaminaExchangeScRsp = 13,
        CmdExchangeStaminaCsReq = 14,
        CmdExchangeStaminaScRsp = 15,
        CmdGetAuthkeyCsReq = 16,
        CmdGetAuthkeyScRsp = 17,
        CmdRegionStopScNotify = 18,
        CmdAntiAddictScNotify = 19,
        CmdSetNicknameCsReq = 20,
        CmdSetNicknameScRsp = 21,
        CmdGetLevelRewardTakenListCsReq = 22,
        CmdGetLevelRewardTakenListScRsp = 23,
        CmdGetLevelRewardCsReq = 24,
        CmdGetLevelRewardScRsp = 25,
        CmdSyncTimeCsReq = 26,
        CmdSyncTimeScRsp = 27,
        CmdSetLanguageCsReq = 28,
        CmdSetLanguageScRsp = 29,
        CmdServerAnnounceNotify = 30,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum AuthkeySignType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"AUTHKEY_SIGN_TYPE_NONE")]
        AuthkeySignTypeNone = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"AUTHKEY_SIGN_TYPE_DEFAULT")]
        AuthkeySignTypeDefault = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"AUTHKEY_SIGN_TYPE_RSA")]
        AuthkeySignTypeRsa = 2,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
