// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: cs.plot.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace KazusaHSR.Protocol
{

    [global::ProtoBuf.ProtoContract()]
    public partial class FinishPlotCsReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"plot_id")]
        public uint PlotId
        {
            get => __pbn__PlotId.GetValueOrDefault();
            set => __pbn__PlotId = value;
        }
        public bool ShouldSerializePlotId() => __pbn__PlotId != null;
        public void ResetPlotId() => __pbn__PlotId = null;
        private uint? __pbn__PlotId;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class FinishPlotScRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"retcode")]
        public uint Retcode
        {
            get => __pbn__Retcode.GetValueOrDefault();
            set => __pbn__Retcode = value;
        }
        public bool ShouldSerializeRetcode() => __pbn__Retcode != null;
        public void ResetRetcode() => __pbn__Retcode = null;
        private uint? __pbn__Retcode;

        [global::ProtoBuf.ProtoMember(2, Name = @"plot_id")]
        public uint PlotId
        {
            get => __pbn__PlotId.GetValueOrDefault();
            set => __pbn__PlotId = value;
        }
        public bool ShouldSerializePlotId() => __pbn__PlotId != null;
        public void ResetPlotId() => __pbn__PlotId = null;
        private uint? __pbn__PlotId;

    }

    [global::ProtoBuf.ProtoContract()]
    public enum CmdPlotType
    {
        CmdPlotTypeNone = 0,
        CmdFinishPlotCsReq = 1101,
        CmdFinishPlotScRsp = 1102,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
