// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: cs.quest.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace KazusaHSR.Protocol
{

    [global::ProtoBuf.ProtoContract()]
    public partial class GetQuestDataCsReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Quest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public uint Id
        {
            get => __pbn__Id.GetValueOrDefault();
            set => __pbn__Id = value;
        }
        public bool ShouldSerializeId() => __pbn__Id != null;
        public void ResetId() => __pbn__Id = null;
        private uint? __pbn__Id;

        [global::ProtoBuf.ProtoMember(2, Name = @"status")]
        public QuestStatus Status
        {
            get => __pbn__Status.GetValueOrDefault();
            set => __pbn__Status = value;
        }
        public bool ShouldSerializeStatus() => __pbn__Status != null;
        public void ResetStatus() => __pbn__Status = null;
        private QuestStatus? __pbn__Status;

        [global::ProtoBuf.ProtoMember(3, Name = @"progress")]
        public uint Progress
        {
            get => __pbn__Progress.GetValueOrDefault();
            set => __pbn__Progress = value;
        }
        public bool ShouldSerializeProgress() => __pbn__Progress != null;
        public void ResetProgress() => __pbn__Progress = null;
        private uint? __pbn__Progress;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetQuestDataScRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"retcode")]
        public uint Retcode
        {
            get => __pbn__Retcode.GetValueOrDefault();
            set => __pbn__Retcode = value;
        }
        public bool ShouldSerializeRetcode() => __pbn__Retcode != null;
        public void ResetRetcode() => __pbn__Retcode = null;
        private uint? __pbn__Retcode;

        [global::ProtoBuf.ProtoMember(2, Name = @"quest_list")]
        public global::System.Collections.Generic.List<Quest> QuestLists { get; } = new global::System.Collections.Generic.List<Quest>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TakeQuestRewardCsReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"quest_id_list", IsPacked = true)]
        public uint[] QuestIdLists { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TakeQuestRewardScRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"retcode")]
        public uint Retcode
        {
            get => __pbn__Retcode.GetValueOrDefault();
            set => __pbn__Retcode = value;
        }
        public bool ShouldSerializeRetcode() => __pbn__Retcode != null;
        public void ResetRetcode() => __pbn__Retcode = null;
        private uint? __pbn__Retcode;

        [global::ProtoBuf.ProtoMember(2, Name = @"reward")]
        public RewardData Reward { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"succ_quest_id_list", IsPacked = true)]
        public uint[] SuccQuestIdLists { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public enum CmdQuestType
    {
        CmdQuestTypeNone = 0,
        CmdGetQuestDataCsReq = 901,
        CmdGetQuestDataScRsp = 902,
        CmdTakeQuestRewardCsReq = 903,
        CmdTakeQuestRewardScRsp = 904,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum QuestStatus
    {
        [global::ProtoBuf.ProtoEnum(Name = @"QUEST_NONE")]
        QuestNone = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"QUEST_DOING")]
        QuestDoing = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"QUEST_FINISH")]
        QuestFinish = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"QUEST_CLOSE")]
        QuestClose = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"QUEST_DELETE")]
        QuestDelete = 4,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
