// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: cs.stage.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace KazusaHSR.Protocol
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Stage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public uint Id
        {
            get => __pbn__Id.GetValueOrDefault();
            set => __pbn__Id = value;
        }
        public bool ShouldSerializeId() => __pbn__Id != null;
        public void ResetId() => __pbn__Id = null;
        private uint? __pbn__Id;

        [global::ProtoBuf.ProtoMember(2, Name = @"win_times")]
        public uint WinTimes
        {
            get => __pbn__WinTimes.GetValueOrDefault();
            set => __pbn__WinTimes = value;
        }
        public bool ShouldSerializeWinTimes() => __pbn__WinTimes != null;
        public void ResetWinTimes() => __pbn__WinTimes = null;
        private uint? __pbn__WinTimes;

        [global::ProtoBuf.ProtoMember(3, Name = @"challenge_value")]
        public uint ChallengeValue
        {
            get => __pbn__ChallengeValue.GetValueOrDefault();
            set => __pbn__ChallengeValue = value;
        }
        public bool ShouldSerializeChallengeValue() => __pbn__ChallengeValue != null;
        public void ResetChallengeValue() => __pbn__ChallengeValue = null;
        private uint? __pbn__ChallengeValue;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetStageDataCsReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"stage_id_list", IsPacked = true)]
        public uint[] StageIdLists { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetStageDataScRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"retcode")]
        public uint Retcode
        {
            get => __pbn__Retcode.GetValueOrDefault();
            set => __pbn__Retcode = value;
        }
        public bool ShouldSerializeRetcode() => __pbn__Retcode != null;
        public void ResetRetcode() => __pbn__Retcode = null;
        private uint? __pbn__Retcode;

        [global::ProtoBuf.ProtoMember(2, Name = @"stage_list")]
        public global::System.Collections.Generic.List<Stage> StageLists { get; } = new global::System.Collections.Generic.List<Stage>();

        [global::ProtoBuf.ProtoMember(3, Name = @"is_all")]
        public bool IsAll
        {
            get => __pbn__IsAll.GetValueOrDefault();
            set => __pbn__IsAll = value;
        }
        public bool ShouldSerializeIsAll() => __pbn__IsAll != null;
        public void ResetIsAll() => __pbn__IsAll = null;
        private bool? __pbn__IsAll;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class StageBeginCsReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"stage_id")]
        public uint StageId
        {
            get => __pbn__StageId.GetValueOrDefault();
            set => __pbn__StageId = value;
        }
        public bool ShouldSerializeStageId() => __pbn__StageId != null;
        public void ResetStageId() => __pbn__StageId = null;
        private uint? __pbn__StageId;

        [global::ProtoBuf.ProtoMember(2, Name = @"lineup_index")]
        public uint LineupIndex
        {
            get => __pbn__LineupIndex.GetValueOrDefault();
            set => __pbn__LineupIndex = value;
        }
        public bool ShouldSerializeLineupIndex() => __pbn__LineupIndex != null;
        public void ResetLineupIndex() => __pbn__LineupIndex = null;
        private uint? __pbn__LineupIndex;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class StageBeginScRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"retcode")]
        public uint Retcode
        {
            get => __pbn__Retcode.GetValueOrDefault();
            set => __pbn__Retcode = value;
        }
        public bool ShouldSerializeRetcode() => __pbn__Retcode != null;
        public void ResetRetcode() => __pbn__Retcode = null;
        private uint? __pbn__Retcode;

        [global::ProtoBuf.ProtoMember(2, Name = @"logic_random_seed")]
        public uint LogicRandomSeed
        {
            get => __pbn__LogicRandomSeed.GetValueOrDefault();
            set => __pbn__LogicRandomSeed = value;
        }
        public bool ShouldSerializeLogicRandomSeed() => __pbn__LogicRandomSeed != null;
        public void ResetLogicRandomSeed() => __pbn__LogicRandomSeed = null;
        private uint? __pbn__LogicRandomSeed;

        [global::ProtoBuf.ProtoMember(3, Name = @"stage_id")]
        public uint StageId
        {
            get => __pbn__StageId.GetValueOrDefault();
            set => __pbn__StageId = value;
        }
        public bool ShouldSerializeStageId() => __pbn__StageId != null;
        public void ResetStageId() => __pbn__StageId = null;
        private uint? __pbn__StageId;

        [global::ProtoBuf.ProtoMember(4, Name = @"battle_avatar_list")]
        public global::System.Collections.Generic.List<BattleAvatar> BattleAvatarLists { get; } = new global::System.Collections.Generic.List<BattleAvatar>();

    }

    [global::ProtoBuf.ProtoContract()]
    public enum CmdStageType
    {
        CmdStageTypeNone = 0,
        CmdGetStageDataCsReq = 201,
        CmdGetStageDataScRsp = 202,
        CmdStageBeginCsReq = 203,
        CmdStageBeginScRsp = 204,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
