// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: cs.shop.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace KazusaHSR.Protocol
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Shop : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"shop_id")]
        public uint ShopId
        {
            get => __pbn__ShopId.GetValueOrDefault();
            set => __pbn__ShopId = value;
        }
        public bool ShouldSerializeShopId() => __pbn__ShopId != null;
        public void ResetShopId() => __pbn__ShopId = null;
        private uint? __pbn__ShopId;

        [global::ProtoBuf.ProtoMember(2, Name = @"begin_time")]
        public uint BeginTime
        {
            get => __pbn__BeginTime.GetValueOrDefault();
            set => __pbn__BeginTime = value;
        }
        public bool ShouldSerializeBeginTime() => __pbn__BeginTime != null;
        public void ResetBeginTime() => __pbn__BeginTime = null;
        private uint? __pbn__BeginTime;

        [global::ProtoBuf.ProtoMember(3, Name = @"end_time")]
        public uint EndTime
        {
            get => __pbn__EndTime.GetValueOrDefault();
            set => __pbn__EndTime = value;
        }
        public bool ShouldSerializeEndTime() => __pbn__EndTime != null;
        public void ResetEndTime() => __pbn__EndTime = null;
        private uint? __pbn__EndTime;

        [global::ProtoBuf.ProtoMember(4, Name = @"goods_list")]
        public global::System.Collections.Generic.List<Goods> GoodsLists { get; } = new global::System.Collections.Generic.List<Goods>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Goods : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"goods_id")]
        public uint GoodsId
        {
            get => __pbn__GoodsId.GetValueOrDefault();
            set => __pbn__GoodsId = value;
        }
        public bool ShouldSerializeGoodsId() => __pbn__GoodsId != null;
        public void ResetGoodsId() => __pbn__GoodsId = null;
        private uint? __pbn__GoodsId;

        [global::ProtoBuf.ProtoMember(2, Name = @"buy_times")]
        public uint BuyTimes
        {
            get => __pbn__BuyTimes.GetValueOrDefault();
            set => __pbn__BuyTimes = value;
        }
        public bool ShouldSerializeBuyTimes() => __pbn__BuyTimes != null;
        public void ResetBuyTimes() => __pbn__BuyTimes = null;
        private uint? __pbn__BuyTimes;

        [global::ProtoBuf.ProtoMember(3, Name = @"begin_time")]
        public uint BeginTime
        {
            get => __pbn__BeginTime.GetValueOrDefault();
            set => __pbn__BeginTime = value;
        }
        public bool ShouldSerializeBeginTime() => __pbn__BeginTime != null;
        public void ResetBeginTime() => __pbn__BeginTime = null;
        private uint? __pbn__BeginTime;

        [global::ProtoBuf.ProtoMember(4, Name = @"end_time")]
        public uint EndTime
        {
            get => __pbn__EndTime.GetValueOrDefault();
            set => __pbn__EndTime = value;
        }
        public bool ShouldSerializeEndTime() => __pbn__EndTime != null;
        public void ResetEndTime() => __pbn__EndTime = null;
        private uint? __pbn__EndTime;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetShopListCsReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"shop_type")]
        public uint ShopType
        {
            get => __pbn__ShopType.GetValueOrDefault();
            set => __pbn__ShopType = value;
        }
        public bool ShouldSerializeShopType() => __pbn__ShopType != null;
        public void ResetShopType() => __pbn__ShopType = null;
        private uint? __pbn__ShopType;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetShopListScRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"retcode")]
        public uint Retcode
        {
            get => __pbn__Retcode.GetValueOrDefault();
            set => __pbn__Retcode = value;
        }
        public bool ShouldSerializeRetcode() => __pbn__Retcode != null;
        public void ResetRetcode() => __pbn__Retcode = null;
        private uint? __pbn__Retcode;

        [global::ProtoBuf.ProtoMember(2, Name = @"shop_list")]
        public global::System.Collections.Generic.List<Shop> ShopLists { get; } = new global::System.Collections.Generic.List<Shop>();

        [global::ProtoBuf.ProtoMember(3, Name = @"shop_type")]
        public uint ShopType
        {
            get => __pbn__ShopType.GetValueOrDefault();
            set => __pbn__ShopType = value;
        }
        public bool ShouldSerializeShopType() => __pbn__ShopType != null;
        public void ResetShopType() => __pbn__ShopType = null;
        private uint? __pbn__ShopType;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BuyGoodsCsReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"shop_id")]
        public uint ShopId
        {
            get => __pbn__ShopId.GetValueOrDefault();
            set => __pbn__ShopId = value;
        }
        public bool ShouldSerializeShopId() => __pbn__ShopId != null;
        public void ResetShopId() => __pbn__ShopId = null;
        private uint? __pbn__ShopId;

        [global::ProtoBuf.ProtoMember(2, Name = @"goods_id")]
        public uint GoodsId
        {
            get => __pbn__GoodsId.GetValueOrDefault();
            set => __pbn__GoodsId = value;
        }
        public bool ShouldSerializeGoodsId() => __pbn__GoodsId != null;
        public void ResetGoodsId() => __pbn__GoodsId = null;
        private uint? __pbn__GoodsId;

        [global::ProtoBuf.ProtoMember(3, Name = @"goods_num")]
        public uint GoodsNum
        {
            get => __pbn__GoodsNum.GetValueOrDefault();
            set => __pbn__GoodsNum = value;
        }
        public bool ShouldSerializeGoodsNum() => __pbn__GoodsNum != null;
        public void ResetGoodsNum() => __pbn__GoodsNum = null;
        private uint? __pbn__GoodsNum;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BuyGoodsScRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"retcode")]
        public uint Retcode
        {
            get => __pbn__Retcode.GetValueOrDefault();
            set => __pbn__Retcode = value;
        }
        public bool ShouldSerializeRetcode() => __pbn__Retcode != null;
        public void ResetRetcode() => __pbn__Retcode = null;
        private uint? __pbn__Retcode;

        [global::ProtoBuf.ProtoMember(2, Name = @"shop_id")]
        public uint ShopId
        {
            get => __pbn__ShopId.GetValueOrDefault();
            set => __pbn__ShopId = value;
        }
        public bool ShouldSerializeShopId() => __pbn__ShopId != null;
        public void ResetShopId() => __pbn__ShopId = null;
        private uint? __pbn__ShopId;

        [global::ProtoBuf.ProtoMember(3, Name = @"goods_id")]
        public uint GoodsId
        {
            get => __pbn__GoodsId.GetValueOrDefault();
            set => __pbn__GoodsId = value;
        }
        public bool ShouldSerializeGoodsId() => __pbn__GoodsId != null;
        public void ResetGoodsId() => __pbn__GoodsId = null;
        private uint? __pbn__GoodsId;

        [global::ProtoBuf.ProtoMember(4, Name = @"goods_buy_times")]
        public uint GoodsBuyTimes
        {
            get => __pbn__GoodsBuyTimes.GetValueOrDefault();
            set => __pbn__GoodsBuyTimes = value;
        }
        public bool ShouldSerializeGoodsBuyTimes() => __pbn__GoodsBuyTimes != null;
        public void ResetGoodsBuyTimes() => __pbn__GoodsBuyTimes = null;
        private uint? __pbn__GoodsBuyTimes;

    }

    [global::ProtoBuf.ProtoContract()]
    public enum CmdShopType
    {
        CmdShopTypeNone = 0,
        CmdGetShopListCsReq = 1501,
        CmdGetShopListScRsp = 1502,
        CmdBuyGoodsCsReq = 1503,
        CmdBuyGoodsScRsp = 1504,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
