// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: cs.sync.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace KazusaHSR.Protocol
{

    [global::ProtoBuf.ProtoContract()]
    public partial class BasicModuleSync : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"stamina")]
        public uint Stamina
        {
            get => __pbn__Stamina.GetValueOrDefault();
            set => __pbn__Stamina = value;
        }
        public bool ShouldSerializeStamina() => __pbn__Stamina != null;
        public void ResetStamina() => __pbn__Stamina = null;
        private uint? __pbn__Stamina;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AvatarSync : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"avatar_list")]
        public global::System.Collections.Generic.List<Avatar> AvatarLists { get; } = new global::System.Collections.Generic.List<Avatar>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MissionSync : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"mission_list")]
        public global::System.Collections.Generic.List<Mission> MissionLists { get; } = new global::System.Collections.Generic.List<Mission>();

        [global::ProtoBuf.ProtoMember(2, Name = @"finished_main_mission_id_list", IsPacked = true)]
        public uint[] FinishedMainMissionIdLists { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"del_mission_id_list", IsPacked = true)]
        public uint[] DelMissionIdLists { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"del_main_mission_id_list", IsPacked = true)]
        public uint[] DelMainMissionIdLists { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PlayerSyncScNotify : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"basic_info")]
        public PlayerBasicInfo BasicInfo { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"avatar_sync")]
        public AvatarSync AvatarSync { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"equipment_list")]
        public global::System.Collections.Generic.List<Equipment> EquipmentLists { get; } = new global::System.Collections.Generic.List<Equipment>();

        [global::ProtoBuf.ProtoMember(4, Name = @"del_equipment_list", IsPacked = true)]
        public uint[] DelEquipmentLists { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"material_list")]
        public global::System.Collections.Generic.List<Material> MaterialLists { get; } = new global::System.Collections.Generic.List<Material>();

        [global::ProtoBuf.ProtoMember(6, Name = @"quest_list")]
        public global::System.Collections.Generic.List<Quest> QuestLists { get; } = new global::System.Collections.Generic.List<Quest>();

        [global::ProtoBuf.ProtoMember(7, Name = @"mission_sync")]
        public MissionSync MissionSync { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"basic_module_sync")]
        public BasicModuleSync BasicModuleSync { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public enum CmdPlayerSyncType
    {
        CmdPlayerSyncNone = 0,
        CmdPlayerSyncScNotify = 601,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
