// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: cs.scene.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace KazusaHSR.Protocol
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Vector : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"x", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public int X
        {
            get => __pbn__X.GetValueOrDefault();
            set => __pbn__X = value;
        }
        public bool ShouldSerializeX() => __pbn__X != null;
        public void ResetX() => __pbn__X = null;
        private int? __pbn__X;

        [global::ProtoBuf.ProtoMember(2, Name = @"y", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public int Y
        {
            get => __pbn__Y.GetValueOrDefault();
            set => __pbn__Y = value;
        }
        public bool ShouldSerializeY() => __pbn__Y != null;
        public void ResetY() => __pbn__Y = null;
        private int? __pbn__Y;

        [global::ProtoBuf.ProtoMember(3, Name = @"z", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public int Z
        {
            get => __pbn__Z.GetValueOrDefault();
            set => __pbn__Z = value;
        }
        public bool ShouldSerializeZ() => __pbn__Z != null;
        public void ResetZ() => __pbn__Z = null;
        private int? __pbn__Z;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MotionInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"pos")]
        public Vector Pos { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"rot")]
        public Vector Rot { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SceneActorInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"uid")]
        public uint Uid
        {
            get => __pbn__Uid.GetValueOrDefault();
            set => __pbn__Uid = value;
        }
        public bool ShouldSerializeUid() => __pbn__Uid != null;
        public void ResetUid() => __pbn__Uid = null;
        private uint? __pbn__Uid;

        [global::ProtoBuf.ProtoMember(2, Name = @"avatar_type")]
        public AvatarType AvatarType
        {
            get => __pbn__AvatarType.GetValueOrDefault();
            set => __pbn__AvatarType = value;
        }
        public bool ShouldSerializeAvatarType() => __pbn__AvatarType != null;
        public void ResetAvatarType() => __pbn__AvatarType = null;
        private AvatarType? __pbn__AvatarType;

        [global::ProtoBuf.ProtoMember(3, Name = @"avatar_id")]
        public uint AvatarId
        {
            get => __pbn__AvatarId.GetValueOrDefault();
            set => __pbn__AvatarId = value;
        }
        public bool ShouldSerializeAvatarId() => __pbn__AvatarId != null;
        public void ResetAvatarId() => __pbn__AvatarId = null;
        private uint? __pbn__AvatarId;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SceneNpcMonsterInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"monster_id")]
        public uint MonsterId
        {
            get => __pbn__MonsterId.GetValueOrDefault();
            set => __pbn__MonsterId = value;
        }
        public bool ShouldSerializeMonsterId() => __pbn__MonsterId != null;
        public void ResetMonsterId() => __pbn__MonsterId = null;
        private uint? __pbn__MonsterId;

        [global::ProtoBuf.ProtoMember(2, Name = @"is_gen_monster")]
        public bool IsGenMonster
        {
            get => __pbn__IsGenMonster.GetValueOrDefault();
            set => __pbn__IsGenMonster = value;
        }
        public bool ShouldSerializeIsGenMonster() => __pbn__IsGenMonster != null;
        public void ResetIsGenMonster() => __pbn__IsGenMonster = null;
        private bool? __pbn__IsGenMonster;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SceneNpcInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"npc_id")]
        public uint NpcId
        {
            get => __pbn__NpcId.GetValueOrDefault();
            set => __pbn__NpcId = value;
        }
        public bool ShouldSerializeNpcId() => __pbn__NpcId != null;
        public void ResetNpcId() => __pbn__NpcId = null;
        private uint? __pbn__NpcId;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ScenePropInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"prop_id")]
        public uint PropId
        {
            get => __pbn__PropId.GetValueOrDefault();
            set => __pbn__PropId = value;
        }
        public bool ShouldSerializePropId() => __pbn__PropId != null;
        public void ResetPropId() => __pbn__PropId = null;
        private uint? __pbn__PropId;

        [global::ProtoBuf.ProtoMember(2, Name = @"prop_state")]
        public uint PropState
        {
            get => __pbn__PropState.GetValueOrDefault();
            set => __pbn__PropState = value;
        }
        public bool ShouldSerializePropState() => __pbn__PropState != null;
        public void ResetPropState() => __pbn__PropState = null;
        private uint? __pbn__PropState;

        [global::ProtoBuf.ProtoMember(3, Name = @"create_time_ms")]
        public ulong CreateTimeMs
        {
            get => __pbn__CreateTimeMs.GetValueOrDefault();
            set => __pbn__CreateTimeMs = value;
        }
        public bool ShouldSerializeCreateTimeMs() => __pbn__CreateTimeMs != null;
        public void ResetCreateTimeMs() => __pbn__CreateTimeMs = null;
        private ulong? __pbn__CreateTimeMs;

        [global::ProtoBuf.ProtoMember(4, Name = @"life_time_ms")]
        public uint LifeTimeMs
        {
            get => __pbn__LifeTimeMs.GetValueOrDefault();
            set => __pbn__LifeTimeMs = value;
        }
        public bool ShouldSerializeLifeTimeMs() => __pbn__LifeTimeMs != null;
        public void ResetLifeTimeMs() => __pbn__LifeTimeMs = null;
        private uint? __pbn__LifeTimeMs;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SceneEntityInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"entity_id")]
        public uint EntityId
        {
            get => __pbn__EntityId.GetValueOrDefault();
            set => __pbn__EntityId = value;
        }
        public bool ShouldSerializeEntityId() => __pbn__EntityId != null;
        public void ResetEntityId() => __pbn__EntityId = null;
        private uint? __pbn__EntityId;

        [global::ProtoBuf.ProtoMember(2, Name = @"motion")]
        public MotionInfo Motion { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"group_id")]
        public uint GroupId
        {
            get => __pbn__GroupId.GetValueOrDefault();
            set => __pbn__GroupId = value;
        }
        public bool ShouldSerializeGroupId() => __pbn__GroupId != null;
        public void ResetGroupId() => __pbn__GroupId = null;
        private uint? __pbn__GroupId;

        [global::ProtoBuf.ProtoMember(4, Name = @"inst_id")]
        public uint InstId
        {
            get => __pbn__InstId.GetValueOrDefault();
            set => __pbn__InstId = value;
        }
        public bool ShouldSerializeInstId() => __pbn__InstId != null;
        public void ResetInstId() => __pbn__InstId = null;
        private uint? __pbn__InstId;

        [global::ProtoBuf.ProtoMember(5, Name = @"actor")]
        public SceneActorInfo Actor
        {
            get => __pbn__entity.Is(5) ? ((SceneActorInfo)__pbn__entity.Object) : default;
            set => __pbn__entity = new global::ProtoBuf.DiscriminatedUnionObject(5, value);
        }
        public bool ShouldSerializeActor() => __pbn__entity.Is(5);
        public void ResetActor() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__entity, 5);

        private global::ProtoBuf.DiscriminatedUnionObject __pbn__entity;

        [global::ProtoBuf.ProtoMember(6, Name = @"npc_monster")]
        public SceneNpcMonsterInfo NpcMonster
        {
            get => __pbn__entity.Is(6) ? ((SceneNpcMonsterInfo)__pbn__entity.Object) : default;
            set => __pbn__entity = new global::ProtoBuf.DiscriminatedUnionObject(6, value);
        }
        public bool ShouldSerializeNpcMonster() => __pbn__entity.Is(6);
        public void ResetNpcMonster() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__entity, 6);

        [global::ProtoBuf.ProtoMember(7, Name = @"npc")]
        public SceneNpcInfo Npc
        {
            get => __pbn__entity.Is(7) ? ((SceneNpcInfo)__pbn__entity.Object) : default;
            set => __pbn__entity = new global::ProtoBuf.DiscriminatedUnionObject(7, value);
        }
        public bool ShouldSerializeNpc() => __pbn__entity.Is(7);
        public void ResetNpc() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__entity, 7);

        [global::ProtoBuf.ProtoMember(8, Name = @"prop")]
        public ScenePropInfo Prop
        {
            get => __pbn__entity.Is(8) ? ((ScenePropInfo)__pbn__entity.Object) : default;
            set => __pbn__entity = new global::ProtoBuf.DiscriminatedUnionObject(8, value);
        }
        public bool ShouldSerializeProp() => __pbn__entity.Is(8);
        public void ResetProp() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__entity, 8);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BuffInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"buff_id")]
        public uint BuffId
        {
            get => __pbn__BuffId.GetValueOrDefault();
            set => __pbn__BuffId = value;
        }
        public bool ShouldSerializeBuffId() => __pbn__BuffId != null;
        public void ResetBuffId() => __pbn__BuffId = null;
        private uint? __pbn__BuffId;

        [global::ProtoBuf.ProtoMember(2, Name = @"level")]
        public uint Level
        {
            get => __pbn__Level.GetValueOrDefault();
            set => __pbn__Level = value;
        }
        public bool ShouldSerializeLevel() => __pbn__Level != null;
        public void ResetLevel() => __pbn__Level = null;
        private uint? __pbn__Level;

        [global::ProtoBuf.ProtoMember(3, Name = @"add_time_ms")]
        public ulong AddTimeMs
        {
            get => __pbn__AddTimeMs.GetValueOrDefault();
            set => __pbn__AddTimeMs = value;
        }
        public bool ShouldSerializeAddTimeMs() => __pbn__AddTimeMs != null;
        public void ResetAddTimeMs() => __pbn__AddTimeMs = null;
        private ulong? __pbn__AddTimeMs;

        [global::ProtoBuf.ProtoMember(4, Name = @"life_time")]
        public float LifeTime
        {
            get => __pbn__LifeTime.GetValueOrDefault();
            set => __pbn__LifeTime = value;
        }
        public bool ShouldSerializeLifeTime() => __pbn__LifeTime != null;
        public void ResetLifeTime() => __pbn__LifeTime = null;
        private float? __pbn__LifeTime;

        [global::ProtoBuf.ProtoMember(5, Name = @"count")]
        public uint Count
        {
            get => __pbn__Count.GetValueOrDefault();
            set => __pbn__Count = value;
        }
        public bool ShouldSerializeCount() => __pbn__Count != null;
        public void ResetCount() => __pbn__Count = null;
        private uint? __pbn__Count;

        [global::ProtoBuf.ProtoMember(6, Name = @"caster_avatar_id")]
        public uint CasterAvatarId
        {
            get => __pbn__CasterAvatarId.GetValueOrDefault();
            set => __pbn__CasterAvatarId = value;
        }
        public bool ShouldSerializeCasterAvatarId() => __pbn__CasterAvatarId != null;
        public void ResetCasterAvatarId() => __pbn__CasterAvatarId = null;
        private uint? __pbn__CasterAvatarId;

        [global::ProtoBuf.ProtoMember(7, Name = @"dynamic_values")]
        [global::ProtoBuf.ProtoMap]
        public global::System.Collections.Generic.Dictionary<string, float> DynamicValues { get; } = new global::System.Collections.Generic.Dictionary<string, float>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SceneInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"map_id")]
        public uint MapId
        {
            get => __pbn__MapId.GetValueOrDefault();
            set => __pbn__MapId = value;
        }
        public bool ShouldSerializeMapId() => __pbn__MapId != null;
        public void ResetMapId() => __pbn__MapId = null;
        private uint? __pbn__MapId;

        [global::ProtoBuf.ProtoMember(2, Name = @"plane_id")]
        public uint PlaneId
        {
            get => __pbn__PlaneId.GetValueOrDefault();
            set => __pbn__PlaneId = value;
        }
        public bool ShouldSerializePlaneId() => __pbn__PlaneId != null;
        public void ResetPlaneId() => __pbn__PlaneId = null;
        private uint? __pbn__PlaneId;

        [global::ProtoBuf.ProtoMember(3, Name = @"floor_id")]
        public uint FloorId
        {
            get => __pbn__FloorId.GetValueOrDefault();
            set => __pbn__FloorId = value;
        }
        public bool ShouldSerializeFloorId() => __pbn__FloorId != null;
        public void ResetFloorId() => __pbn__FloorId = null;
        private uint? __pbn__FloorId;

        [global::ProtoBuf.ProtoMember(4, Name = @"entity_list")]
        public global::System.Collections.Generic.List<SceneEntityInfo> EntityLists { get; } = new global::System.Collections.Generic.List<SceneEntityInfo>();

        [global::ProtoBuf.ProtoMember(5, Name = @"lighten_section_list", IsPacked = true)]
        public uint[] LightenSectionLists { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"leader_entity_id")]
        public uint LeaderEntityId
        {
            get => __pbn__LeaderEntityId.GetValueOrDefault();
            set => __pbn__LeaderEntityId = value;
        }
        public bool ShouldSerializeLeaderEntityId() => __pbn__LeaderEntityId != null;
        public void ResetLeaderEntityId() => __pbn__LeaderEntityId = null;
        private uint? __pbn__LeaderEntityId;

        [global::ProtoBuf.ProtoMember(7, Name = @"entry_id")]
        public uint EntryId
        {
            get => __pbn__EntryId.GetValueOrDefault();
            set => __pbn__EntryId = value;
        }
        public bool ShouldSerializeEntryId() => __pbn__EntryId != null;
        public void ResetEntryId() => __pbn__EntryId = null;
        private uint? __pbn__EntryId;

        [global::ProtoBuf.ProtoMember(8, Name = @"env_buff_list")]
        public global::System.Collections.Generic.List<BuffInfo> EnvBuffLists { get; } = new global::System.Collections.Generic.List<BuffInfo>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class EntityMotion : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"entity_id")]
        public uint EntityId
        {
            get => __pbn__EntityId.GetValueOrDefault();
            set => __pbn__EntityId = value;
        }
        public bool ShouldSerializeEntityId() => __pbn__EntityId != null;
        public void ResetEntityId() => __pbn__EntityId = null;
        private uint? __pbn__EntityId;

        [global::ProtoBuf.ProtoMember(2, Name = @"motion")]
        public MotionInfo Motion { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SceneEntityMoveCsReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"entity_motion_list")]
        public global::System.Collections.Generic.List<EntityMotion> EntityMotionLists { get; } = new global::System.Collections.Generic.List<EntityMotion>();

        [global::ProtoBuf.ProtoMember(2, Name = @"entry_id")]
        public uint EntryId
        {
            get => __pbn__EntryId.GetValueOrDefault();
            set => __pbn__EntryId = value;
        }
        public bool ShouldSerializeEntryId() => __pbn__EntryId != null;
        public void ResetEntryId() => __pbn__EntryId = null;
        private uint? __pbn__EntryId;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SceneEntityMoveScRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"retcode")]
        public uint Retcode
        {
            get => __pbn__Retcode.GetValueOrDefault();
            set => __pbn__Retcode = value;
        }
        public bool ShouldSerializeRetcode() => __pbn__Retcode != null;
        public void ResetRetcode() => __pbn__Retcode = null;
        private uint? __pbn__Retcode;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SceneEntityMoveScNotify : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"entity_id")]
        public uint EntityId
        {
            get => __pbn__EntityId.GetValueOrDefault();
            set => __pbn__EntityId = value;
        }
        public bool ShouldSerializeEntityId() => __pbn__EntityId != null;
        public void ResetEntityId() => __pbn__EntityId = null;
        private uint? __pbn__EntityId;

        [global::ProtoBuf.ProtoMember(2, Name = @"motion")]
        public MotionInfo Motion { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class InteractPropCsReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"prop_entity_id")]
        public uint PropEntityId
        {
            get => __pbn__PropEntityId.GetValueOrDefault();
            set => __pbn__PropEntityId = value;
        }
        public bool ShouldSerializePropEntityId() => __pbn__PropEntityId != null;
        public void ResetPropEntityId() => __pbn__PropEntityId = null;
        private uint? __pbn__PropEntityId;

        [global::ProtoBuf.ProtoMember(2, Name = @"interact_id")]
        public uint InteractId
        {
            get => __pbn__InteractId.GetValueOrDefault();
            set => __pbn__InteractId = value;
        }
        public bool ShouldSerializeInteractId() => __pbn__InteractId != null;
        public void ResetInteractId() => __pbn__InteractId = null;
        private uint? __pbn__InteractId;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class InteractPropScRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"retcode")]
        public uint Retcode
        {
            get => __pbn__Retcode.GetValueOrDefault();
            set => __pbn__Retcode = value;
        }
        public bool ShouldSerializeRetcode() => __pbn__Retcode != null;
        public void ResetRetcode() => __pbn__Retcode = null;
        private uint? __pbn__Retcode;

        [global::ProtoBuf.ProtoMember(2, Name = @"prop_entity_id")]
        public uint PropEntityId
        {
            get => __pbn__PropEntityId.GetValueOrDefault();
            set => __pbn__PropEntityId = value;
        }
        public bool ShouldSerializePropEntityId() => __pbn__PropEntityId != null;
        public void ResetPropEntityId() => __pbn__PropEntityId = null;
        private uint? __pbn__PropEntityId;

        [global::ProtoBuf.ProtoMember(3, Name = @"prop_state")]
        public uint PropState
        {
            get => __pbn__PropState.GetValueOrDefault();
            set => __pbn__PropState = value;
        }
        public bool ShouldSerializePropState() => __pbn__PropState != null;
        public void ResetPropState() => __pbn__PropState = null;
        private uint? __pbn__PropState;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SceneCastSkillCsReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"cast_entity_id")]
        public uint CastEntityId
        {
            get => __pbn__CastEntityId.GetValueOrDefault();
            set => __pbn__CastEntityId = value;
        }
        public bool ShouldSerializeCastEntityId() => __pbn__CastEntityId != null;
        public void ResetCastEntityId() => __pbn__CastEntityId = null;
        private uint? __pbn__CastEntityId;

        [global::ProtoBuf.ProtoMember(2, Name = @"skill_index")]
        public uint SkillIndex
        {
            get => __pbn__SkillIndex.GetValueOrDefault();
            set => __pbn__SkillIndex = value;
        }
        public bool ShouldSerializeSkillIndex() => __pbn__SkillIndex != null;
        public void ResetSkillIndex() => __pbn__SkillIndex = null;
        private uint? __pbn__SkillIndex;

        [global::ProtoBuf.ProtoMember(3, Name = @"ability_target_entity_id")]
        public uint AbilityTargetEntityId
        {
            get => __pbn__AbilityTargetEntityId.GetValueOrDefault();
            set => __pbn__AbilityTargetEntityId = value;
        }
        public bool ShouldSerializeAbilityTargetEntityId() => __pbn__AbilityTargetEntityId != null;
        public void ResetAbilityTargetEntityId() => __pbn__AbilityTargetEntityId = null;
        private uint? __pbn__AbilityTargetEntityId;

        [global::ProtoBuf.ProtoMember(4, Name = @"hit_target_entity_id_list", IsPacked = true)]
        public uint[] HitTargetEntityIdLists { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"assist_monster_entity_id_list", IsPacked = true)]
        public uint[] AssistMonsterEntityIdLists { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"target_motion")]
        public MotionInfo TargetMotion { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SceneCastSkillScRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"retcode")]
        public uint Retcode
        {
            get => __pbn__Retcode.GetValueOrDefault();
            set => __pbn__Retcode = value;
        }
        public bool ShouldSerializeRetcode() => __pbn__Retcode != null;
        public void ResetRetcode() => __pbn__Retcode = null;
        private uint? __pbn__Retcode;

        [global::ProtoBuf.ProtoMember(2, Name = @"battle_info")]
        public SceneBattleInfo BattleInfo { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SceneEnterStageCsReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"stage_id")]
        public uint StageId
        {
            get => __pbn__StageId.GetValueOrDefault();
            set => __pbn__StageId = value;
        }
        public bool ShouldSerializeStageId() => __pbn__StageId != null;
        public void ResetStageId() => __pbn__StageId = null;
        private uint? __pbn__StageId;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SceneEnterStageScRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"retcode")]
        public uint Retcode
        {
            get => __pbn__Retcode.GetValueOrDefault();
            set => __pbn__Retcode = value;
        }
        public bool ShouldSerializeRetcode() => __pbn__Retcode != null;
        public void ResetRetcode() => __pbn__Retcode = null;
        private uint? __pbn__Retcode;

        [global::ProtoBuf.ProtoMember(2, Name = @"battle_info")]
        public SceneBattleInfo BattleInfo { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetCurSceneInfoCsReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetCurSceneInfoScRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"retcode")]
        public uint Retcode
        {
            get => __pbn__Retcode.GetValueOrDefault();
            set => __pbn__Retcode = value;
        }
        public bool ShouldSerializeRetcode() => __pbn__Retcode != null;
        public void ResetRetcode() => __pbn__Retcode = null;
        private uint? __pbn__Retcode;

        [global::ProtoBuf.ProtoMember(2, Name = @"scene")]
        public SceneInfo Scene { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SceneEntityUpdateScNotify : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"entity_list")]
        public global::System.Collections.Generic.List<SceneEntityInfo> EntityLists { get; } = new global::System.Collections.Generic.List<SceneEntityInfo>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SceneEntityDisappearScNotify : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"entity_id_list", IsPacked = true)]
        public uint[] EntityIdLists { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class WaitCustomStringCsReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(3, Name = @"custom_string")]
        [global::System.ComponentModel.DefaultValue("")]
        public string CustomString
        {
            get => __pbn__CustomString ?? "";
            set => __pbn__CustomString = value;
        }
        public bool ShouldSerializeCustomString() => __pbn__CustomString != null;
        public void ResetCustomString() => __pbn__CustomString = null;
        private string __pbn__CustomString;

        [global::ProtoBuf.ProtoMember(1, Name = @"prop_entity_id")]
        public uint PropEntityId
        {
            get => __pbn__key.Is(1) ? __pbn__key.UInt32 : default;
            set => __pbn__key = new global::ProtoBuf.DiscriminatedUnion32(1, value);
        }
        public bool ShouldSerializePropEntityId() => __pbn__key.Is(1);
        public void ResetPropEntityId() => global::ProtoBuf.DiscriminatedUnion32.Reset(ref __pbn__key, 1);

        private global::ProtoBuf.DiscriminatedUnion32 __pbn__key;

        [global::ProtoBuf.ProtoMember(2, Name = @"sub_mission_id")]
        public uint SubMissionId
        {
            get => __pbn__key.Is(2) ? __pbn__key.UInt32 : default;
            set => __pbn__key = new global::ProtoBuf.DiscriminatedUnion32(2, value);
        }
        public bool ShouldSerializeSubMissionId() => __pbn__key.Is(2);
        public void ResetSubMissionId() => global::ProtoBuf.DiscriminatedUnion32.Reset(ref __pbn__key, 2);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class WaitCustomStringScRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"retcode")]
        public uint Retcode
        {
            get => __pbn__Retcode.GetValueOrDefault();
            set => __pbn__Retcode = value;
        }
        public bool ShouldSerializeRetcode() => __pbn__Retcode != null;
        public void ResetRetcode() => __pbn__Retcode = null;
        private uint? __pbn__Retcode;

        [global::ProtoBuf.ProtoMember(4, Name = @"custom_string")]
        [global::System.ComponentModel.DefaultValue("")]
        public string CustomString
        {
            get => __pbn__CustomString ?? "";
            set => __pbn__CustomString = value;
        }
        public bool ShouldSerializeCustomString() => __pbn__CustomString != null;
        public void ResetCustomString() => __pbn__CustomString = null;
        private string __pbn__CustomString;

        [global::ProtoBuf.ProtoMember(2, Name = @"prop_entity_id")]
        public uint PropEntityId
        {
            get => __pbn__key.Is(2) ? __pbn__key.UInt32 : default;
            set => __pbn__key = new global::ProtoBuf.DiscriminatedUnion32(2, value);
        }
        public bool ShouldSerializePropEntityId() => __pbn__key.Is(2);
        public void ResetPropEntityId() => global::ProtoBuf.DiscriminatedUnion32.Reset(ref __pbn__key, 2);

        private global::ProtoBuf.DiscriminatedUnion32 __pbn__key;

        [global::ProtoBuf.ProtoMember(3, Name = @"sub_mission_id")]
        public uint SubMissionId
        {
            get => __pbn__key.Is(3) ? __pbn__key.UInt32 : default;
            set => __pbn__key = new global::ProtoBuf.DiscriminatedUnion32(3, value);
        }
        public bool ShouldSerializeSubMissionId() => __pbn__key.Is(3);
        public void ResetSubMissionId() => global::ProtoBuf.DiscriminatedUnion32.Reset(ref __pbn__key, 3);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SpringTransferCsReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"plane_id")]
        public uint PlaneId
        {
            get => __pbn__PlaneId.GetValueOrDefault();
            set => __pbn__PlaneId = value;
        }
        public bool ShouldSerializePlaneId() => __pbn__PlaneId != null;
        public void ResetPlaneId() => __pbn__PlaneId = null;
        private uint? __pbn__PlaneId;

        [global::ProtoBuf.ProtoMember(2, Name = @"floor_id")]
        public uint FloorId
        {
            get => __pbn__FloorId.GetValueOrDefault();
            set => __pbn__FloorId = value;
        }
        public bool ShouldSerializeFloorId() => __pbn__FloorId != null;
        public void ResetFloorId() => __pbn__FloorId = null;
        private uint? __pbn__FloorId;

        [global::ProtoBuf.ProtoMember(3, Name = @"prop_entity_id")]
        public uint PropEntityId
        {
            get => __pbn__PropEntityId.GetValueOrDefault();
            set => __pbn__PropEntityId = value;
        }
        public bool ShouldSerializePropEntityId() => __pbn__PropEntityId != null;
        public void ResetPropEntityId() => __pbn__PropEntityId = null;
        private uint? __pbn__PropEntityId;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SpringTransferScRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"retcode")]
        public uint Retcode
        {
            get => __pbn__Retcode.GetValueOrDefault();
            set => __pbn__Retcode = value;
        }
        public bool ShouldSerializeRetcode() => __pbn__Retcode != null;
        public void ResetRetcode() => __pbn__Retcode = null;
        private uint? __pbn__Retcode;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UpdateBuffScNotify : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"entity_id")]
        public uint EntityId
        {
            get => __pbn__EntityId.GetValueOrDefault();
            set => __pbn__EntityId = value;
        }
        public bool ShouldSerializeEntityId() => __pbn__EntityId != null;
        public void ResetEntityId() => __pbn__EntityId = null;
        private uint? __pbn__EntityId;

        [global::ProtoBuf.ProtoMember(2, Name = @"buff")]
        public BuffInfo Buff { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DelBuffScNotify : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"entity_id")]
        public uint EntityId
        {
            get => __pbn__EntityId.GetValueOrDefault();
            set => __pbn__EntityId = value;
        }
        public bool ShouldSerializeEntityId() => __pbn__EntityId != null;
        public void ResetEntityId() => __pbn__EntityId = null;
        private uint? __pbn__EntityId;

        [global::ProtoBuf.ProtoMember(2, Name = @"buff_id")]
        public uint BuffId
        {
            get => __pbn__BuffId.GetValueOrDefault();
            set => __pbn__BuffId = value;
        }
        public bool ShouldSerializeBuffId() => __pbn__BuffId != null;
        public void ResetBuffId() => __pbn__BuffId = null;
        private uint? __pbn__BuffId;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SpringRefreshCsReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"plane_id")]
        public uint PlaneId
        {
            get => __pbn__PlaneId.GetValueOrDefault();
            set => __pbn__PlaneId = value;
        }
        public bool ShouldSerializePlaneId() => __pbn__PlaneId != null;
        public void ResetPlaneId() => __pbn__PlaneId = null;
        private uint? __pbn__PlaneId;

        [global::ProtoBuf.ProtoMember(2, Name = @"floor_id")]
        public uint FloorId
        {
            get => __pbn__FloorId.GetValueOrDefault();
            set => __pbn__FloorId = value;
        }
        public bool ShouldSerializeFloorId() => __pbn__FloorId != null;
        public void ResetFloorId() => __pbn__FloorId = null;
        private uint? __pbn__FloorId;

        [global::ProtoBuf.ProtoMember(3, Name = @"prop_entity_id")]
        public uint PropEntityId
        {
            get => __pbn__PropEntityId.GetValueOrDefault();
            set => __pbn__PropEntityId = value;
        }
        public bool ShouldSerializePropEntityId() => __pbn__PropEntityId != null;
        public void ResetPropEntityId() => __pbn__PropEntityId = null;
        private uint? __pbn__PropEntityId;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SpringRefreshScRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"retcode")]
        public uint Retcode
        {
            get => __pbn__Retcode.GetValueOrDefault();
            set => __pbn__Retcode = value;
        }
        public bool ShouldSerializeRetcode() => __pbn__Retcode != null;
        public void ResetRetcode() => __pbn__Retcode = null;
        private uint? __pbn__Retcode;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LastSpringRefreshTimeNotify : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"last_time")]
        public uint LastTime
        {
            get => __pbn__LastTime.GetValueOrDefault();
            set => __pbn__LastTime = value;
        }
        public bool ShouldSerializeLastTime() => __pbn__LastTime != null;
        public void ResetLastTime() => __pbn__LastTime = null;
        private uint? __pbn__LastTime;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ReturnLastTownCsReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ReturnLastTownScRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"retcode")]
        public uint Retcode
        {
            get => __pbn__Retcode.GetValueOrDefault();
            set => __pbn__Retcode = value;
        }
        public bool ShouldSerializeRetcode() => __pbn__Retcode != null;
        public void ResetRetcode() => __pbn__Retcode = null;
        private uint? __pbn__Retcode;

        [global::ProtoBuf.ProtoMember(2, Name = @"scene")]
        public SceneInfo Scene { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class EnterSectionCsReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"section_id")]
        public uint SectionId
        {
            get => __pbn__SectionId.GetValueOrDefault();
            set => __pbn__SectionId = value;
        }
        public bool ShouldSerializeSectionId() => __pbn__SectionId != null;
        public void ResetSectionId() => __pbn__SectionId = null;
        private uint? __pbn__SectionId;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class EnterSectionScRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"retcode")]
        public uint Retcode
        {
            get => __pbn__Retcode.GetValueOrDefault();
            set => __pbn__Retcode = value;
        }
        public bool ShouldSerializeRetcode() => __pbn__Retcode != null;
        public void ResetRetcode() => __pbn__Retcode = null;
        private uint? __pbn__Retcode;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SetCurInteractEntityCsReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"entity_id")]
        public uint EntityId
        {
            get => __pbn__EntityId.GetValueOrDefault();
            set => __pbn__EntityId = value;
        }
        public bool ShouldSerializeEntityId() => __pbn__EntityId != null;
        public void ResetEntityId() => __pbn__EntityId = null;
        private uint? __pbn__EntityId;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SetCurInteractEntityScRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"retcode")]
        public uint Retcode
        {
            get => __pbn__Retcode.GetValueOrDefault();
            set => __pbn__Retcode = value;
        }
        public bool ShouldSerializeRetcode() => __pbn__Retcode != null;
        public void ResetRetcode() => __pbn__Retcode = null;
        private uint? __pbn__Retcode;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RecoverAllLineupCsReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RecoverAllLineupScRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"retcode")]
        public uint Retcode
        {
            get => __pbn__Retcode.GetValueOrDefault();
            set => __pbn__Retcode = value;
        }
        public bool ShouldSerializeRetcode() => __pbn__Retcode != null;
        public void ResetRetcode() => __pbn__Retcode = null;
        private uint? __pbn__Retcode;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SavePointsInfoNotify : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"valid_times")]
        public uint ValidTimes
        {
            get => __pbn__ValidTimes.GetValueOrDefault();
            set => __pbn__ValidTimes = value;
        }
        public bool ShouldSerializeValidTimes() => __pbn__ValidTimes != null;
        public void ResetValidTimes() => __pbn__ValidTimes = null;
        private uint? __pbn__ValidTimes;

        [global::ProtoBuf.ProtoMember(2, Name = @"refresh_time")]
        public uint RefreshTime
        {
            get => __pbn__RefreshTime.GetValueOrDefault();
            set => __pbn__RefreshTime = value;
        }
        public bool ShouldSerializeRefreshTime() => __pbn__RefreshTime != null;
        public void ResetRefreshTime() => __pbn__RefreshTime = null;
        private uint? __pbn__RefreshTime;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class StartCocoonStageCsReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"prop_entity_id")]
        public uint PropEntityId
        {
            get => __pbn__PropEntityId.GetValueOrDefault();
            set => __pbn__PropEntityId = value;
        }
        public bool ShouldSerializePropEntityId() => __pbn__PropEntityId != null;
        public void ResetPropEntityId() => __pbn__PropEntityId = null;
        private uint? __pbn__PropEntityId;

        [global::ProtoBuf.ProtoMember(2, Name = @"cocoon_id")]
        public uint CocoonId
        {
            get => __pbn__CocoonId.GetValueOrDefault();
            set => __pbn__CocoonId = value;
        }
        public bool ShouldSerializeCocoonId() => __pbn__CocoonId != null;
        public void ResetCocoonId() => __pbn__CocoonId = null;
        private uint? __pbn__CocoonId;

        [global::ProtoBuf.ProtoMember(3, Name = @"wave")]
        public uint Wave
        {
            get => __pbn__Wave.GetValueOrDefault();
            set => __pbn__Wave = value;
        }
        public bool ShouldSerializeWave() => __pbn__Wave != null;
        public void ResetWave() => __pbn__Wave = null;
        private uint? __pbn__Wave;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class StartCocoonStageScRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"retcode")]
        public uint Retcode
        {
            get => __pbn__Retcode.GetValueOrDefault();
            set => __pbn__Retcode = value;
        }
        public bool ShouldSerializeRetcode() => __pbn__Retcode != null;
        public void ResetRetcode() => __pbn__Retcode = null;
        private uint? __pbn__Retcode;

        [global::ProtoBuf.ProtoMember(2, Name = @"battle_info")]
        public SceneBattleInfo BattleInfo { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"prop_entity_id")]
        public uint PropEntityId
        {
            get => __pbn__PropEntityId.GetValueOrDefault();
            set => __pbn__PropEntityId = value;
        }
        public bool ShouldSerializePropEntityId() => __pbn__PropEntityId != null;
        public void ResetPropEntityId() => __pbn__PropEntityId = null;
        private uint? __pbn__PropEntityId;

        [global::ProtoBuf.ProtoMember(4, Name = @"cocoon_id")]
        public uint CocoonId
        {
            get => __pbn__CocoonId.GetValueOrDefault();
            set => __pbn__CocoonId = value;
        }
        public bool ShouldSerializeCocoonId() => __pbn__CocoonId != null;
        public void ResetCocoonId() => __pbn__CocoonId = null;
        private uint? __pbn__CocoonId;

        [global::ProtoBuf.ProtoMember(5, Name = @"wave")]
        public uint Wave
        {
            get => __pbn__Wave.GetValueOrDefault();
            set => __pbn__Wave = value;
        }
        public bool ShouldSerializeWave() => __pbn__Wave != null;
        public void ResetWave() => __pbn__Wave = null;
        private uint? __pbn__Wave;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class EntityBindPropCsReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"is_bind")]
        public bool IsBind
        {
            get => __pbn__IsBind.GetValueOrDefault();
            set => __pbn__IsBind = value;
        }
        public bool ShouldSerializeIsBind() => __pbn__IsBind != null;
        public void ResetIsBind() => __pbn__IsBind = null;
        private bool? __pbn__IsBind;

        [global::ProtoBuf.ProtoMember(2, Name = @"motion")]
        public MotionInfo Motion { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class EntityBindPropScRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"retcode")]
        public uint Retcode
        {
            get => __pbn__Retcode.GetValueOrDefault();
            set => __pbn__Retcode = value;
        }
        public bool ShouldSerializeRetcode() => __pbn__Retcode != null;
        public void ResetRetcode() => __pbn__Retcode = null;
        private uint? __pbn__Retcode;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SetClientPausedCsReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"paused")]
        public bool Paused
        {
            get => __pbn__Paused.GetValueOrDefault();
            set => __pbn__Paused = value;
        }
        public bool ShouldSerializePaused() => __pbn__Paused != null;
        public void ResetPaused() => __pbn__Paused = null;
        private bool? __pbn__Paused;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SetClientPausedScRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"retcode")]
        public uint Retcode
        {
            get => __pbn__Retcode.GetValueOrDefault();
            set => __pbn__Retcode = value;
        }
        public bool ShouldSerializeRetcode() => __pbn__Retcode != null;
        public void ResetRetcode() => __pbn__Retcode = null;
        private uint? __pbn__Retcode;

        [global::ProtoBuf.ProtoMember(2, Name = @"paused")]
        public bool Paused
        {
            get => __pbn__Paused.GetValueOrDefault();
            set => __pbn__Paused = value;
        }
        public bool ShouldSerializePaused() => __pbn__Paused != null;
        public void ResetPaused() => __pbn__Paused = null;
        private bool? __pbn__Paused;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PropBeHitCsReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"prop_entity_id")]
        public uint PropEntityId
        {
            get => __pbn__PropEntityId.GetValueOrDefault();
            set => __pbn__PropEntityId = value;
        }
        public bool ShouldSerializePropEntityId() => __pbn__PropEntityId != null;
        public void ResetPropEntityId() => __pbn__PropEntityId = null;
        private uint? __pbn__PropEntityId;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PropBeHitScRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"retcode")]
        public uint Retcode
        {
            get => __pbn__Retcode.GetValueOrDefault();
            set => __pbn__Retcode = value;
        }
        public bool ShouldSerializeRetcode() => __pbn__Retcode != null;
        public void ResetRetcode() => __pbn__Retcode = null;
        private uint? __pbn__Retcode;

        [global::ProtoBuf.ProtoMember(2, Name = @"prop_entity_id")]
        public uint PropEntityId
        {
            get => __pbn__PropEntityId.GetValueOrDefault();
            set => __pbn__PropEntityId = value;
        }
        public bool ShouldSerializePropEntityId() => __pbn__PropEntityId != null;
        public void ResetPropEntityId() => __pbn__PropEntityId = null;
        private uint? __pbn__PropEntityId;

    }

    [global::ProtoBuf.ProtoContract()]
    public enum CmdSceneType
    {
        CmdSceneTypeNone = 0,
        CmdSceneEntityMoveCsReq = 1401,
        CmdSceneEntityMoveScRsp = 1402,
        CmdInteractPropCsReq = 1403,
        CmdInteractPropScRsp = 1404,
        CmdSceneCastSkillCsReq = 1405,
        CmdSceneCastSkillScRsp = 1406,
        CmdGetCurSceneInfoCsReq = 1407,
        CmdGetCurSceneInfoScRsp = 1408,
        CmdSceneEntityUpdateScNotify = 1409,
        CmdSceneEntityDisappearScNotify = 1410,
        CmdSceneEntityMoveScNotify = 1411,
        CmdWaitCustomStringCsReq = 1412,
        CmdWaitCustomStringScRsp = 1413,
        CmdSpringTransferCsReq = 1414,
        CmdSpringTransferScRsp = 1415,
        CmdUpdateBuffScNotify = 1416,
        CmdDelBuffScNotify = 1417,
        CmdSpringRefreshCsReq = 1418,
        CmdSpringRefreshScRsp = 1419,
        CmdLastSpringRefreshTimeNotify = 1420,
        CmdReturnLastTownCsReq = 1421,
        CmdReturnLastTownScRsp = 1422,
        CmdSceneEnterStageCsReq = 1423,
        CmdSceneEnterStageScRsp = 1424,
        CmdEnterSectionCsReq = 1427,
        CmdEnterSectionScRsp = 1428,
        CmdSetCurInteractEntityCsReq = 1431,
        CmdSetCurInteractEntityScRsp = 1432,
        CmdRecoverAllLineupCsReq = 1433,
        CmdRecoverAllLineupScRsp = 1434,
        CmdSavePointsInfoNotify = 1435,
        CmdStartCocoonStageCsReq = 1436,
        CmdStartCocoonStageScRsp = 1437,
        CmdEntityBindPropCsReq = 1438,
        CmdEntityBindPropScRsp = 1439,
        CmdSetClientPausedCsReq = 1440,
        CmdSetClientPausedScRsp = 1441,
        CmdPropBeHitCsReq = 1442,
        CmdPropBeHitScRsp = 1443,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
