// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: cs.tutorial.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace KazusaHSR.Protocol
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Tutorial : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public uint Id
        {
            get => __pbn__Id.GetValueOrDefault();
            set => __pbn__Id = value;
        }
        public bool ShouldSerializeId() => __pbn__Id != null;
        public void ResetId() => __pbn__Id = null;
        private uint? __pbn__Id;

        [global::ProtoBuf.ProtoMember(2, Name = @"status")]
        public TutorialStatus Status
        {
            get => __pbn__Status.GetValueOrDefault();
            set => __pbn__Status = value;
        }
        public bool ShouldSerializeStatus() => __pbn__Status != null;
        public void ResetStatus() => __pbn__Status = null;
        private TutorialStatus? __pbn__Status;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TutorialGuide : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public uint Id
        {
            get => __pbn__Id.GetValueOrDefault();
            set => __pbn__Id = value;
        }
        public bool ShouldSerializeId() => __pbn__Id != null;
        public void ResetId() => __pbn__Id = null;
        private uint? __pbn__Id;

        [global::ProtoBuf.ProtoMember(2, Name = @"status")]
        public TutorialStatus Status
        {
            get => __pbn__Status.GetValueOrDefault();
            set => __pbn__Status = value;
        }
        public bool ShouldSerializeStatus() => __pbn__Status != null;
        public void ResetStatus() => __pbn__Status = null;
        private TutorialStatus? __pbn__Status;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetTutorialCsReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetTutorialScRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"retcode")]
        public uint Retcode
        {
            get => __pbn__Retcode.GetValueOrDefault();
            set => __pbn__Retcode = value;
        }
        public bool ShouldSerializeRetcode() => __pbn__Retcode != null;
        public void ResetRetcode() => __pbn__Retcode = null;
        private uint? __pbn__Retcode;

        [global::ProtoBuf.ProtoMember(2, Name = @"tutorial_list")]
        public global::System.Collections.Generic.List<Tutorial> TutorialLists { get; } = new global::System.Collections.Generic.List<Tutorial>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetTutorialGuideCsReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetTutorialGuideScRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"retcode")]
        public uint Retcode
        {
            get => __pbn__Retcode.GetValueOrDefault();
            set => __pbn__Retcode = value;
        }
        public bool ShouldSerializeRetcode() => __pbn__Retcode != null;
        public void ResetRetcode() => __pbn__Retcode = null;
        private uint? __pbn__Retcode;

        [global::ProtoBuf.ProtoMember(2, Name = @"tutorial_guide_list")]
        public global::System.Collections.Generic.List<TutorialGuide> TutorialGuideLists { get; } = new global::System.Collections.Generic.List<TutorialGuide>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UnlockTutorialCsReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"tutorial_id")]
        public uint TutorialId
        {
            get => __pbn__TutorialId.GetValueOrDefault();
            set => __pbn__TutorialId = value;
        }
        public bool ShouldSerializeTutorialId() => __pbn__TutorialId != null;
        public void ResetTutorialId() => __pbn__TutorialId = null;
        private uint? __pbn__TutorialId;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UnlockTutorialScRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"retcode")]
        public uint Retcode
        {
            get => __pbn__Retcode.GetValueOrDefault();
            set => __pbn__Retcode = value;
        }
        public bool ShouldSerializeRetcode() => __pbn__Retcode != null;
        public void ResetRetcode() => __pbn__Retcode = null;
        private uint? __pbn__Retcode;

        [global::ProtoBuf.ProtoMember(2, Name = @"tutorial")]
        public Tutorial Tutorial { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UnlockTutorialGuideCsReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"group_id")]
        public uint GroupId
        {
            get => __pbn__GroupId.GetValueOrDefault();
            set => __pbn__GroupId = value;
        }
        public bool ShouldSerializeGroupId() => __pbn__GroupId != null;
        public void ResetGroupId() => __pbn__GroupId = null;
        private uint? __pbn__GroupId;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UnlockTutorialGuideScRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"retcode")]
        public uint Retcode
        {
            get => __pbn__Retcode.GetValueOrDefault();
            set => __pbn__Retcode = value;
        }
        public bool ShouldSerializeRetcode() => __pbn__Retcode != null;
        public void ResetRetcode() => __pbn__Retcode = null;
        private uint? __pbn__Retcode;

        [global::ProtoBuf.ProtoMember(2, Name = @"tutorial_guide")]
        public TutorialGuide TutorialGuide { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class FinishTutorialCsReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"tutorial_id")]
        public uint TutorialId
        {
            get => __pbn__TutorialId.GetValueOrDefault();
            set => __pbn__TutorialId = value;
        }
        public bool ShouldSerializeTutorialId() => __pbn__TutorialId != null;
        public void ResetTutorialId() => __pbn__TutorialId = null;
        private uint? __pbn__TutorialId;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class FinishTutorialScRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"retcode")]
        public uint Retcode
        {
            get => __pbn__Retcode.GetValueOrDefault();
            set => __pbn__Retcode = value;
        }
        public bool ShouldSerializeRetcode() => __pbn__Retcode != null;
        public void ResetRetcode() => __pbn__Retcode = null;
        private uint? __pbn__Retcode;

        [global::ProtoBuf.ProtoMember(2, Name = @"tutorial")]
        public Tutorial Tutorial { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class FinishTutorialGuideCsReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"group_id")]
        public uint GroupId
        {
            get => __pbn__GroupId.GetValueOrDefault();
            set => __pbn__GroupId = value;
        }
        public bool ShouldSerializeGroupId() => __pbn__GroupId != null;
        public void ResetGroupId() => __pbn__GroupId = null;
        private uint? __pbn__GroupId;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class FinishTutorialGuideScRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"retcode")]
        public uint Retcode
        {
            get => __pbn__Retcode.GetValueOrDefault();
            set => __pbn__Retcode = value;
        }
        public bool ShouldSerializeRetcode() => __pbn__Retcode != null;
        public void ResetRetcode() => __pbn__Retcode = null;
        private uint? __pbn__Retcode;

        [global::ProtoBuf.ProtoMember(2, Name = @"tutorial_guide")]
        public TutorialGuide TutorialGuide { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"reward")]
        public RewardData Reward { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public enum CmdTutorialType
    {
        CmdTutorialTypeNone = 0,
        CmdGetTutorialCsReq = 1601,
        CmdGetTutorialScRsp = 1602,
        CmdGetTutorialGuideCsReq = 1603,
        CmdGetTutorialGuideScRsp = 1604,
        CmdUnlockTutorialCsReq = 1605,
        CmdUnlockTutorialScRsp = 1606,
        CmdUnlockTutorialGuideCsReq = 1607,
        CmdUnlockTutorialGuideScRsp = 1608,
        CmdFinishTutorialCsReq = 1609,
        CmdFinishTutorialScRsp = 1610,
        CmdFinishTutorialGuideCsReq = 1611,
        CmdFinishTutorialGuideScRsp = 1612,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum TutorialStatus
    {
        [global::ProtoBuf.ProtoEnum(Name = @"TUTORIAL_NONE")]
        TutorialNone = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"TUTORIAL_UNLOCK")]
        TutorialUnlock = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"TUTORIAL_FINISH")]
        TutorialFinish = 2,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
