// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: cs.waypoint.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace KazusaHSR.Protocol
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Waypoint : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public uint Id
        {
            get => __pbn__Id.GetValueOrDefault();
            set => __pbn__Id = value;
        }
        public bool ShouldSerializeId() => __pbn__Id != null;
        public void ResetId() => __pbn__Id = null;
        private uint? __pbn__Id;

        [global::ProtoBuf.ProtoMember(2, Name = @"finish_times")]
        public uint FinishTimes
        {
            get => __pbn__FinishTimes.GetValueOrDefault();
            set => __pbn__FinishTimes = value;
        }
        public bool ShouldSerializeFinishTimes() => __pbn__FinishTimes != null;
        public void ResetFinishTimes() => __pbn__FinishTimes = null;
        private uint? __pbn__FinishTimes;

        [global::ProtoBuf.ProtoMember(3, Name = @"is_new")]
        public bool IsNew
        {
            get => __pbn__IsNew.GetValueOrDefault();
            set => __pbn__IsNew = value;
        }
        public bool ShouldSerializeIsNew() => __pbn__IsNew != null;
        public void ResetIsNew() => __pbn__IsNew = null;
        private bool? __pbn__IsNew;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ChapterBrief : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public uint Id
        {
            get => __pbn__Id.GetValueOrDefault();
            set => __pbn__Id = value;
        }
        public bool ShouldSerializeId() => __pbn__Id != null;
        public void ResetId() => __pbn__Id = null;
        private uint? __pbn__Id;

        [global::ProtoBuf.ProtoMember(2, Name = @"finish_challenge_num")]
        public uint FinishChallengeNum
        {
            get => __pbn__FinishChallengeNum.GetValueOrDefault();
            set => __pbn__FinishChallengeNum = value;
        }
        public bool ShouldSerializeFinishChallengeNum() => __pbn__FinishChallengeNum != null;
        public void ResetFinishChallengeNum() => __pbn__FinishChallengeNum = null;
        private uint? __pbn__FinishChallengeNum;

        [global::ProtoBuf.ProtoMember(3, Name = @"taken_reward_id_list", IsPacked = true)]
        public uint[] TakenRewardIdLists { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"is_new")]
        public bool IsNew
        {
            get => __pbn__IsNew.GetValueOrDefault();
            set => __pbn__IsNew = value;
        }
        public bool ShouldSerializeIsNew() => __pbn__IsNew != null;
        public void ResetIsNew() => __pbn__IsNew = null;
        private bool? __pbn__IsNew;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Chapter : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"brief_info")]
        public ChapterBrief BriefInfo { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"waypoint_list")]
        public global::System.Collections.Generic.List<Waypoint> WaypointLists { get; } = new global::System.Collections.Generic.List<Waypoint>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetWaypointCsReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"chapter_id")]
        public uint ChapterId
        {
            get => __pbn__ChapterId.GetValueOrDefault();
            set => __pbn__ChapterId = value;
        }
        public bool ShouldSerializeChapterId() => __pbn__ChapterId != null;
        public void ResetChapterId() => __pbn__ChapterId = null;
        private uint? __pbn__ChapterId;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetWaypointScRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"retcode")]
        public uint Retcode
        {
            get => __pbn__Retcode.GetValueOrDefault();
            set => __pbn__Retcode = value;
        }
        public bool ShouldSerializeRetcode() => __pbn__Retcode != null;
        public void ResetRetcode() => __pbn__Retcode = null;
        private uint? __pbn__Retcode;

        [global::ProtoBuf.ProtoMember(2, Name = @"chapter")]
        public Chapter Chapter { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"cur_waypoint_id")]
        public uint CurWaypointId
        {
            get => __pbn__CurWaypointId.GetValueOrDefault();
            set => __pbn__CurWaypointId = value;
        }
        public bool ShouldSerializeCurWaypointId() => __pbn__CurWaypointId != null;
        public void ResetCurWaypointId() => __pbn__CurWaypointId = null;
        private uint? __pbn__CurWaypointId;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SetCurWaypointCsReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"waypoint_id")]
        public uint WaypointId
        {
            get => __pbn__WaypointId.GetValueOrDefault();
            set => __pbn__WaypointId = value;
        }
        public bool ShouldSerializeWaypointId() => __pbn__WaypointId != null;
        public void ResetWaypointId() => __pbn__WaypointId = null;
        private uint? __pbn__WaypointId;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SetCurWaypointScRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"retcode")]
        public uint Retcode
        {
            get => __pbn__Retcode.GetValueOrDefault();
            set => __pbn__Retcode = value;
        }
        public bool ShouldSerializeRetcode() => __pbn__Retcode != null;
        public void ResetRetcode() => __pbn__Retcode = null;
        private uint? __pbn__Retcode;

        [global::ProtoBuf.ProtoMember(2, Name = @"cur_waypoint_id")]
        public uint CurWaypointId
        {
            get => __pbn__CurWaypointId.GetValueOrDefault();
            set => __pbn__CurWaypointId = value;
        }
        public bool ShouldSerializeCurWaypointId() => __pbn__CurWaypointId != null;
        public void ResetCurWaypointId() => __pbn__CurWaypointId = null;
        private uint? __pbn__CurWaypointId;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetChapterCsReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetChapterScRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"retcode")]
        public uint Retcode
        {
            get => __pbn__Retcode.GetValueOrDefault();
            set => __pbn__Retcode = value;
        }
        public bool ShouldSerializeRetcode() => __pbn__Retcode != null;
        public void ResetRetcode() => __pbn__Retcode = null;
        private uint? __pbn__Retcode;

        [global::ProtoBuf.ProtoMember(2, Name = @"chapter_list")]
        public global::System.Collections.Generic.List<ChapterBrief> ChapterLists { get; } = new global::System.Collections.Generic.List<ChapterBrief>();

        [global::ProtoBuf.ProtoMember(3, Name = @"cur_waypoint_id")]
        public uint CurWaypointId
        {
            get => __pbn__CurWaypointId.GetValueOrDefault();
            set => __pbn__CurWaypointId = value;
        }
        public bool ShouldSerializeCurWaypointId() => __pbn__CurWaypointId != null;
        public void ResetCurWaypointId() => __pbn__CurWaypointId = null;
        private uint? __pbn__CurWaypointId;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class WaypointShowNewCsNotify : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"waypoint_id")]
        public uint WaypointId
        {
            get => __pbn__WaypointId.GetValueOrDefault();
            set => __pbn__WaypointId = value;
        }
        public bool ShouldSerializeWaypointId() => __pbn__WaypointId != null;
        public void ResetWaypointId() => __pbn__WaypointId = null;
        private uint? __pbn__WaypointId;

        [global::ProtoBuf.ProtoMember(2, Name = @"chapter_id")]
        public uint ChapterId
        {
            get => __pbn__ChapterId.GetValueOrDefault();
            set => __pbn__ChapterId = value;
        }
        public bool ShouldSerializeChapterId() => __pbn__ChapterId != null;
        public void ResetChapterId() => __pbn__ChapterId = null;
        private uint? __pbn__ChapterId;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TakeChapterRewardCsReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"chapter_id")]
        public uint ChapterId
        {
            get => __pbn__ChapterId.GetValueOrDefault();
            set => __pbn__ChapterId = value;
        }
        public bool ShouldSerializeChapterId() => __pbn__ChapterId != null;
        public void ResetChapterId() => __pbn__ChapterId = null;
        private uint? __pbn__ChapterId;

        [global::ProtoBuf.ProtoMember(2, Name = @"chapter_reward_id")]
        public uint ChapterRewardId
        {
            get => __pbn__ChapterRewardId.GetValueOrDefault();
            set => __pbn__ChapterRewardId = value;
        }
        public bool ShouldSerializeChapterRewardId() => __pbn__ChapterRewardId != null;
        public void ResetChapterRewardId() => __pbn__ChapterRewardId = null;
        private uint? __pbn__ChapterRewardId;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TakeChapterRewardScRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"retcode")]
        public uint Retcode
        {
            get => __pbn__Retcode.GetValueOrDefault();
            set => __pbn__Retcode = value;
        }
        public bool ShouldSerializeRetcode() => __pbn__Retcode != null;
        public void ResetRetcode() => __pbn__Retcode = null;
        private uint? __pbn__Retcode;

        [global::ProtoBuf.ProtoMember(2, Name = @"chapter_id")]
        public uint ChapterId
        {
            get => __pbn__ChapterId.GetValueOrDefault();
            set => __pbn__ChapterId = value;
        }
        public bool ShouldSerializeChapterId() => __pbn__ChapterId != null;
        public void ResetChapterId() => __pbn__ChapterId = null;
        private uint? __pbn__ChapterId;

        [global::ProtoBuf.ProtoMember(3, Name = @"chapter_reward_id")]
        public uint ChapterRewardId
        {
            get => __pbn__ChapterRewardId.GetValueOrDefault();
            set => __pbn__ChapterRewardId = value;
        }
        public bool ShouldSerializeChapterRewardId() => __pbn__ChapterRewardId != null;
        public void ResetChapterRewardId() => __pbn__ChapterRewardId = null;
        private uint? __pbn__ChapterRewardId;

    }

    [global::ProtoBuf.ProtoContract()]
    public enum CmdWaypointType
    {
        CmdWaypointTypeNone = 0,
        CmdGetWaypointCsReq = 401,
        CmdGetWaypointScRsp = 402,
        CmdSetCurWaypointCsReq = 403,
        CmdSetCurWaypointScRsp = 404,
        CmdGetChapterCsReq = 405,
        CmdGetChapterScRsp = 406,
        CmdWaypointShowNewCsNotify = 407,
        CmdTakeChapterRewardCsReq = 408,
        CmdTakeChapterRewardScRsp = 409,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum WaypointType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"WAYPOINT_TYPE_NONE")]
        WaypointTypeNone = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"WAYPOINT_TYPE_STAGE")]
        WaypointTypeStage = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"WAYPOINT_TYPE_PLOT")]
        WaypointTypePlot = 2,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum WaypointUnlockType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"WAYPOINT_UNLOCK_NONE")]
        WaypointUnlockNone = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"WAYPOINT_UNLOCK_PRE")]
        WaypointUnlockPre = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"WAYPOINT_UNLOCK_LEVEL")]
        WaypointUnlockLevel = 2,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
