// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: head.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace KazusaHSR.Protocol
{

    [global::ProtoBuf.ProtoContract()]
    public partial class PacketHead : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"packet_id")]
        public uint PacketId
        {
            get => __pbn__PacketId.GetValueOrDefault();
            set => __pbn__PacketId = value;
        }
        public bool ShouldSerializePacketId() => __pbn__PacketId != null;
        public void ResetPacketId() => __pbn__PacketId = null;
        private uint? __pbn__PacketId;

        [global::ProtoBuf.ProtoMember(2, Name = @"sign_type")]
        public uint SignType
        {
            get => __pbn__SignType.GetValueOrDefault();
            set => __pbn__SignType = value;
        }
        public bool ShouldSerializeSignType() => __pbn__SignType != null;
        public void ResetSignType() => __pbn__SignType = null;
        private uint? __pbn__SignType;

        [global::ProtoBuf.ProtoMember(3, Name = @"sign")]
        public uint Sign
        {
            get => __pbn__Sign.GetValueOrDefault();
            set => __pbn__Sign = value;
        }
        public bool ShouldSerializeSign() => __pbn__Sign != null;
        public void ResetSign() => __pbn__Sign = null;
        private uint? __pbn__Sign;

        [global::ProtoBuf.ProtoMember(4, Name = @"user_id")]
        public uint UserId
        {
            get => __pbn__UserId.GetValueOrDefault();
            set => __pbn__UserId = value;
        }
        public bool ShouldSerializeUserId() => __pbn__UserId != null;
        public void ResetUserId() => __pbn__UserId = null;
        private uint? __pbn__UserId;

        [global::ProtoBuf.ProtoMember(5, Name = @"src_addr")]
        public uint SrcAddr
        {
            get => __pbn__SrcAddr.GetValueOrDefault();
            set => __pbn__SrcAddr = value;
        }
        public bool ShouldSerializeSrcAddr() => __pbn__SrcAddr != null;
        public void ResetSrcAddr() => __pbn__SrcAddr = null;
        private uint? __pbn__SrcAddr;

        [global::ProtoBuf.ProtoMember(6, Name = @"dst_addr")]
        public uint DstAddr
        {
            get => __pbn__DstAddr.GetValueOrDefault();
            set => __pbn__DstAddr = value;
        }
        public bool ShouldSerializeDstAddr() => __pbn__DstAddr != null;
        public void ResetDstAddr() => __pbn__DstAddr = null;
        private uint? __pbn__DstAddr;

        [global::ProtoBuf.ProtoMember(7, Name = @"dispatch_type")]
        public uint DispatchType
        {
            get => __pbn__DispatchType.GetValueOrDefault();
            set => __pbn__DispatchType = value;
        }
        public bool ShouldSerializeDispatchType() => __pbn__DispatchType != null;
        public void ResetDispatchType() => __pbn__DispatchType = null;
        private uint? __pbn__DispatchType;

        [global::ProtoBuf.ProtoMember(8, Name = @"server_type")]
        public uint ServerType
        {
            get => __pbn__ServerType.GetValueOrDefault();
            set => __pbn__ServerType = value;
        }
        public bool ShouldSerializeServerType() => __pbn__ServerType != null;
        public void ResetServerType() => __pbn__ServerType = null;
        private uint? __pbn__ServerType;

        [global::ProtoBuf.ProtoMember(9, Name = @"dispatch_key")]
        public uint DispatchKey
        {
            get => __pbn__DispatchKey.GetValueOrDefault();
            set => __pbn__DispatchKey = value;
        }
        public bool ShouldSerializeDispatchKey() => __pbn__DispatchKey != null;
        public void ResetDispatchKey() => __pbn__DispatchKey = null;
        private uint? __pbn__DispatchKey;

        [global::ProtoBuf.ProtoMember(10, Name = @"user_session_id")]
        public uint UserSessionId
        {
            get => __pbn__UserSessionId.GetValueOrDefault();
            set => __pbn__UserSessionId = value;
        }
        public bool ShouldSerializeUserSessionId() => __pbn__UserSessionId != null;
        public void ResetUserSessionId() => __pbn__UserSessionId = null;
        private uint? __pbn__UserSessionId;

        [global::ProtoBuf.ProtoMember(11, Name = @"id")]
        public uint Id
        {
            get => __pbn__Id.GetValueOrDefault();
            set => __pbn__Id = value;
        }
        public bool ShouldSerializeId() => __pbn__Id != null;
        public void ResetId() => __pbn__Id = null;
        private uint? __pbn__Id;

        [global::ProtoBuf.ProtoMember(12, Name = @"coroutine_id")]
        public uint CoroutineId
        {
            get => __pbn__CoroutineId.GetValueOrDefault();
            set => __pbn__CoroutineId = value;
        }
        public bool ShouldSerializeCoroutineId() => __pbn__CoroutineId != null;
        public void ResetCoroutineId() => __pbn__CoroutineId = null;
        private uint? __pbn__CoroutineId;

        [global::ProtoBuf.ProtoMember(13, Name = @"hop_cnt")]
        public uint HopCnt
        {
            get => __pbn__HopCnt.GetValueOrDefault();
            set => __pbn__HopCnt = value;
        }
        public bool ShouldSerializeHopCnt() => __pbn__HopCnt != null;
        public void ResetHopCnt() => __pbn__HopCnt = null;
        private uint? __pbn__HopCnt;

    }

    [global::ProtoBuf.ProtoContract()]
    public enum DispatchType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"DISPATCH_TYPE_NONE")]
        DispatchTypeNone = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"DISPATCH_TYPE_BY_ADDR")]
        DispatchTypeByAddr = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"DISPATCH_TYPE_BY_MOD")]
        DispatchTypeByMod = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"DISPATCH_TYPE_BY_RAND")]
        DispatchTypeByRand = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"DISPATCH_TYPE_BY_CHASH")]
        DispatchTypeByChash = 4,
        [global::ProtoBuf.ProtoEnum(Name = @"DISPATCH_TYPE_BY_STICKY_SESSION")]
        DispatchTypeByStickySession = 5,
        [global::ProtoBuf.ProtoEnum(Name = @"DISPATCH_TYPE_BY_OBJECT")]
        DispatchTypeByObject = 6,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
