namespace KazusaHSR.GameServer.Resource;

public class TurnBasedModifierConfig : ModifierConfig
{
	public int LifeTime { get; set; }
	public int MaxLayer { get; set; }
	public DynamicFloat LayerAddWhenStack { get; set; }
	public HJHAHPBLAHP WorkingTurn { get; set; }
	public AKCDOJAKEDN LifeStepMoment { get; set; }
	public DynamicFloat PerformTime { get; set; }
	public TargetEvaluator TargetSelectRestrict { get; set; }
	public SkillTargetType TargetSelectRestrictType { get; set; }
	public BEAPKPIOEHJ[] BehaviorFlagList { get; set; }
	public TaskConfig[] OnCreate { get; set; }
	public TaskConfig[] OnDestroy { get; set; }
	public TaskConfig[] OnPhase1 { get; set; }
	public TaskConfig[] OnAllowAction { get; set; }
	public TaskConfig[] OnActionEnd { get; set; }
	public TaskConfig[] OnTurnEnd { get; set; }
	public TaskConfig[] OnListenBegin { get; set; }
	public TaskConfig[] OnPhase2 { get; set; }
	public TaskConfig[] OnProjectileHit { get; set; }
	public TaskConfig[] OnBeforeHit { get; set; }
	public TaskConfig[] OnBeforeHitAll { get; set; }
	public TaskConfig[] OnBeforeBeingHit { get; set; }
	public TaskConfig[] OnBeforeBeingHitAll { get; set; }
	public TaskConfig[] OnAfterHit { get; set; }
	public TaskConfig[] OnAfterHitAll { get; set; }
	public TaskConfig[] OnAfterBeingHit { get; set; }
	public TaskConfig[] OnAfterBeingHitAll { get; set; }
	public TaskConfig[] OnBeforeDealHeal { get; set; }
	public TaskConfig[] OnBeforeBeingHeal { get; set; }
	public TaskConfig[] OnAfterDealHeal { get; set; }
	public TaskConfig[] OnAfterBeingHeal { get; set; }
	public TaskConfig[] OnListenStanceCountDown { get; set; }
	public TaskConfig[] OnTriggerStanceCountDown { get; set; }
	public TaskConfig[] OnBeingStanceCountDown { get; set; }
	public TaskConfig[] OnTriggerLimbo { get; set; }
	public TaskConfig[] OnBeingLimbo { get; set; }
	public TaskConfig[] OnStack { get; set; }
	public TaskConfig[] OnTriggerDeath { get; set; }
	public TaskConfig[] OnCharacterDie { get; set; }
	public TaskConfig[] OnCharacterCreate { get; set; }
	public TaskConfig[] OnLimboWaitHeal { get; set; }
	public TaskConfig[] OnBeforeDying { get; set; }
	public TaskConfig[] OnHPChange { get; set; }
	public TaskConfig[] OnListenHPChange { get; set; }
	public TaskConfig[] OnSkillTypeDisableChanged { get; set; }
	public TaskConfig[] OnLockHPThresholdReached { get; set; }
	public TaskConfig[] OnBeforeAttack { get; set; }
	public TaskConfig[] OnListenBeforeAttack { get; set; }
	public TaskConfig[] OnAfterAttack { get; set; }
	public TaskConfig[] OnListenAfterAttack { get; set; }
	public TaskConfig[] OnBeforeBeingAttacked { get; set; }
	public TaskConfig[] OnAfterBeingAttacked { get; set; }
	public TaskConfig[] OnListenBeforeSkillUse { get; set; }
	public TaskConfig[] OnBeforeSkillUse { get; set; }
	public TaskConfig[] OnListenAfterSkillUse { get; set; }
	public TaskConfig[] OnAfterSkillUse { get; set; }
	public TaskConfig[] OnEnterBattle { get; set; }
	public TaskConfig[] OnCustomEvent { get; set; }
	public TaskConfig[] OnTriggerBreak { get; set; }
	public TaskConfig[] OnBeingBreak { get; set; }
	public TaskConfig[] OnListenBreak { get; set; }
	public TaskConfig[] OnEndBreak { get; set; }
	public TaskConfig[] OnUltraSkillPrepare { get; set; }
	public TaskConfig[] OnSnapshotCreate { get; set; }
	public TaskConfig[] OnAnySkillExecution { get; set; }
	public DynamicValueRangeGroup[] OnDynamicValueChange { get; set; }
	public AbilityPropertyRangeGroup[] OnAbilityPropertyChange { get; set; }
	public bool UseSnapshotEntity { get; set; }
	public string UIEffectPath { get; set; }
	public bool IsGlobalModifier { get; set; }
}
