namespace KazusaHSR.GameServer.Resource;

public enum IGIJOHMNGEL
{
	Unknow = 0,
	EnterBattle = 1,
	TurnBeginNormal = 2,
	TurnBeginHealthLow = 3,
	TurnBeginSkillReady = 4,
	ActionBegin = 5,
	ReceiveHealing = 6,
	ReceiveBuff = 7,
	LinkLead = 8,
	LinkLeadSpecial = 9,
	LinkSupport = 10,
	LinkSupportSpecial = 11,
	SkillSelect1 = 12,
	SkillSelect2 = 13,
	SkillSelectUlt = 14,
	ResultLeadKillEnemy = 15,
	ResultLeadTriggerEffect = 16,
	ResultLeadSkill1 = 17,
	ResultLeadSkill2 = 18,
	ResultLeadSkillUlt = 19,
	ResultLeadEnemyHealthLow = 20,
	ResultSupport = 21,
	ResultSupportSpecial = 22,
	Victory = 23,
	Defeat = 24,
	Revived = 25,
	EncounterHighRisk = 26,
	EncounterLowRisk = 27,
	UltraReady = 28,
	LightHit = 29,
}
